### PR TITLE
Update bencode and PyYAML

### PR DESCRIPTION
**Pull request by sharkykh**
- ~Waiting on #5091~
- [x] Update PyYAML to v3.13
	[Changelog](https://pyyaml.org/wiki/PyYAML#history) is basically nothing:
	>3.13 (2018-07-05)
	>
	>Rebuild wheels using latest Cython for Python 3.7 support.
- [x] Update `bencode` to a Py2/3 compatible package ~[`bencode_py3`](https://pypi.org/project/bencode_py3/1.1329139006/)~ [`bencode.py`](https://pypi.org/project/bencode.py/2.0.0)
	- [x] `lib/bencode` was modified.
			Instead of modifying it again, I monkeypatched it to have the same effect.
	- [x] Added tests for the monkeypatch to make sure it's working as intended.

### CODE REVIEW

**Comment by ngosang** [comment]
@sharkykh why you don't use https://pypi.org/project/bencode.py/ instead? It looks more "official" to me.

**Comment by sharkykh** [comment]
Actually, I wanted to, initially.
But, and I don't mean it in any disrespectful way to them, I just feel like that developer sometimes "abandons" their projects for months at a time. However, they're still active on GitHub it seems.

Shouldn't really matter which one I choose, it's just an API difference. So, I could.

**Comment by sharkykh** [comment]
Alright, rebased and switched to `fuzeman/bencode.py == 2.0.0`.

**Comment by ngosang** [comment]
@sharkykh LGTM. I didn't test.

**Pull request merged**
