### PR TITLE
Upgrade pytimeparse to 1.1.5

### PR DESCRIPTION
**Pull request by fernandog**
@duramato

### CODE REVIEW

**Comment by duramato** [comment]
Did it had local changes of ours? If so we need them. Also the things commented we need them uncommented for our use case.

**Comment by ratoaq2** [comment]
What's the issue? We should try to avoid as much as possible patching our libs. It might be hard to track them when updating

**Comment by duramato** [comment]
Iir I added support for years and months to the library, but as it is a relative time to the calendar, I left it commented to follow the author's "wish" so any one that wants to use year and month parsing the just needs to uncomment the relevant part

**Comment by fernandog** [comment]
This code is in the library. Just upgrading

**Comment by medariox** [comment]
I think we should stay on the latest [Pypi version](https://pypi.python.org/pypi/pytimeparse/1.1.5) to avoid future headaches.

**Comment by fernandog** [comment]
This commit *IS* the 1.1.5

future headaches?
we don't use this lib right now in medusa.
I added this library for a future PR that @duramato will create

**Comment by fernandog** [comment]
tired of wasting time explaining stuff when a simple check can be done

**Comment by medariox** [comment]
Are we adding libs for future PRs now? This lib shouldn't have been added in the first place.

**Comment by fernandog** [comment]
@medariox stop complaining! omg!

I did for @duramato to make his life easier

**Pull request merged**
