### PR TITLE
Use webroot to namespace the browser localStorage key for shows.

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
@mysterfr this should fix the issue for you.
Be aware that there are some other values stored in the localStorage cache. But I don't expect any issues with these on your install.

**Comment by mysterfr** [comment]
Hi,

I had switched to the feature/namespaced-localstorage branch yesterday, but could only test today actually.
From my testing, it doesn't change the behaviour, I'm still getting a mixed shows list.

I see you've merged into "develop", should I switch to develop as well and try again to confirm ?

**Comment by p0psicles** [comment]
Yes, only develop branch

**Comment by mysterfr** [comment]
Ok, switching to develop and coming back shortly

**Comment by mysterfr** [comment]
Didn't improve.

Current situation:
- regular instance on develop branch
- 2 other instances (docker) on master 0.5.12

Started fresh with a private browser window:
- opened a first tab, loaded of regular : correct shows list
- opened a second tab, loaded vostfr docker instance : correct shows list
- opened a third tab, loaded FR docker instance : correct shows list

Went back to first tab (regular), refreshed the page (F5), got a mixed shows list displayed.

I was hoping for the regular tab to stay clean, and have the shows mixed between the FR and VOSTFR docker instances given they're still on a "master" image, but shows from those instances we still showing up the regular instance tab, which is on "develop" (I have a warning message on top confirming I'm on develop)

**Comment by p0psicles** [comment]
They all have webroots?

**Comment by mysterfr** [comment]
Yes they do:
regular : https://my.host/medusa
docker/vostfr : https://my.host/medusa-vostfr
docker/fr : https://my.host/medusa-fr

**Comment by p0psicles** [comment]
If you open devtools -> application -> localStorage
Can you see a key like /medusa-shows?

**Comment by mysterfr** [comment]
There are two keys there : "shows" and "medusa-shows".
I suppose the "shows" one is from the docker instances ?

**Comment by p0psicles** [comment]
Yes, maybe we only know after you have the docker containers on the new code. But I don't think we have a docker tag for the develop branch

**Comment by p0psicles** [comment]
You can also switch over. The code I added also won't hurt anything.

**Comment by mysterfr** [comment]
Hi,

Having updated my docker containers to v0.5.13, now shows all instances use their own local storage "container", and the shows lists don't get mixed up between instances.

Problem solved, thanks for your help !

**Pull request merged**
