### PR TITLE
Fix recommended shows error. Fixes #5962

### LINKED ISSUE #5962: Add Recommended Shows Error
Hello!

The Add Recommended shows feature do not seem to work properly and returns the following screen for IMDB and Trakt : 

image

There is an associated error : 

```
2019-01-06 09:32:34 ERROR    Thread_0 :: [b15af93] Make sure you pass kwargs parameter `storage_key` to configure the key, that is used in the dogpile cache.
Traceback (most recent call last):
  File "/home/**********/.medusa/medusa/show/recommendations/recommended.py", line 234, in generate_key
    return kwargs['storage_key'].encode('utf-8')
KeyError: u'storage_key'
```

Medusa Info: | Branch: develop Commit: b15af934a229d46f31fa241bb40fce11761bc3a5 Version: v0.2.14 Database: 44.13
-- | --
Python Version: | 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
SSL Version: | OpenSSL 1.0.2g 1 Mar 2016
OS: | Linux-4.12.14-041214-generic-x86_64-with-Ubuntu-16.04-xenial
Locale: | en_US.UTF-8

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

@p0psicles 
Switching from Py2 to 3 and vice versa still doesn't work. The cache file needs to be delete every time. Not sure why.

### CODE REVIEW

**Comment by gacopl** [comment]
Why this is still not merged to master ?

**Comment by p0psicles** [comment]
Because we haven't released yet

**Comment by gacopl** [comment]
merged to develop on jan11, last release is from march so am asking maybe someone missed it :)

**Comment by sharkykh** [comment]
It is merged to master and released on version 0.3.0. Maybe you're not up to date? Maybe you're experiencing a different bug?

**Comment by p0psicles** [comment]
Ooh yeah. It's definitely in master.

**Comment by gacopl** [comment]
this is what i am getting when visiting add recoomended shows
Fetching of Recommender Data failed. Exception:

[Errno 22] Invalid argument

this commit looked like a fix for it

**Comment by p0psicles** [comment]
Best to create a new issue and fill out the template

**Comment by medariox** [comment]
If you are coming from Python 2.7 you need to delete the cache files (`cache/recommended.dbm`).

**Comment by gacopl** [comment]
shoot now i recall i started for couple minutes on python2 before channging systemd to use python3 that worked thank you very much!

**Pull request merged**
