### PR TITLE
Check free space before running Medusa

### PR DESCRIPTION
**Pull request by fernandog**
@medariox as you suggested

### CODE REVIEW

**Comment by ratoaq2** [comment]
Don't think this is a fix. Every time I start the application it will create and delete a 10mb file. We should just let the ouf of disk space occur. If you didn't restart the application for some time and you have low disk space this "fix" will not prevent anything

**Comment by fernandog** [comment]
No disk space will cause mako issues and all sort of errors. App cant continue to work

**Comment by duramato** [comment]
This prevents it from running in an unusable environment, running out of disk mid operation is another story imo

**Comment by medariox** [comment]
As discussed, we need a more reliable solution.

**Comment by OmgImAlexis** [comment]
Can we not check if the free space is larger than 100mb otherwise don't start? I know *NIX OSs have a cli until to check that and so does Windows.

**Pull request closed without merging**
