### PR TITLE
Feature/fix provider eztv

### PR DESCRIPTION
**Pull request by JorgMuskens**
- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Updated the URL's to point to the new domain eztv.re

### CODE REVIEW

**Review by p0psicles — COMMENTED** [review]
You added a space there?

**Comment by JorgMuskens** [comment]
> You added a space there?

Yeah need to remove that hold on for sec

**Comment by JorgMuskens** [comment]
i am not sure anymore howto start travis to check the build.
I thought last time it fired when i changed the file online. 
There is where the space came in to test.

**Comment by medariox** [comment]
Thanks for the PR. I'm not sure why Travis is not being triggered. I've opened another PR here: https://github.com/pymedusa/Medusa/pull/8711

**Pull request closed without merging**
