### PR TITLE
Fix pymedusa/Medusa/issues/1417

### PR DESCRIPTION
**Pull request by fernandog**
@FireBladeNooT can you try this? I didn't test. Its just a "guess it will work" lol

https://github.com/pymedusa/Medusa/issues/1417

ping @ratoaq2 

it will show `version`:  LOL
image

### CODE REVIEW

**Comment by ratoaq2** [comment]
You don't need to check if it's addicted provider, only the version attribute

**Comment by fernandog** [comment]
It breaks opensubtitle. It shows a '0' or some numbers

**Comment by ratoaq2** [comment]
Is it integer in opensubtitles?

**Comment by fernandog** [comment]
@ratoaq2 moved 1 down.

@duramato can you test this? i can't make addi7ed work to me

**Comment by fernandog** [comment]
@ratoaq2 i didn't test this. i can't make addi7ed work here. so don't know how it will look like

**Comment by FireBladeNooT** [comment]
@fernandog 
Hi just a question, where I can see if somebody notify me? As you do in your 1st message?
Thks

**Comment by fernandog** [comment]
https://github.com/notifications

**Comment by FireBladeNooT** [comment]
OK now I'll never miss them ^^

**Pull request merged**
