### PR TITLE
Pass str (.message) in stead of object.

### PR DESCRIPTION
**Pull request by p0psicles**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
It seems that when logging an object, it's raising exception. Dont know if this can be fixed centralized?

**Comment by labrys** [comment]
@p0psicles It can be fixed, but wanted to remove old style logger first before I fixed it... right now they have some conflicts by having them both and I'd rather not try to work around the old one while fixing the new.

**Comment by p0psicles** [comment]
@labrys any reason to not accept this as a fix for this case?

**Comment by labrys** [comment]
No not at all.

**Pull request merged**
