### PR TITLE
When the user clicks on the menu button in mobile view, clicking a

### PR DESCRIPTION
**Pull request by p0psicles**
button with a dropdown with initiate an automatic scrolldown, of 250px.

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Just want to get some feedback on this, to see if it's workable.

Try it out on mobile, and click for ex the menu button, and the on Tools.

### CODE REVIEW

**Comment by p0psicles** [comment]
@OmgImAlexis pls try it out. Curious what you think of it?

**Comment by OmgImAlexis** [comment]
I can't test this as I'm using a Macbook with only a trackpad.

**Comment by fernandog** [comment]
@p0psicles i liked. Very nice.

**Comment by fernandog** [comment]
@p0psicles clicking "shows" it scrolls too much. Confirm?

**Pull request closed without merging**
