### PR TITLE
Added TVNZ 1 logo

### PR DESCRIPTION
**Pull request by purevertigo**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by purevertigo** [comment]
I'm using the GitHub desktop app. How do I do this there?

**Comment by medariox** [comment]
See https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch#rebasing-your-project-branch-onto-another-branch

**Comment by purevertigo** [comment]
OK Done. Could you check now?

**Comment by medariox** [comment]
Thank you!

**Pull request merged**
