### PR TITLE
SnatchSelection improve:  better header

### PR DESCRIPTION
**Pull request by wimpyrbx**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

image

### CODE REVIEW

**Comment by wimpyrbx** [comment]
image

**Comment by fernandog** [comment]
The episode status change cant be in snatchSelection too.

**Comment by wimpyrbx** [comment]
can you elaborate?

**Comment by fernandog** [comment]
That listbox "changed selected to" + button "go"

**Comment by fernandog** [comment]
In displayShow I would show that listbox on the left and the colored keys om the right.

As the checkboxes to select episodes are on the left. And the column status is on the right

**Comment by wimpyrbx** [comment]
yeah i understand. for snatchselection we'll need to hide those.

**Comment by fernandog** [comment]
@thraxis can you review/approve this please?

**Comment by fernandog** [comment]
@wimpyrbx look:

@Thraxis moved away from the top menu because of that

image

**Comment by fernandog** [comment]
With my commit:
### DisplayShow
image


-----------------

### Snatch selection:

image

**Comment by wimpyrbx** [comment]
image

this happens on both displayShow and snatchSelection pages. it might need a empty row to seperate showheader from what's below.

also @Thraxis could you look at the <div> and </div> situtation? i'm not 100% sure it's correct now, but unable to see it clearly.

**Comment by Thraxis** [comment]
Why did you move the checkboxes and selection back the way they were to begin with?   that change wipes out the move that was done to tighten up the slack space under the summary table?

You now have change first , auto-selects on the right, then manual selects on the left.

**Comment by fernandog** [comment]
@Thraxis the checkboxes to change status are on the left. That's why i moved the `select` to the left to be together with the checkboxes

The colored keys i moved to the right, as the "status" column is in the right part of the screen.

space is still optimized, right?

**Comment by Thraxis** [comment]
Look at the space difference below the summary table of these two images.  Of anything I'd think we should change "Select Filtered Episodes" to "Select Episodes" to shorten that button up a bit

image

image

**Comment by wimpyrbx** [comment]
"Clear all" can also be changed to "Reset" or just "Clear"

**Pull request merged**
