### PR TITLE
Feature/add ignored required exclude option

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

This feature will add flags that change the behavior of the required words and ignored words fields for the tv_show configuration. Enabling the flag will make sure that the words provided in the shows configuration, will be excluded from the global configuration.

Will implement #5648 

### TODO:
- [x] Implement unit tests
- [x] Implement logic in Series.show_words() method
- [x] Add new options in db main.db tv_shows
- [x] Add new options in UI
- [x] Update api spec
- [x] Update api unit test
- [x] Update changelog

image

### CODE REVIEW

**Comment by udochrist** [comment]
Looking at the GUI this seems ok. 
My use case is to remove a single word from the global ignore list on a single show.

**Comment by udochrist** [comment]
hmmm. in medusa 3,o the GUI is missing the select boxes for excluded/ignored. is the final implementation. different from this feature?

**Comment by medariox** [comment]
Which boxes are you referring to? Final implementation should be the same. Try a hard cache refresh with `CTRL + F5`.

**Comment by udochrist** [comment]
YES. that fixed  it. after clearing the cache the toggle buttons appeared.

great work with 0.3.0 and thanks for the fast reply!

**Comment by scott451** [comment]
hello. i looked at this new feature. in my install it looks like the global ignore words are used for ignore words and required words as well. though adding exceptions works correctly.

**Comment by medariox** [comment]
@scott451 
Please open a new issue, this is not the right place.

**Pull request merged**
