### PR TITLE
Prepare v0.2.7 release

### PR DESCRIPTION
**Pull request by sharkykh**
I'm still unsure about what we're going to do with the `CHANGELOG.md` file,
but if it stays updated as PRs get merged, it should make the changelog easier to read.

So maybe we just list the changes here, but on release copy them over to [CHANGES.md](https://github.com/pymedusa/medusa.github.io/blob/master/news/CHANGES.md)...

### CODE REVIEW

**Comment by p0psicles** [comment]
Cant we just start to load changelog in the iframe instead of changes?

**Comment by sharkykh** [comment]
The issue with that is, it's going to require users to update Medusa before they can see the actual changelog, while currently they may see the changelog before they update (if the CDN updates in that window).

**Comment by sharkykh** [comment]
Or... we can load it directly from Github instead of the local file :thinking: ...

**Comment by OmgImAlexis** [comment]
Why don't we keep a news file for "human text" and the changelog for the automations?

**Comment by OmgImAlexis** [comment]
We could even have a link to the develop branch changelog so people can look at the to be added features and see if their issue has been fixed already.

**Comment by sharkykh** [comment]
Preview:
image

**Comment by p0psicles** [comment]
Wow, thats some clean changelog!

**Pull request merged**
