### PR TITLE
Optimize show_statistics()

### PR DESCRIPTION
**Pull request by sharkykh**
I don't know if and how much it will help for #5311 (in the meantime at least)

### CODE REVIEW

**Comment by rafi-d** [comment]
I've modified only medusa/server/web/home/handler.py . Sadly, no real change in load time of main page (  #5311 ) . About the same ~20 seconds on a slow C2D PC. 

Test clip:
https://drive.google.com/file/d/13z6O6vPUOsVY5ZDT-QSBbPpSmEhLBobM/view?usp=sharing

FYI

PS: still on older 0.29 (modified) waiting on a fix on show->manual search GUI.

Medusa Info: 
 Branch:                 master
Commit:                 54da0c77d705a23f1ce67945ba4af3e1b978dcfc                  
Version:                 Unknown                  
Database:                 44.13
-- | --
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-10-10.0.17763
Locale: | en_US.cp1255
  |

**Comment by sharkykh** [comment]
@rafi-d 	Thanks.

**Comment by medariox** [comment]
Retry DeepCode

**Comment by rafi-d** [comment]
> 
> 
> Besides the possibly moderate performance improvement, this is a nice code quality improvement. We should probably add a dedicated table about the stats to DB if we want to have an efficient way to retrieve them.

Sadly, as you can see in the test-clip, there is no speed improvement... 
Just a thought: why not keep a "cache"-copy of the last viewed screen, and just immediately display it (with some "pending update" message) ,  while you run an update job for it (like today) in the background, and refresh it when done?  

Most of the times, the user just wants to click-navigate to  some show... Maybe you can do the same thing in the show view page (most of the data are old anyway, except of the last episode).

Rafi

**Comment by sharkykh** [comment]
This DB query is only part of the problem.
The bigger issue is that Vue needs to parse the HTML provided by the server and essentially re-render everything from scratch as "Virtual DOM". There is no "easy fix". We have to complete the transition to Vue/API.

**Comment by rafi-d** [comment]
I've just tried to remove 20 out of my 71 shows that were actually marked as "Ended". To my surprise - I have managed to cut 50% of home page refresh (20 sec to 10 sec) .

Does it imply you may be doing some unnecessary checks for "static" shows (Ended/Not-active ATM) ?  

Rafi

**Comment by sharkykh** [comment]
No, no, I simply stated some facts.
And if you mean about the "there's a chance some stats won't be needed",
I just meant that there's a lot of legacy code, and maybe we'll be able to come up with a better solution.

**Pull request merged**
