### PR TITLE
Responsive changes wave 2, mostly fixes.

### PR DESCRIPTION
**Pull request by p0psicles**
* Small, banner and simple filter controls, now properly allign right.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### TODO: 
- [x] warning / error log page.
- [x] manual search

### CODE REVIEW

**Comment by fernandog** [comment]
@p0sicles can you please review/fix my PR about layouts and indexer after this PR?

**Comment by p0psicles** [comment]
Yes will do. I'll also rebase of needed.

**Comment by p0psicles** [comment]
Reminder: On schedule page:
image

**Comment by p0psicles** [comment]
I'd like to limit this PR to really "release blocking" issues. Then we can take some time after to go through the rest.

**Comment by fernandog** [comment]
@p0psicles can you replace tabs with spaces? tons of it

**Comment by p0psicles** [comment]
let's keep the branch for now?

**Pull request merged**
