### PR TITLE
Update renovate/todo config

### LINKED ISSUE #4571: Dependency deprecation warning: bower (npm)
On registry `https://registry.npmjs.org/`, the "latest" version (v1.8.4) of dependency `bower` has the following deprecation notice:

`We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/`

Marking the latest version of an npm package as deprecated results in the entire package being considered deprecated, so contact the package author you think this is a mistake.

Please take the actions necessary to rename or substitute this deprecated package and commit to your base branch. If you wish to ignore this deprecation warning and continue using `bower` as-is, please add it to your [ignoreDeps](https://renovatebot.com/docs/configuration-options/#ignoredeps) array in Renovate config before closing this issue, otherwise another issue will be recreated the next time Renovate runs.

### PR DESCRIPTION
**Pull request by sharkykh**
### renovate:
Ignore paths:
- `.build/**` - Closes #4571, closes #4614, closes #4604, closes #4608, closes #4607, closes #4606
- `themes/**` - Just duplicates of `themes-default/slim`
- `ext/**` - Future-proofing
- `lib/**` - Future-proofing

Ignore dependencies:
- `guessit` - Needs work to be upgraded. Closes #4609 

### todo:
Ignore paths:
- `.build/**`

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Also does this need to be pushed into master for it to take effect?

@ranskin if we push the changes to a branch listed in baseBranches does it update or do we need to merge it back into master?

**Comment by OmgImAlexis** [comment]
@sharkykh we'll need todo a release soon.

**Comment by rarkins** [comment]
Actually sorry I need to check source code. Been a while since I wrote it. It’s possible that config can be in both but I’m not 100% sure. Obviously the base branch config needs to be in master.

**Comment by OmgImAlexis** [comment]
We have the baseBranch set in master but wanted to update the config. I was hoping the config in dev would trump the master so we wouldn't need to wait for a release just to update Renovate.

**Comment by rarkins** [comment]
It’s possible/logical. I will double check later and let you know

**Comment by sharkykh** [comment]
> are these paths also ignored in the todo bot? I'd like to re-enable that soon.

@OmgImAlexis 
Yes, in the most part. I just updated it to include the `.build` folder as well.

**Comment by rarkins** [comment]
Update: only the config in the repository's main branch (e.g. `master`) is used, so `renovate.json` must be updated there

**Pull request merged**
