### PR TITLE
Add season pack search support for GFT

### PR DESCRIPTION
**Pull request by duramato**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

image

### CODE REVIEW

**Comment by medariox** [comment]
@fernandog 
Did you test it? This won't work like this.

**Comment by duramato** [comment]
I tested, it works

**Comment by medariox** [comment]
You should only query the category ```c42=1``` and not all of them.

**Comment by duramato** [comment]
Ah but it still works, it's just a slight enhancement i missed.

**Pull request merged**
