### PR TITLE
Add missing commas

### PR DESCRIPTION
**Pull request by p0psicles**
Fixes the episode obj queries.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by medariox** [comment]
Now that I think about it... Shouldn't we also upgrade the minor DB version?

**Comment by sharkykh** [comment]
@medariox I think you're right.
_Beginning to despise that migration system._

**Comment by p0psicles** [comment]
@medariox is this what you mean?
@sharkykh whell be rid of it in a while. Just have to continue on the sqlalchemy PR with alembic support.

**Comment by sharkykh** [comment]
Also keep in mind there are users who had issues with the previous upgrade and now they have database version `44.12` already. **This will be an issue.**!

**Comment by p0psicles** [comment]
I've started on a branch with sqlalchemy. #3792 
I've also worked with peewee. It's fast. But beside that I can't really compare the two. I know that alembic works nice with sqlal. Don't know allot about the migration support for peewee.

**Pull request merged**
