### PR TITLE
Feature/fix show updates

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
Should fix #1842

**Comment by duramato** [comment]
Just tried this:
```
2017-01-03 22:21:42 DEBUG    SHOWQUEUE-UPDATE :: [8628e37] 270916: Beginning update of Math and the Rise of Civilization
2017-01-03 22:21:42 DEBUG    SHOWQUEUE-UPDATE :: [8628e37] 270916: Retrieving show info from TVDBv2
2017-01-03 22:21:42 DEBUG    SHOWQUEUE-UPDATE :: [8628e37] 270916: Loading show info from TVDBv2
2017-01-03 22:21:45 DEBUG    SHOWQUEUE-UPDATE :: [8628e37] Trying other indexers TVmaze get_id_by_external
2017-01-03 22:21:45 DEBUG    SHOWQUEUE-UPDATE :: [8628e37] Trying other indexers TMDB get_id_by_external
2017-01-03 22:21:45 DEBUG    SHOWQUEUE-UPDATE :: [8628e37] Looking for externals using Trakt and tvdb's 270916
2017-01-03 22:22:00 WARNING  SHOWQUEUE-UPDATE :: [8628e37] Could not connect to Trakt. No http status code
``` 
It seems to just halt the Show Update if it can't grab externals from Trakt

**Comment by p0psicles** [comment]
@duramato Your on latest develop?

**Comment by duramato** [comment]
Agh fail I thought I had git checkout this branch

**Pull request merged**
