### PR TITLE
Update yggtorrent.py

### PR DESCRIPTION
**Pull request by Silvers12**
Change to work with the new site ygg.is

ATTENTION I have comment the code ligne 159 who read Publish date. It doesn't work anymore and i don't know how...

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by IDerr** [comment]
You should format your code using flake8 :D

**Comment by Silvers12** [comment]
I don't know what is flake8 ^^ I'm noob on python :p

**Comment by Silvers12** [comment]
Flake8 OK ! I had pb with space and tab ... I don't know that ...

**Comment by medariox** [comment]
Thanks, this fixes a few things. I will push another PR with the remaining changes.

**Pull request merged**
