### PR TITLE
Clean up IssueSubmitter

### LINKED ISSUE #3209: Cannot push error on github automatically
**Branch/Commit:**
```
branch: master
Commit: b16e0e5eb4ded727eebd2ab2cd9683ab597662f5
Version: v0.1.17
Database: 44.8
--
Python Version: | 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
SSL Version: | LibreSSL 2.5.5
OS: | Linux-3.16.0-4-amd64-x86_64-with
Locale: | Unknown.Unknown
```
**OS:**
`Using the linuxserver.io docker image.`
**What you did:**
```
I configured the github setting in the config.
I am using the "Personal access token" because I have 2FA on github.
Then, in the error message page on Medusa, I pushed the submit errors button.
```
**What happened:**
`
The notification tell me I have to setup my username and password first
`

**Logs:**
```
2017-10-31 21:50:05 WARNING  Thread-16 :: [b16e0e5] Please set your GitHub username and password in the config and enable debug. Unable to submit issue ticket to GitHub.
```

### PR DESCRIPTION
**Pull request by labrys**
Clean up IssueSubmitter and fixes #3209

### CODE REVIEW

**Comment by medariox** [comment]
Can you fix the failing test and rebase, please?

**Comment by labrys** [comment]
Long hours this week.  As soon as I get a chance I'll fix the test and add a test for the new error condition.

**Comment by labrys** [comment]
Couldn't tell you what couchpotato has, I could tell you that thats part of the reason I want to standardize the logging.. then we can have a log config that can decide exactly what you do or don't want logged and at what level.. For example a config could be providers logged at debug level, rest of the app at info, etc

**Comment by labrys** [comment]
Ok, sorry misunderstood what you were talking about.  The major work would need to be done in the UI.  The issue submission would likely only require minimal changes.

**Comment by p0psicles** [comment]
Ui isn't allot of work either.

**Pull request merged**
