### PR TITLE
Make use of `travis_retry`

### PR DESCRIPTION
**Pull request by sharkykh**
https://docs.travis-ci.com/user/common-build-problems/#travis_retry

### CODE REVIEW

**Comment by p0psicles** [comment]
@sharkykh on the subject. What do you think about extending renovate options. Like "postUpgradeTasks"? 
https://docs.renovatebot.com/configuration-options/?ref=hackernoon.com

**Comment by sharkykh** [comment]
I don't think you can use `postUpgradeTasks` because you need `trustLevel = 'high'` and I assume it can only be set on self-hosted instances of Renovate (not the official GitHub App)...

**Comment by p0psicles** [comment]
That makes sense. Would be awesome though if we could use it.

**Comment by p0psicles** [comment]
I had to so some digging. But in deed. Trust level High can only be used when your running your own bot

**Pull request merged**
