### PR TITLE
Prioritize plot to plot_outline

### PR DESCRIPTION
**Pull request by medariox**
It's more complete.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by duramato** [comment]
I don't remeber now the difference between them but, approved

**Comment by medariox** [comment]
Example for Arrow:
plot:

> Oliver Queen and his father are lost at sea when their luxury yacht sinks, apparently in a storm. His father dies, but Oliver survives for five years on an uncharted island and eventually returns home. But he wasn't alone on the island where he learned not only how to fight and survive but also of his father's corruption and unscrupulous business dealings. He returns to civilization a changed man, determined to put things right. He disguises himself with the hood of one of his mysterious island mentors, arms himself with a bow and sets about hunting down the men and women who have corrupted his city.


plot_outline:

> Spoiled billionaire playboy Oliver Queen is missing and presumed dead when his yacht is lost at sea. He returns five years later a changed man, determined to clean up the city as a hooded vigilante armed with a bow.

Also theTVDB uses plot, so it should be a bit more consistent.

**Comment by fernandog** [comment]
@duramato outline is a VERY basic plot. like one line. That's why in the my original PR i got plot[0]

**Comment by medariox** [comment]
@fernandog Your "original" PR didn't use ImdPie at all to get the plot information and wouldn't even work as you were using .get on an object. Additionally the attribute name is "plots" and not "plot" , so I'm not exactly sure what you are talking about.

@duramato 
plot_outline is a short summary written by IMDb, while plots are written mostly by users and usually a bit more detailed.

**Comment by fernandog** [comment]
my point is: IMDB has two fields: plot outline and plot. 
In my PR i got the plot. And not the plot outline.
I was just pointing that before imdbPie we didn't show the plot outline

**Pull request merged**
