### PR TITLE
Begin fixes for storing commit hash dynamically

### PR DESCRIPTION
**Pull request by a10kiloham**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
@a10kiloham you have to explain me. Are we or are we not including the .git folder?
As when we add the .git folder, medusa will be able to determine the cur commit hash just fine. So no further changes required.

For example the image https://github.com/linuxserver/docker-medusa already adds the .git folder.
That image doesn't have the issue we're trying to solve.

But, i'm no docker expert here. So I don't know what's best practice here.

So we first need to decide what we want. Do we add the .git folder or not?
Personally, I don't think we should want that. And just add the source, as we don't want users to provide the option of running commands like `git pull`.

**Comment by p0psicles** [comment]
@OmgImAlexis care to pitch in? As you also use docker?

**Comment by a10kiloham** [comment]
The Linux server version should be ignored imo. Not relevant since I added our own docker file.
Someone else's call whether to keep the git dir. I'd prefer to remove it after we extract the head but that's above my pay grade. My commit was a suggestion how to do exactly that. Then just rm the git directory so people don't try to pull inside a container.

**Comment by OmgImAlexis** [comment]
Is there a reason we're not just reading the version via an env that we set in the dockerfile?

**Pull request closed without merging**
