### PR TITLE
Adding savepath for qBittorrent client

### PR DESCRIPTION
**Pull request by Gabisonfire**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Gabisonfire** [comment]
Sorry @p0psicles , I'm not good at github :) I don't know what happened with my last commit, but I redid it. Let me know if anything else needs to be changed. Thank you

**Comment by Gabisonfire** [comment]
Anything missing for this merge?

**Comment by p0psicles** [comment]
I'll check today

**Comment by p0psicles** [comment]
Few things.
1. Pls run (yarn dev) and commit changes in folder themes-default/slim
2. can you add the message, that it only works with version 3.2.0?
Like:
```
<config-template v-show="clientsConfig.torrent[clients.torrents.method].pathOption" label-for="torrent_client" label="Downloaded files location">
                                                <file-browser name="torrent_path" title="Select downloaded files location" :initial-dir="clients.torrents.path" @update="clients.torrents.path = $event" />
                                                <p>where <span id="torrent_client" v-if="clientsConfig.torrent[clients.torrents.method]">{{clientsConfig.torrent[clients.torrents.method].shortTitle || clientsConfig.torrent[clients.torrents.method].title}}</span> will save downloaded files (blank for client default)
                                                    <span v-show="clients.torrents.method === 'downloadstation'"> <b>Note:</b> the destination has to be a shared folder for Synology DS</span>
                                                </p>
                                                <span v-show="clients.torrents.method === 'qbittorrent'">
                                                    <p><b>Note:</b> for qBitTorrent 3.2.0 and up</p>
                                                </span>
                                            </config-template>
```

**Comment by Gabisonfire** [comment]
Done, thanks for you help

**Pull request merged**
