### PR TITLE
Added Tvmaze

### PR DESCRIPTION
**Pull request by p0psicles**
This PR is going to add Tvmaze indexer support.

As of yet it is in progress. But should already be "usable-ish".

Part of the PR (at this time) is cachecontrol upgrade. But as this is a lib upgrade, this can just as well be PR'd into Dev as a separate PR.

Proposed changes in this PR:
- Full TVmaze indexer support
- Supports TVmaze show, season, episode and casts indexing
- ?

TODO:
- [x] Code cleanup (especially pytvmaze_api.
- [x] _parseActors support, so it can be used like: t['show name]['_actors']. Don't know where it's used, yet.

~~\- [ ] Separate the cachecontrol lib changes into commit.~~
- [x] remove the cachecontrol lib changes.
- [x] change pytvmaze_api to tvmaze_api as i've merged the pytvmaze api with the existing tvdb_api structure. So eventually there won't be allot of pytvmaze api code left.
- [x] create a better tvmaze icon. I just resized the official icon to 16x16. Maybe someone can do a better job?
- [x] Test and probably fix the show updating
- [x] Test and probably fix metadata creation
- [x] Added indexer 2 indexer mapping, when adding new shows. Tvmaze shows are now mapped to tvdbid in indexer_mapping table when a tvdb_id is provided.
- [x] Fix errors regarding scene_name_exceptions
- [x] Missing genre and network
- [x] Add episode summaries
- [x] Fix the unit tests
- [x] Think of something for scene showname/season/episode searches. Anime doesn't work atm. Implemented a mapping to tvdb (made it configurable through the indexer_config) https://github.com/pymedusa/SickRage/pull/145/commits/02520ba0f208709624be728f8c3580da2ddfd9a5
- [ ] Implement the mapping also within the medusa scene exceptions

### CODE REVIEW

**Comment by p0psicles** [comment]
image

**Comment by OmgImAlexis** [comment]
For the icon just use the 16x16 favicon from their [site](http://tvmazecdn.com/images/favico/favicon-16x16.png).

````
<link rel="apple-touch-icon" sizes="57x57" href="//tvmazecdn.com/images/favico/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="114x114" href="//tvmazecdn.com/images/favico/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="72x72" href="//tvmazecdn.com/images/favico/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="144x144" href="//tvmazecdn.com/images/favico/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="60x60" href="//tvmazecdn.com/images/favico/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="120x120" href="//tvmazecdn.com/images/favico/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="76x76" href="//tvmazecdn.com/images/favico/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="152x152" href="//tvmazecdn.com/images/favico/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="//tvmazecdn.com/images/favico/apple-touch-icon-180x180.png">

<link rel="icon" type="image/png" href="//tvmazecdn.com/images/favico/favicon-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="//tvmazecdn.com/images/favico/favicon-160x160.png" sizes="160x160">
<link rel="icon" type="image/png" href="//tvmazecdn.com/images/favico/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="//tvmazecdn.com/images/favico/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="//tvmazecdn.com/images/favico/favicon-32x32.png" sizes="32x32">
````

**Comment by fernandog** [comment]
@p0psicles 
IMO it should add an option to users migrate from tvdb to tvmaze without removing/re-adding show. what do you think?

**Comment by OmgImAlexis** [comment]
@fernandog can we not support a show being added to both at the same time? For example have the ID for both added to a single show so if one provider is down we still have it mapped to the other.

**Comment by p0psicles** [comment]
Although both feature requests are far out of scope for this PR, I do think it's a good idea to support some sort of migration between indexers. Imo i would go with a migration scenario. 

I don't feel much for Omg's suggestion, as think that's a too high risk, average reward feature. And I do believe the user should be in control over from which indexer it's adding/updating his shows. We already see allot of discrepancies between indexers, you will already have to build in allot of checks, to make sure you can migrate from one to the other. And you will probably loose all your download history.

Also all indexers would have to be inner-changeable. Meaning we should be able to migrate from thetvdb to anidb and visa versa. Can you imagine a solution where we index from both at the same time, without making drastic changes to the applications architecture?

**Comment by p0psicles** [comment]
For now this PR is on a feature freeze. Goals for he PR have been set. Or i've missed some features, that are also supported by thetvdb. We should start testing using allot of different type of shows. For ex, I noticed some bugs when trying to add a netflix show.

**Comment by OmgImAlexis** [comment]
Even if we just for now add an option to cross link the shows between indexers that'd at least allow us to "freeze" the show in the case of the indexer going down, etc.

**Comment by p0psicles** [comment]
You triggered me! We're already doing that through the table indexer_mapping. But i need to make sure tvmaze also updates the table.

**Comment by duramato** [comment]
The shows are nothing alike between indexers, tvmazre tries to follow scene while tvdb just makes up their own numbering

**Comment by p0psicles** [comment]
Now, i wouldn't say that. http://www.tvmaze.com/shows/488/naruto-shippuuden/episodes. As far as I know the "scene" uses one season for naruto shippuuden?

**Comment by duramato** [comment]
Normal shows wise, not cartoons
Transporter for example compare tvdb with maze

**Comment by OmgImAlexis** [comment]
@duramato from what I can see they're identical in season 2 and that show is only like that because of [this](https://en.wikipedia.org/wiki/Transporter:_The_Series#Episode_order_and_alternative_versions)?
http://www.tvmaze.com/shows/248/transporter-the-series/episodes
https://thetvdb.com/?tab=seasonall&id=248962&lid=7

**Comment by duramato** [comment]
@OmgImAlexis you need to compare ep titles
Another one is Pawn Stars, not all but a big portion are acording to scene on tvmaze

**Comment by OmgImAlexis** [comment]
@duramato that shows are still the same show and the episodes for the most part line up. Having it already mapped between shows before anything goes wrong with an indexer would be great. This would also allow people to switch to another indexer if there's issues with a certain one like you've described. For example you add "Transporter" only to find that exact issue so you go into the edit menu of the show and just switch it to the other indexer, the files then all get renamed and Sickrage handles everything.

**Comment by p0psicles** [comment]
Pls stay on-topic in the PR. You are discussing an issue that has nothing to do with TVmaze support. It's a generic indexers issue or more specific feature request. If indexers failover is really needed, please start a new issue there.

I will really need your support in testing the indexer with allot of different shows.

**Comment by fernandog** [comment]
@Thraxis do you plan to continue the PR 392 from the old repo? we invited you to this new org. almost all devs moved away and created this new one

**Comment by p0psicles** [comment]
I fixed some of the Quantified code recommendations.
But the unit tests are failing because the scene_exceptions.json is unavailable.

   -------------------- >> begin captured logging << --------------------
   sickrage: INFO: MainThread :: Checking for scene exception updates from https://cdn.pymedusa.com/scene_exceptions/scene_exceptions.json
   --------------------- >> end captured logging << ---------------------

**Comment by p0psicles** [comment]
@Thraxis, do you mind if I continue with your code here?

**Comment by OmgImAlexis** [comment]
@p0psicles the file is there, you sure that's the issue?

**Comment by Thraxis** [comment]
@p0psicles Feel free to continue it.  my RL is really slammed at the moment

**Comment by miigotu** [comment]
Floundering that bad that you need to keep trying to bait more people to this project @fernandog? Let the project speak for itself. Just because you have been excommunicated does not mean dirty tactics are ok.

@Thraxis you are still welcome in the other project, and there is still plenty of work going on in SickRage/SickRage
//no more responses from me

**Comment by p0psicles** [comment]
@OmgImAlexis Hm think your right. it was just the only log message I got. And I can't find an explanation for the scene_exceptions unittest failing. I haven't made any changes to that part of the code.

Also if you look into the babalyon5 test. It should always fail that test. Cause the test uses the scene_exceptions table in cache.db, to get the scene name exceptions for babylon 5. And that table  won't have a scene exception if you haven't added the show through thetvdb?

**Comment by OmgImAlexis** [comment]
@p0psicles it may have been when it was down as I moved between hosts.

**Comment by p0psicles** [comment]
@labrys Can you help me with the babylon5 unittest error? Really don't know what i'm doing wrong here.

**Comment by miigotu** [comment]
@p0psicles before every test, rm tests/*.db

**Comment by p0psicles** [comment]
tnx @miigotu, will have a look at that.

**Comment by fernandog** [comment]
@p0psicles tvmaze_rebased: https://github.com/pymedusa/SickRage/compare/tvmaze...tvmaze_rebased?expand=1

**Comment by fernandog** [comment]
@p0psicles did you found out why scene exceptions is failing even with correct URL? maybe some code change that need to pass tvdb only and not tvmaze?

**Comment by OmgImAlexis** [comment]
Just taking a guess here but @fernandog wouldn't that be caused by the scene_exceptions file not having tvmaze as a key?
Currently it just has thetvdb, maybe we needed to add tvmaze?

**Comment by fernandog** [comment]
@OmgImAlexis nice guess!! Can you duplicate?

**Comment by p0psicles** [comment]
Well i already adapted the logic, to use tvmaze's mapping to tvdb. Meaning that if there is a tvdb known for a tvmaze show, it does the scenename exception, using the tvdb key.

**Comment by ratoaq2** [comment]
Rebased

**Comment by OmgImAlexis** [comment]
@p0psicles will this be ready for 0.1.7?

**Comment by p0psicles** [comment]
No. First comes the tvdbapiv2

**Comment by OmgImAlexis** [comment]
Can we try for 2.0.0 then? Just trying to add everything to milestones so we know where we are.

**Comment by p0psicles** [comment]
For everyone who is running or testing this PR/Feature. We have continued development on this in the following PR #1534. The branch will stay for a while. As there is still some code in it, that could be merged into develop.

**Pull request closed without merging**
