### PR TITLE
fix show-refresh tries to cleanup empty "files" instead of just folders

### LINKED ISSUE #2036: Files don't have subfolders! SHOWQUEUE-REFRESH tries to clean a files subfolders
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Dev ee778e94195098ec9d602703ba0dcbb0b3db8192
**OS:** Win 10; Python 2.7.13
**What you did:**  Observed SHOWQUEUE-REFRESH logs
**What happened:**  Logs showed multiple attempts to clear a file's subdirectories.  Files don't have subdirectories.
**What you expected:**  Single attempt for the folder, and not trying subdirectories of a file.
**Logs:**
```
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\banner.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\clearart.png
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\clearlogo.png
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\fanart.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\logo.png
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season-all-banner.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season-all-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1969-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1985-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1988-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1990-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1991-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1992-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1993-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1994-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1995-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1996-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1997-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1998-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season1999-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2000-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2001-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2002-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2003-poster.jpg
2017-01-25 23:57:28 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2004-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2005-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2006-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2007-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2008-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2009-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2010-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2011-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2012-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2013-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2014-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2015-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2016-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\season2017-poster.jpg
2017-01-25 23:57:29 INFO     SHOWQUEUE-REFRESH :: [ee778e9] Trying to clean any empty folders under D:\- Series\BBC Documentaries\tvshow.nfo
```

### PR DESCRIPTION
**Pull request by fernandog**
BTW the helper method already checks if is_dir so its **just a logging issue**
but as method expects a directory, i will only pass directorty
Fixes #2036

### CODE REVIEW

**Comment by p0psicles** [comment]
@fernandog please use this setup to create PR's that fix issues.

**Comment by fernandog** [comment]
@labrys waiting your review. or somebody else's review

**Comment by fernandog** [comment]
tomorrow I will merge this as no one have comments
no comments = all good

**Comment by medariox** [comment]
The problem is that you are using delete_empty_folders() in the wrong way. It expects the path of the last folder in a directory, so that's what you have to the method.

One way to achieve that would be:
```
for path in os.walk(self.location, topdown=False):
    last_dir = path[0]
    delete_empty_folders(last_dir, self.location)
    break
```

**Comment by fernandog** [comment]
@medariox my goal is this:

Call "/show abc/" and delete all empty season folders like this:

/show abc/Season 1/ (empty)
/show abc/Season 2/ (empty)
/show abc/Season 3/ (has files)

your code does that?

**Comment by fernandog** [comment]
@medariox afaik os.walk returns tuple with directory and files right?

**Comment by fernandog** [comment]
@medariox if works as I described, please commit in this PR directly

**Comment by fernandog** [comment]
@medariox PR is failing.

**Comment by fernandog** [comment]
@ratoaq2 how to fix this loop import? i tried but I coudl'nt

**Comment by medariox** [comment]
@fernandog There is no quick fix for this, as notifiers is a big mess. I reverted the import for now. The PR should be ready.

**Comment by fernandog** [comment]
@medariox approve then please

**Comment by fernandog** [comment]
thanks

**Pull request merged**
