### PR TITLE
Fix adding custom torrent provider

### LINKED ISSUE #2552: Can't add custom torrent provider
As reported in IRC

### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

**Branch/Commit:** Dev
**OS:** Win 10
**What you did:**  Added custom torrent provider
**What happened:**  Provider failed to add, error in logs
**What you expected:**  Provider to be added
**Logs:**
```
2017-04-01 10:11:02 ERROR    Thread-37 :: [44b1453] Exception generated: canAddTorrentRssProvider() got an unexpected keyword argument 'titleTag'
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\server\web\core\base.py", line 259, in async_call
    result = function(**kwargs)
TypeError: canAddTorrentRssProvider() got an unexpected keyword argument 'titleTag'
```

### PR DESCRIPTION
**Pull request by labrys**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Fixes #2552

### CODE REVIEW

**Comment by fernandog** [comment]
@ripper1967 switch to this branch and report back please

**Comment by ripper1967** [comment]
did not fix it for me

2017-04-01 14:50:29 ERROR    Thread-27 :: [2eb0a09] Exception
generated: canAddTorrentRssProvider() got an unexpected keyword
argument 'titleTag'
Traceback (most recent call last):
  File "C:\Medusa\medusa\server\web\core\base.py", line 259, in async_call
    result = function(**kwargs)
TypeError: canAddTorrentRssProvider() got an unexpected keyword
argument 'titleTag'

Branch: bugfix/add-custom-provider
<https://github.com/pymedusa/Medusa/tree/bugfix/add-custom-provider>
Commit: 2eb0a0956c51fd83976bc889efcd1b2352288d0c
<https://github.com/pymedusa/Medusa/commit/2eb0a0956c51fd83976bc889efcd1b2352288d0c>

**Comment by labrys** [comment]
@ripper1967 try in another browser to see if your cache is blocking it.. i tried edge (since i never use it :) ) and it worked, if it still doesnt work ill restore the full `.js` change

**Comment by fernandog** [comment]
@ripper1967 you replied in the wrong PR:
https://github.com/pymedusa/Medusa/pull/2550#issuecomment-290941210

**Comment by labrys** [comment]
Per your message in the #2550 stating it still didnt work, Ill PR the full change I had earlier for you to try.

**Comment by labrys** [comment]
Per IRC, latest commit fixes issue.

**Comment by fernandog** [comment]
@labrys commit 1 works for me. I get the JS alert and not a traceback.

 That rss is invalid as i get redirect to kat page

**Comment by fernandog** [comment]
also noted that cookies are hardocoded:

`self.enable_cookies = True` in `class TorrentRssProvider(TorrentProvider):`

**Comment by fernandog** [comment]
code is completely different. don't know why. but this one makes more sense:

https://github.com/SickRage/SickRage/blob/master/sickbeard/providers/rsstorrent.py#L151-L155

**Comment by labrys** [comment]
@fernandog ok thought the first commit was sufficient, I'll close this one and push my fix to your pr #2561 instead of reverting those commits in this PR

**Comment by fernandog** [comment]
ok

**Pull request closed without merging**
