### PR TITLE
Log when can't save subtitles

### PR DESCRIPTION
**Pull request by fernandog**
Log when can't save subtitles

@duramato i didn't test. can you?

### CODE REVIEW

**Comment by fernandog** [comment]
@duramato i can't reproduce your error:

```
2017-02-15 18:48:47 ERROR    Thread-26 :: [3e479a3] Error while manual downloading subtitles. Error: Faked OSError
Traceback (most recent call last):
  File "C:/Users/Fernando/Documents/Medusa\medusa\server\web\home\handler.py", line 2101, in manual_search_subtitles
    new_manual_subtitle = subtitles.save_subtitle(tv_episode=ep_obj, subtitle_id=picked_id, video_path=video_path)
  File "C:/Users/Fernando/Documents/Medusa\medusa\subtitles.py", line 363, in save_subtitle
    return save_subs(tv_episode, video, [subtitle], video_path=video_path)
  File "C:/Users/Fernando/Documents/Medusa\medusa\subtitles.py", line 475, in save_subs
    single=not app.SUBTITLES_MULTI)
  File "C:\Users\Fernando\Documents\Medusa\lib\subliminal\core.py", line 694, in save_subtitles
    raise OSError('Faked OSError')
OSError: Faked OSError
```

**Comment by fernandog** [comment]
next time open an issue with full logs

**Comment by duramato** [comment]
I showed you logs, there was no info at all. Hence my request to show some..

**Comment by fernandog** [comment]
@ratoaq2 commneted in github channel, that as you don't have space, log can't be saved, so it can't show the traceback.

**Comment by duramato** [comment]
This all there is when there is no disk space.

```
2017-02-13 22:00:08 DEBUG    Thread-19 :: [7920ada] Scores computed for release: Marvels.Agents.of.S.H.I.E.L.D.S04E12.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Video information cached under key medusa.subtitles:video|/media/extssd/Shows/Marvel's Agents of S.H.I.E.L.D/Season 04/Marvels.Agents.of.S.H.I.E.L.D.S04E12.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Attribute tvdb_id changed from None to 5905299
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Attribute title changed from None to Hot Potato Soup
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Refining using TVEpisode information.
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Attribute year changed from None to 2013
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Attribute series_imdb_id changed from None to tt2364582
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Attribute series_tvdb_id changed from None to 263365
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Attribute series changed from Marvels Agents of S.H.I.E.L.D. to Marvel's Agents of S.H.I.E.L.D.
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Refining using TVShow information.
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Guessing using /media/extssd/Shows/Marvel's Agents of S.H.I.E.L.D/Season 04/Marvels.Agents.of.S.H.I.E.L.D.S04E12.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
2017-02-13 21:59:34 DEBUG    Thread-19 :: [7920ada] Starting release refiner [extension=release, release_name=Marvels.Agents.of.S.H.I.E.L.D.S04E12.1080p.WEB-DL.DD5.1.H264-RARBG, release_file=None]
2017-02-13 21:59:28 DEBUG    Thread-19 :: [7920ada] Scanning video /media/extssd/Shows/Marvel's Agents of S.H.I.E.L.D/Season 04/Marvels.Agents.of.S.H.I.E.L.D.S04E12.1080p.WEB-DL.DD5.1.H264-RARBG.mkv...
2017-02-13 21:59:28 INFO     Thread-19 :: [7920ada] Manual searching subtitles for: Marvels.Agents.of.S.H.I.E.L.D.S04E12.1080p.WEB-DL.DD5.1.H264-RARBG
2017-02-13 21:59:28 INFO     Thread-19 :: [7920ada] Starting to manual searching subtitles
```

**Comment by duramato** [comment]
There is disk space where the logs are located.

**Comment by fernandog** [comment]
well, i have no idea why then

**Pull request closed without merging**
