### PR TITLE
Fix post-processing ignoring files in subdirectories. Fixes #3255

### LINKED ISSUE #3255: PP ignores Folders surprisingly
**Branch/Commit:** last dev
**OS:** windows 10
**What you did:** nothing that could help to reproduice
**What happened:**
There are processable folders / files in a folder.
image
_inside every folder, there is a video file with exactly the same filename as the folder_

I force a manual PP and get these logs

**Logs:**
```
2017-11-10 17:49:54 INFO     Thread-25 :: [80db5a5] C:\Users\**********\Downloads\AutoDL\Deluge Seedbox\.stfolder: Hidden folder
2017-11-10 17:49:54 INFO     Thread-25 :: [80db5a5] I did encounter some unprocessable items: 
2017-11-10 17:49:54 INFO     Thread-25 :: [80db5a5] Successfully processed.
2017-11-10 17:49:54 DEBUG    Thread-25 :: [80db5a5] Ignoring hidden folder: .stfolder
2017-11-10 17:49:54 DEBUG    Thread-25 :: [80db5a5] No processable items found in folder: C:\Users\**********\Downloads\AutoDL
2017-11-10 17:49:54 INFO     Thread-25 :: [80db5a5] Feature 'postpone post-processing if no subtitle available' is enabled.
2017-11-10 17:49:54 DEBUG    Thread-25 :: [80db5a5] Processing path: C:\Users\**********\Downloads\AutoDL
```
**What you expected:**
This kind of files used to be PPed (even automatically)

the hidden stfolder is the folder created by Syncthing to store config files to its synchronisation.
it used to be a .stfolder file in the past (I don't know until when exactly, but fairly recently).
However, as you see, the folder was last modified in september.
I am sure I had files synced and PPed since.

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@__thumb is a thumbnail folder only right?  Why not ignore anymore?

**Comment by medariox** [comment]
@fernandog 
Every folder that starts with a dot is already been taken care of by helpers.is_hidden_folder().

**Comment by fernandog** [comment]
But this one is @ only right? @ratoaq2

**Comment by medariox** [comment]
? `IGNORED_FOLDERS = ('.AppleDouble', '.@__thumb', '@eaDir')`

it's `.@__thumb`

**Comment by fernandog** [comment]
Ok sorry

**Comment by NicoLeOca** [comment]
issue fixed!
well and quickly done thanks!

**Pull request merged**
