### PR TITLE
Yggtorrent: Fix the parsing of download link.

### LINKED ISSUE #3279: [APP SUBMITTED]: TypeError: 'NoneType' object has no attribute '__getitem__'
### INFO
**Python Version**: `2.7.12 (default, Sep 29 2017, 12:24:30) [GCC 4.9.3 20150311 (prerelease)]`
**Operating System**: `Linux-3.10.105-x86_64-with-glibc2.2.5`
**Locale**: `UTF-8`
**Branch**: [fix-rtorrent-0.9.6](../tree/fix-rtorrent-0.9.6)
**Database**: `44.8`
**Commit**: pymedusa/Medusa@7978df5eb142a954ee658e9919006777843b1f53
**Link to Log**: https://gist.github.com/8926b799dd9b0265cdb050745bb30129
### ERROR
<pre>
2017-11-18 14:58:18 ERROR    SEARCHQUEUE-MANUAL-295685 :: [Yggtorrent] :: [7978df5] Failed parsing provider.
Traceback (most recent call last):
  File "/volume2/Medusa/<a href="../blob/7978df5eb142a954ee658e9919006777843b1f53/medusa/providers/torrent/html/yggtorrent.py#L127">medusa/providers/torrent/html/yggtorrent.py</a>", line 127, in parse
    download_url = urljoin(self.url, cells[0].find('a', target='_blank')['href'])
TypeError: 'NoneType' object has no attribute '__getitem__'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)
Should fix #3279

### CODE REVIEW

**Comment by p0psicles** [comment]
Huh, we already fixed those a while back right?

**Comment by Sylanorr** [comment]
when a issue is "closed". How many time before a release ? Thank you :)

**Comment by p0psicles** [comment]
There are no rules for that.
We release when we feel develop is stable and most of the critical bugs have been resolved.

It takes effort to create a stable release. And our time is limited. So we can't do it as often as we would like to.

**Comment by p0psicles** [comment]
But its any these days now.

**Comment by Sylanorr** [comment]
I perfectly understand ! Good luck et thank you for your work, medusa is awesome 👍 !

**Pull request merged**
