### PR TITLE
Feature/anime parsing

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Added tests for:
- [x] Jojo's bizarre adventure
- [x] Cardcaptor Sakura
- [x] Inside West Coast Customs
- [ ] Teen mom
- [ ] Formula 1? Will need to have some valid release names for these.
- [x] American Dad

### CODE REVIEW

**Comment by p0psicles** [comment]
@abeloin you should be able to create branches in the pymedusa project.
That way we can collaborate more easy on PR's.

**Comment by abeloin** [comment]
> abeloin you should be able to create branches in the pymedusa project. That way we can collaborate more easy on PR's.

Sorry about that, will do starting with next PR.

**Comment by p0psicles** [comment]
@abeloin what i'm currently working on is splitting the different parsing branches (parse by air date, anime, series) and write unittests for each. Then we can start create show configurations, and add them to the tests (and extend in future). It should at least fail without your changes and succeed with.

**Comment by abeloin** [comment]
@p0psicles I've been fiddling around for the last 2 hours, trying to push a commit and it look like I don't have access to the repo.

So here is a patch of what I was trying to commit, it implement the ability to test the old behaviour:
https://gist.github.com/abeloin/7d3142a5d276d1a753bcef7e8239c995

**Pull request merged**
