### PR TITLE
Renamed showID and series_slug to series-id and series-slug.

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@medariox can you test it too just to make sure?

**Comment by p0psicles** [comment]
Sure? Workes fine here.
image

IT's not loading at all? Errors in chrome? backend?

**Comment by fernandog** [comment]
No fanart in history

**Comment by p0psicles** [comment]
You were absolutely right @fernandog. Should be fixed now.

**Comment by fernandog** [comment]
approved

**Pull request merged**
