### PR TITLE
Feature/vueify config main

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)
- [x] update open api spec
- [x] update changelog
- [x] update servier/api/v2/config.py patch routes
- [x] Added schedule.vue (from schedule.mako)
- [x] Added history.vue (from history.mako)

### CODE REVIEW

**Comment by p0psicles** [comment]
Need to sort these out.:
```
{
  'posterSortdir': 1,
  'animeSplitHomeInTabs': False,
  'layout': {
    'wide': False
  },
  'fanartBackground': True,
  'trimZero': False,
  'animeSplitHome': True,
  'gitUser**********': 'p0psicles',
  'branch': None,
  'commitHash': None,
  'fanartBackgroundOpacity': 0.4,
  'comingEpsDisplayPaused': False,
  'sortArticle': False,
  'fuzzyDating': False,
  'posterSortby': 'date',
  'news': {
    'lastRead': '2018-04-21',
    'latest': '2019-06-28',
    'unread': 15
  },
  'logs': {
    'debug': True,
    'dbDebug': False,
    'loggingLevels': {
      'error': 40,
      'warning': 30,
      'info': 20,
      'debug': 10,
      'db': 5
    },
    'numErrors': 0,
    'numWarnings': 0
  },
  'failedDownloads': {
    'enabled': False,
    'deleteFailed': False
  },
  'comingEpsSort': 'date',
  'indexerDefault': 0,
  'webInterface': {
    'notifyOnLogin': False
  },
  'cpuPresets': {
    'HIGH': 5,
    'NORMAL': 2,
    'LOW': 1,
    'DISABLED': 0
  },
  'epDefaultDeletedStatus': 6,
  'privacyLevel': 'normal',
  'downloadUrl': ''
}
```

**Comment by p0psicles** [comment]
@medariox I think I can best create a section named "layout". And dump allot of the layout related vars there. What you think?

The json snipped. Are the vars that are in config, but not configured in config-general. So mostly set in home/history/schedule

**Comment by medariox** [comment]
I think creating a new `layout` section is a good idea. But IMO not all of these should be part of the new section.

`Layout section`
```
{
  'posterSortdir': 1,
  'animeSplitHomeInTabs': False,
  'layout': {
    'wide': False
  },
  'fanartBackground': True,
  'trimZero': False,
  'animeSplitHome': True,
  'gitUser**********': 'p0psicles',
  'branch': None,
  'commitHash': None,
  'fanartBackgroundOpacity': 0.4,
  'comingEpsDisplayPaused': False,
  'sortArticle': False,
  'fuzzyDating': False,
  'posterSortby': 'date',
   'comingEpsSort': 'date',
  'indexerDefault': 0,
  'downloadUrl': '',
  'webInterface': {
    'notifyOnLogin': False
  }
}
```

`Different section(s) (general? logging? advanced?)`
```
{
  'logs': {
    'debug': True,
    'dbDebug': False,
    'privacyLevel': 'normal',
    'loggingLevels': {
      'error': 40,
      'warning': 30,
      'info': 20,
      'debug': 10,
      'db': 5
      },
  },
  'numErrors': 0,
  'numWarnings': 0
  },
  'failedDownloads': {
    'enabled': False,
    'deleteFailed': False
  },
  'cpuPresets': {
    'HIGH': 5,
    'NORMAL': 2,
    'LOW': 1,
    'DISABLED': 0
  },
  'epDefaultDeletedStatus': 6
}
```

**Comment by p0psicles** [comment]
@medariox i'm calling in the expert in this. I have no idea why it's failing on the tests/apiv2/test_config.py. Calling these routes that it tries to test manually through postman, works fine. Can you take a look at it? I'm kinda stuck.

**Comment by p0psicles** [comment]
Aah still needs some cleanup rounds

**Comment by p0psicles** [comment]
@medariox i'm done here

**Pull request merged**
