### PR TITLE
Update yggtorrent.py

### PR DESCRIPTION
**Pull request by Silvers12**
Modification to get publiation date for the new ygg.is site.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by medariox** [comment]
What is this for?

**Comment by Silvers12** [comment]
I corrected that MEDUSA not retrived the publish date of the torrent in the new site YGGtorrent.is

**Comment by medariox** [comment]
It's already fixed.

**Comment by Silvers12** [comment]
So not in the develop branch because i do a modification yesterday on the connexion to ygg and research but not for the publication date.

**Comment by Silvers12** [comment]
Ok sorry ;)

**Comment by medariox** [comment]
Nothing to be sorry about! On the contrary, thanks for the help.

**Comment by medariox** [comment]
Closing as it's not needed.

**Pull request closed without merging**
