### PR TITLE
Fix parsing for shows that have year in the title

### PR DESCRIPTION
**Pull request by thompatry**
Specific show 1923.

Added conditions to the rule wrongfully parse year in a multi part release string.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by thompatry** [comment]
I found a spacing typo. I repushed the commit to be retested.

**Comment by p0psicles** [comment]
Could you add some variations to the guessit test file? Like one that only tests the release name. So not a full path

**Comment by p0psicles** [comment]
@medariox would you mind reviewing this for me?

**Comment by medariox** [comment]
What about a title where the year is not between brackets?
e.g. `/1923 (2022)/Season 01/1923.2022.S01E01.720p.WEB.h264-Group.mkv`

**Comment by p0psicles** [comment]
That should also work. I think I even have a test for that.

**Pull request merged**
