### PR TITLE
update tmdb _request to avoid 429

### PR DESCRIPTION
**Pull request by matthewfiore**
new user with big library to import. getting lots of 429 errors when scanning existing folders.
found this and tested myself. no longer erroring out when scanning large collections.

### CODE REVIEW

**Comment by p0psicles** [comment]
@medariox what to do with this? I'm not 100% sure. But I think the lib is already monkey patched. 
@matthewfiore did you try  getting it merged with tmdbsimple project? We actually want to get rid of all the monkey patched libs.

**Comment by p0psicles** [comment]
@medariox what to do with this? I'm not 100% sure. But I think the lib is already monkey patched. 
@matthewfiore did you try  getting it merged with tmdbsimple project? We actually want to get rid of all the monkey patched libs.

**Comment by matthewfiore** [comment]
ok, i found what looks like the lib that medusa is using and submitted the same pull request on that repo.
https://github.com/celiao/tmdbsimple/pull/56
hope dev is active.

**Comment by p0psicles** [comment]
Looking at other pr's I doubt you'll get reaction soon. We make use of the  requests module. You could look into the possibility of writing a requests hook.

Thats only if tmdbsimple has the option of using an external requests session. I'm not sure if we do that.

**Comment by matthewfiore** [comment]
ok, i see now.
thanks for looking into this.
i'm excited to be using medusa even more now that i see how active you are.

what can I do now to help get this resolved?

**Comment by medariox** [comment]
@matthewfiore 
The best way is to make pressure over at https://github.com/celiao/tmdbsimple
It's in the interested of everyone to get this issue fixed upstream. Thanks!

**Pull request closed without merging**
