### PR TITLE
Implemented some exception handling too cover for most the indexer ex…

### PR DESCRIPTION
**Pull request by p0psicles**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

…ceptions. Especially the ones caused lately by tvdb connectivity issues.

### CODE REVIEW

**Comment by p0psicles** [comment]
Fixed #1749

**Comment by p0psicles** [comment]
Tnx @ripper1967. I know it won't really fix the real issue. But let's hope tvdb is getting their shit together real soon now.

**Comment by ripper1967** [comment]
Yw @p0psicles , Thanks for fixing what ya can.

**Comment by fernandog** [comment]
approved

**Pull request merged**
