### PR TITLE
Prevent dropdowns from closing when using touch navigation.

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
fix #9964 #8839

**Comment by p0psicles** [comment]
@Rouzax mind doing some testing for me?

**Comment by Rouzax** [comment]
Yeah, sure.
Git dummy here still. What is the way for me to test this?

**Comment by Rouzax** [comment]
It does work, the only downside still is that some top menus link to pages.
For instance clicking on `Tools` menu will open up the `Scheduler` page but it also opens up the menu pull down.

It would help for speed and clarity that the top menus don't navigate to anywhere in my opinion.

**Comment by p0psicles** [comment]
In the latest commit i've removed the hrefs on the menu items which have a dropdown. I also think this will be more clear to the user.

**Pull request merged**
