### PR TITLE
Add the stats API v2 endpoint

### PR DESCRIPTION
**Pull request by sharkykh**
show statistics, for example:
```json
{
  "seriesStat": [
    {
      "seriesId": 70851,
      "epTotal": 100,
      "epAirsPrev": 733416,
      "epSnatched": 0,
      "seriesSize": 178656514235,
      "epDownloaded": 100,
      "epAirsNext": null,
      "indexerId": 1
    },
    {
      "seriesId": 72449,
      "epTotal": 214,
      "epAirsPrev": 733252,
      "epSnatched": 0,
      "seriesSize": 156658035456,
      "epDownloaded": 214,
      "epAirsNext": null,
      "indexerId": 1
    }
  ],
  "maxDownloadCount": 1000
}
```

### CODE REVIEW

**Comment by sharkykh** [comment]
@p0psicles 
This is my first attempt at this, please let me know if there's anything I should have done differently.
I used the `/config` endpoint as a guideline.

**Comment by p0psicles** [comment]
Maybe this should be part of the series route like: apiv2/tvdb123/stats?
@ratoaq2 thoughts?

**Comment by sharkykh** [comment]
@p0psicles these are the stats used for the footer of every page, I believe.
```
39 Shows (33 Active) | 628 (+1)  / 629 Episodes Downloaded (100.0%)
```

**Comment by OmgImAlexis** [comment]
@p0psicles these are global stats not per series. That's why I was fine with using stats.

**Comment by sharkykh** [comment]
Should I also change every mention of the word `show` to `series`?

**Pull request merged**
