### PR TITLE
More improves in PP

### PR DESCRIPTION
**Pull request by fernandog**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@OmgImAlexis please test this and PP only that folder "x"

**Comment by OmgImAlexis** [comment]
```
Processing folder /downloads/x
PostProcessing Path: /downloads
PostProcessing Dirs: [u'x']
PostProcessing Files: []
PostProcessing VideoFiles: []
PostProcessing RarContent: 
PostProcessing VideoInRar: 
Processing folder x
Processing folder /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI
Found unwanted files: [u'Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.srr', u'Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.nfo']
Processing /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.mkv (Torrent)
Retrieving episode object for Bones S08E01
The episode file has a quality in it, using that: 1080p WEB-DL
This episode is not in history. Not marking it as priority
This episode is a priority download: False
File /tv/Bones/Bones - S08E01 - The Future in the Past 720p HDTV.mkv is smaller than /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.mkv
File exists. Marking it safe to replace. Reason: New quality is preferred. Accepting new quality
No associated files for /tv/Bones/Bones - S08E01 - The Future in the Past 720p HDTV.mkv were found during this pass
Deleting file /tv/Bones/Bones - S08E01 - The Future in the Past 720p HDTV.mkv
Found release name Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI
Destination folder for this episode: /tv/Bones
Found the following associated files for /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.mkv: [u'/downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.srr', u'/downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.nfo']
Moving file from /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.mkv to /tv/Bones/Bones - S08E01 - The Future in the Past 1080p WEB-DL.mkv 
Moving file from /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.srr to /tv/Bones/Bones - S08E01 - The Future in the Past 1080p WEB-DL.srr 
Moving file from /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.nfo to /tv/Bones/Bones - S08E01 - The Future in the Past 1080p WEB-DL.nfo-orig 
Processing succeeded for /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI/Bones.S08E01.The.Future.In.The.Past.1080p.WEB-DL.DD5.1.H.264-ECI.mkv
Deleted folder: /downloads/x/Bones.S08E01.1080p.WEB-DL.DD5.1.H.264-ECI
Processing folder /downloads/x
Unable to match /downloads/x to a show in your database. Parser result: title: downloads, type: episode, parsing_time: 0.012314081192, total_time: 0.0710420608521, absolute_episode: [], quality: Unknown, episode: [], season: None
/downloads/x : No processable items found in the folder
Successfully processed
```

**Comment by medariox** [comment]
As @labrys posted on Slack, this could be much cleaner:
```
def _is_priority(self, ep_obj, new_ep_quality):
        """
        Determine if the episode is a priority download or not (if it is expected).

        Episodes which are expected (snatched) or larger than the existing episode are priority, others are not.

        :param ep_obj: The TVEpisode object in question
        :param new_ep_quality: The quality of the episode that is being processed
        :return: True if the episode is priority, False otherwise.
        """
        _, old_ep_quality = common.Quality.split_composite_status(ep_obj.status)

        level = logger.DEBUG
        self._log(u'In history: {}'.format(self.in_history), level)
        self._log(u'Manual snatch: {}'.format(self.manually_searched), level)
        self._log(u'Existing quality: {}'.format(old_ep_quality), level)
        self._log(u'New quality: {}'.format(old_ep_quality), level)
        self._log(u'Proper: {}'.format(self.is_proper), level)

        if self.is_priority or new_ep_quality != common.Quality.UNKNOWN:
            return True
        else:
            return False
```

**Comment by fernandog** [comment]
Will spam log. Imo just need the correct log.

PP logs are bad because of this kind of logs.
Logs are not reports

**Comment by fernandog** [comment]
Also we dont log UNKNOWN quality. 
So user cant report guessit issue if naming is new or bad

**Comment by medariox** [comment]
I think this is much clearer and easier to read compared to what we currently have.

**Comment by fernandog** [comment]
also without the proper quality check it could PP a proper of different quality (lower)
the quality checks should remain

**Comment by fernandog** [comment]
I wont support any PP issues after this

**Pull request closed without merging**
