### PR TITLE
adds highlighting to table rows.

### PR DESCRIPTION
**Pull request by wimpyrbx**
also fixes colspan to 15 as it was set to 13 from before 2 more columns were added at some point. this affected columnselecter and hide/show episodes not to be displayed at the end of the table if all 15 columns were active.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

image

### CODE REVIEW

**Comment by wimpyrbx** [comment]
image

**Comment by wimpyrbx** [comment]
image

the value for change in color is in the js and atm it's +0.1
this could be added as an option in settings/interface perhaps..?

**Comment by wimpyrbx** [comment]
image

example of snatchSelection highlight row

**Comment by duramato** [comment]
This is a good addition for the history view too, at least in the compact viww

**Comment by wimpyrbx** [comment]
it's added in init.js so can be activated on subpages by adding class="triggerhighlight" to every <td> in the table that you want it active.

just added to history page as well.

**Comment by fernandog** [comment]
nice job! very nice. just tested

**Comment by wimpyrbx** [comment]
will add to Schedule page as well.

**Comment by wimpyrbx** [comment]
image

**Comment by wimpyrbx** [comment]
@Thraxis would love a review here when you have time

**Pull request merged**
