### PR TITLE
add vue to config page

### PR DESCRIPTION
**Pull request by OmgImAlexis**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
## vue
vue

## develop
develop

**Comment by OmgImAlexis** [comment]
Alignment will be fixed, header was removed for a reason. There's no need for it on that page.

**Comment by fernandog** [comment]
I persornaly prefer with header. Otherwise only URL will show the "page name"

**Comment by p0psicles** [comment]
1. @OmgImAlexis why don't you think there is a reason for it?
2. I'd like to have all js regressions fixed before we merge new changes. Is that okay with you?
3. If everything is fixed, don't forget to rebase and resolve the MEDUSA.config = data.. conflict.

**Comment by OmgImAlexis** [comment]
1. If the user needs to see what page they're on by a massive header telling them then obviously the UI isn't setup in a way that's user friendly. The user also got the page somehow so if they don't remember clicking on a link to that page then there's even more of an issue..
2. Sounds good to me.
3. Will do when I get a chance.

**Pull request merged**
