### PR TITLE
Fixed: For some shows there isn't an 'en' language available. But a result is provide, without the showname.

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

Skipping the show when it doesn't have a result in the requested language.
your can reproduce the issue by searching for: '24 h berlin' in english.

### CODE REVIEW

**Comment by fernandog** [comment]
@p0psicles how that will impact updating exiting shows that doesn't have seriesname attribute (the issue we discussed some days ago) ?

**Comment by p0psicles** [comment]
Hmm, your right. I think we should bann shows, without series name from medusa. Or at least when we get a result back, without series_name for a particular language. In that case, i only have to make a small adjustment.

**Comment by fernandog** [comment]
@p0sicles i already said one solution. just catch this error in showupdate and show as WARNING to user asking to change language metadata languaga in editshow!

**Comment by p0psicles** [comment]
This issue has nothing to do with language selection.

**Comment by labrys** [comment]
It is a language selection issue, both for searching and for metadata.  

The series referenced in #1518 has a series title in the original language (German) as can be seen by visiting this url: http://www.thetvdb.com/?tab=series&id=114171&lid=14

This can also be tested with the API by passing "de" for "Accept-Language".  Then the result does have the proper `seriesname`.  Changing "Accept-Lanugage" to any other language then returns no `seriesname`.

**Comment by labrys** [comment]
The TVDBv2 lib should support passing multiple languages to it.  Given current implementation of TVDBv2 api that would require one request per language, but that's a limitation of their API.

IMO the lib should support passing in a list of acceptable languages, and return results as a dict of results by language.  Possibly even supporting a cascading function that produces a single result where null values are replaced with updates from other languages.

Sample function:
```python
# coding = utf-8

def pop_nulls(data):
    return {k: v for k, v in data.items() if v}

def cascade_update(data, languages):
    result = {}
    language_priority = languages
    language_priority.reverse()

    for lang in language_priority:
        if lang in data:
            result.update(pop_nulls(data[lang]))
    return result

## CONTRIVED EXAMPLE
test_data = {
    'en': {'series_name': 'Attack on Titan', 'overview': 'An anime about sutff.', 'network': None},
    'ja': {'series_name': '進撃の巨人', 'overview': None, 'network': 'MBS'}
}

print(test_data)
# {'ja': {'series_name': '進撃の巨人', 'overview': None, 'network': 'MBS'}, 'en': {'series_name': 'Attack on Titan', 'overview': 'An anime about sutff.', 'network': None}}
print(cascade_update(test_data, ['fr', 'ja', 'en']))
# {'network': 'MBS', 'overview': 'An anime about sutff.', 'series_name': '進撃の巨人'}
print(cascade_update(test_data, ['en', 'ja', 'fr']))
# {'network': 'MBS', 'overview': 'An anime about sutff.', 'series_name': 'Attack on Titan'}
```

**Comment by p0psicles** [comment]
Yes Labrys your right. Missed that it only had german language. I'm pretty sure i did one search for it.

Only proper solution is to search without language, and get back all shows, with supported languages per show.

Fortunately this is already in the works. (https://trello.com/b/7zl7PE1j/api-2-x-features-and-bug-fixes).
Tvdbv2 will support fallback languages. Meaning we can define a list of languages it will fallback to. Then it will at least always have a result. With that I also hope they will return the language it has fallen back into. As that's also one of the issues with the old api and our implementation.

The second FR, is about getting back a list of supported languages for a show. We could use that, to limit the list with languages you could change the language into.

For now i'll adjust this PR, to at least handle the error. I'll remove the usage of aliases.

**Pull request merged**
