### PR TITLE
Eliminated ShellCheck warnings from init.gentoo

### PR DESCRIPTION
**Pull request by YogSottot**
Also rewrited old sed string, because of possible errors when unencrypted password in config.ini used
http://www.shellcheck.net/
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@YogSottot are you sure everything works?

**Comment by YogSottot** [comment]
@fernandog I use this init script on my system. All seems to work: start, stop, restart. And pid detection of course. With old sed i got "unexpected EOL" error, if config.ini is contain unencrypted password with ` symbol.

**Comment by medariox** [comment]
@YogSottot 

ShellCheck says:
```
Line 30:
   echo "${RUNDIR}/medusa-${web_port}.pid"
                          ^-- SC2154: web_port is referenced but not assigned.
```
Is it really an issue?

**Comment by YogSottot** [comment]
@medariox Nope.
> ShellCheck does not attempt to figure out runtime or dynamic assignments like with source "$(date +%F).sh" or eval var=value.

eval var=value - this is the case.

**Pull request merged**
