### PR TITLE
Only apply UTF-8 monkey patch when necessary

### PR DESCRIPTION
**Pull request by stefaang**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Fixes https://github.com/pymedusa/Medusa/issues/3567

### CODE REVIEW

**Comment by medariox** [comment]
Thanks for the contribution!

We still need to monkey patch to support [unicode input for pyOpenSSL](https://github.com/stefaang/Medusa/blob/6e903f348a082d5243f9fb8bb110a05b4f8258a2/medusa/init/filesystem.py#L118), so this solution won't cut it.

Don't you think that there is a problem with the Python implementation in Entware-ng?

**Comment by stefaang** [comment]
The problem was resolved by skipping the `lambda x: x` input wrapper, introduced by Medusa. It was failing on closed file object pointers being forwarded as arguments. 
I couldn't identify any root cause in the openwrt python build scripts yet.

I'd argue that monkey patching python core modules is a bit more dirty ... 
I'll refactor my fix to include the output wrapper (thanks for spotting that by the way)

**Comment by medariox** [comment]
I didn't mean to say that your solution is dirty in any way, quite the contrary actually. It just needs to handle what I pointed above as well, that's all. We are grateful for any help and contribution.

**Comment by stefaang** [comment]
Sorry, I couldn't squash the commits due to issues with line endings.
Anyway, glad to help you guys out!

**Comment by medariox** [comment]
Thanks! The code looks really good. Can you [fix the flake8 issues](https://travis-ci.org/pymedusa/Medusa/builds/326382056#L926-L929) when you get the chance?

**Comment by medariox** [comment]
Argh, need to remove the whitespaces from the blank lines, see [travis issue](https://travis-ci.org/pymedusa/Medusa/builds/326413659#L926-L928).

**Comment by labrys** [comment]
Also as an aside, the monkey patching fails for python 3.

**Pull request merged**
