### PR TITLE
Don't allow save custom provider if bad name

### PR DESCRIPTION
**Pull request by fernandog**
Fix https://github.com/pymedusa/Medusa/issues/3436

any suggestions?

### CODE REVIEW

**Comment by p0psicles** [comment]
Yeah,  I think for 1. the character is singular, as in '|' and not '||'. And 2. it should be handled in the frontend. Or at least that's my preference.

**Comment by fernandog** [comment]
@p0psicles if you try, it will show a JS alert showing user can't save it. Please try

Afaik the issue is the double pipes, and not the single pip

**Comment by p0psicles** [comment]
No havent' tested, but I believe you. But imo the request should never hit the backend, as it can be handled with a field validation in the frontend.

**Comment by fernandog** [comment]
There is already a function that validates the provider, inclusing if a name was set. I'm using it.
If you think all this validations should be done in JS please close it

image

**Comment by medariox** [comment]
Please hold this back until the Jackett config is done.

**Comment by fernandog** [comment]
@medariox isn't the issue here how we handle with old configs as you said in the issue? how is this related to Jackett?

**Comment by medariox** [comment]
It is because I've already changed these functions locally and it is going to be messy otherwise.

**Comment by fernandog** [comment]
@medariox changed branch to `add-torznab-providers`. no conflicts

**Comment by fernandog** [comment]
@medariox may I merge into your branch?

**Comment by medariox** [comment]
@fernandog
If it isn't a priority I'd like to finish the PR first.

**Comment by fernandog** [comment]
@pymedusa/developers rebased

**Comment by fernandog** [comment]
Thanks

**Pull request merged**
