### PR TITLE
Fixes for non-Vue scripts

### PR DESCRIPTION
**Pull request by sharkykh**
This PR fixes issues with scripts not working because jQuery run before DOM is constructed by Vue, and because the keyword `this` now points to the Vue instance instead of (scoped) elements.

This PR contains the following fixes:
1. Change ~all~ jQuery event handlers **outside of Vue `mounted()`** to use:
    ```js
    $(document.body).on('event', 'element(s)', event => {
    ```
2. Change ~all~ jQuery `each` loops **outside of Vue `mounted()`** to use:
    ```js
    $('elements').each((index, element) => {
    ```
3. Change ~all~ usages of `this` to the appropriate scoped object:
    For events: `event.currentTarget`
    For `each` loops: `element`

----
Some RegExp I use (I don't use "replace all"!)
Some events/loops will not be caught, so if you use this, make sure to double check for events/loops manually.

1. Events (find/replace):
    ```regex
    \$\((['"][^'"]+['"])\)\.on\((['"][\w]+['"]), *(\(\) =>|function ?\(\)) ?{
    \$\(document.body\).on\($2, $1, event => {
    ```
2. `each` loops (find/replace):
    ```regex
    (\$.+\.each)\((\(\) =>|function ?\(\)) ?{
    $1((index, element) => {
    ```

### CODE REVIEW

**Comment by sharkykh** [comment]
Quality chooser is still not working correctly (`home/editShow`, `addShows/newShow`).
I can't find what changes the selected quality `option`s...

**Comment by sharkykh** [comment]
This PR also fixes sorting history when using the compact layout (closes #3943).

**Comment by OmgImAlexis** [comment]
@p0psicles Travis keeps failing because tvdb's api is down. Shall we merge anyways?

**Comment by sharkykh** [comment]
@p0psicles looks to me like just the API tests are failing and the rest of the tests are running fine.

**Pull request merged**
