### PR TITLE
Missed label in subtitleMisssed.

### PR DESCRIPTION
**Pull request by fernandog**
Missed label in subtitleMisssed
Fixes:
- Avoid call multiple times wanted_languages
- Keep selected chosen sub to manage

Before: "All of your episodes have All subtitles."
Now: All of your episodes have all wanted subtitles.

Before: All of your episodes have Portuguese subtitles.
Now: All of your episodes have Portuguese (pt-BR) subtitles.

@duramato

### CODE REVIEW

**Comment by medariox** [comment]
Selecting "All" looks like this for me:

image

**Comment by fernandog** [comment]
@medariox mine look this way:

image

url: /manage/subtitleMissed?whichSubs=all

which is your URL? I can't reproduce yours

**Comment by medariox** [comment]
@fernandog 
I believe you need to have some missing subs to see that.

**Comment by fernandog** [comment]
Ok. But which is you URL to get that?

**Comment by fernandog** [comment]
@duramato do you also have that?

**Comment by fernandog** [comment]
@medarios waiting the URL.

**Comment by fernandog** [comment]
@medariox you can't have "All" in the label because of this:

<% label = 'all wanted' if subsLanguage == 'All'

It must show "all wanted"
Did you manually changed the URL?

**Comment by medariox** [comment]
@fernandog 
img1

img2

**Comment by fernandog** [comment]
@medariox can you test latest commit please?

**Comment by fernandog** [comment]
@duramato can you also test this please?

**Comment by fernandog** [comment]
ok thanks. should be good now

**Comment by medariox** [comment]
This is what I'm getting now:
img

**Comment by fernandog** [comment]
@medariox sorry about that. can you try again with latest commit?

**Comment by fernandog** [comment]
Don't know why the flake issues now as I only changed mako

**Comment by medariox** [comment]
@fernandog 
All good now, thanks!

The flake issues were introduced recently with [this PR](https://github.com/pymedusa/Medusa/pull/3021) (I believe it was merged directly by mistake).
I have them all fixed in [this PR](https://github.com/pymedusa/Medusa/pull/3022).

**Comment by fernandog** [comment]
@medariox approve?

**Comment by medariox** [comment]
Approved

**Pull request merged**
