### PR TITLE
Fix labels in AniDex provider. Fixes #2806

### LINKED ISSUE #2806: Anidex Exception
On develop, I'm getting this exception because they don't always post a torrent file but only a magnet link. But I don't if magnets links are fully supported by Medusa.
``` shell 
2017-05-19 09:18:34 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [AniDex] :: [c6cfffd] Failed parsing provider. Traceback: 'Traceback (most recent call last):\n  File "/opt/Medusa/medusa/providers/torrent/html/anidex.py", line 120, in parse\n    download_url = cells[labels.index(\'Torrent\')].a.get(\'href\')\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
Traceback (most recent call last):
  File "/opt/Medusa/medusa/providers/torrent/html/anidex.py", line 120, in parse
    download_url = cells[labels.index('Torrent')].a.get('href')
AttributeError: 'NoneType' object has no attribute 'get'
```

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by duramato** [comment]
I just noticed the provider has both magnets and torrents, it is missing something like this 
https://github.com/pymedusa/Medusa/blob/b4d77f7f4bb3a0a07818a49884498e8e97ac7e3e/medusa/providers/torrent/rss/extratorrent.py#L129

**Comment by p0psicles** [comment]
If this is something generic. It should be moved out of the individual provider, and moved into TorrentProvider.

**Comment by medariox** [comment]
AniDex hosts the torrents directly, so we don't have to rely on 3rd party indexers. They also always include a download link with their torrents, unlike the magnets, that can be missing.

**Comment by duramato** [comment]
We only want torrent files for black hole, magnets are preferred because of proxies. Its explained in the comment.

**Pull request merged**
