### PR TITLE
Feature/indexer glotz

### PR DESCRIPTION
**Pull request by 3OW**
- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Hi, this is my first contribution on GitHub, so please be indulgent to me. 
I added [Glotz](https://www.glotz.info/) as an indexer as someone requested here: #7570 

What is Glotz? Glotz adds german air dates to shows from TVDB. Users can add a show to Glotz and provide custom air dates for it. If a show has no entry on Glotz, the API just returns the cached original TVDB information. Its API corresponds to the TVDB API V1.

As far as I can tell, all required operations are supported (add shows and episodes, get actors, download images, get updates etc.).

add
s1

How are chances that the code gets merged? If there is a chance, what would you need from my side?

### CODE REVIEW

**Comment by p0psicles** [comment]
There might be some changes required. But one the requirements is that someone supports the code. Meaning you'll need to be around for bug reports and other issues / questions on gh.

**Comment by p0psicles** [comment]
Also pls join our discord. It's easier to discuss there.

**Comment by 3OW** [comment]
I forgot to mention that I didn't consider Python 2 support as it is EOL.

**Comment by medariox** [comment]
Good start! It would be great if you could join us on Discord: https://discord.gg/zMdAdUK

**Comment by 3OW** [comment]
> Good start! It would be great if you could join us on Discord: https://discord.gg/zMdAdUK

Thanks. I already joined yesterday.

**Comment by p0psicles** [comment]
Py2 support is required. We want users to move, but we'll need a transition period for that. You can choose not to add it. But then you'll have to wait the transition period. Which could be like a year

**Comment by p0psicles** [comment]
Ok maybe a year is allot. But we have to add a warning first. And give users (and devs) the time to move to py3. Like Synology or other Nas OS might wanna move their packages to py3

**Comment by 3OW** [comment]
Ok, I think I will provide a docker image for the Glotz community for now. So I can do bug fixing based on their feedback, get the pyglotz lib into PyPI etc. I will get back to you after you fully switched to py3.

**Comment by p0psicles** [comment]
It's not necessary to get it into pypi. Just have it in GitHub is fine.

**Pull request closed without merging**
