### PR TITLE
Don't print IMDB data and response in console

### PR DESCRIPTION
**Pull request by fernandog**
Fixes IMDB showing a LOT of logs in console

Fixes: https://github.com/pymedusa/Medusa/issues/2312

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@fernandog don't you open this upstream?

**Comment by fernandog** [comment]
Author must have a reason to keep the print

**Comment by OmgImAlexis** [comment]
Remove the print, just looked at the source and I'm pretty sure that's from when @medariox added the lib and was testing. Neither of the print statements are in the actual lib.

**Comment by fernandog** [comment]
@OmgImAlexis done

**Pull request merged**
