### PR TITLE
Remove NZB splitting option. "Fixes" #5141

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@medariox still "on hold"?

**Comment by medariox** [comment]
@OmgImAlexis 
I'm still trying to find out if this whole NZB splitting is a thing or not 😕

**Comment by OmgImAlexis** [comment]
@medariox no worries saw the "on hold" around the hotfix and wasn't sure if that was why it was added.

**Comment by medariox** [comment]
I'm going to merge this PR soon if no one can come up with a valid reason to keep that code.

**Pull request merged**
