### PR TITLE
Clarify Jackett's configuration

### PR DESCRIPTION
**Pull request by adaur**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)
Helps with #3465

### CODE REVIEW

**Comment by p0psicles** [comment]
Yeah I think i'll add proper jacket integration in the coming weeks. But tnx!

**Comment by fernandog** [comment]
Hold this PR please

**Comment by p0psicles** [comment]
Just noticed he replaced the other url.

**Comment by fernandog** [comment]
Added note to UI. If you code that we could still point to the wiki:

image

**Comment by fernandog** [comment]
His change is ok:

image

**Comment by adaur** [comment]
Thanks for the merge. At least now we'll only have to update the wiki and not have to modify the repository anymore.

**Pull request merged**
