### PR TITLE
will make table views on main page reflow for mobile

### PR DESCRIPTION
**Pull request by Thraxis**
This will cause the tables on the main page to reflow for mobile view.

image

image

image

image

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
is it possible to be an option? personally i like to swipe left-right in the table as it is in develop

**Comment by p0psicles** [comment]
@xo shouldn't we also make these packages part of the build script? As in adding them to bower?

**Comment by Thraxis** [comment]
@fernandog No this is not something that can easily be made into an option. short of using a variable load of CSS

**Comment by OmgImAlexis** [comment]
@p0psicles ideally we should actually be adding libs that don't require jQuery instead of just adding jQuery plugins. @Thraxis I've mentioned that before.

Keep in mind all of this will need to be added to Vue at some point or another and we shouldn't have to rely on jQuery for DOM manipulation so we shouldn't be using jQuery plugins when there's alternatives.

**Comment by OmgImAlexis** [comment]
@Thraxis can you show what res this was tested on as honestly this is just going to take a LOT of extra space on mobile now. Imagine someone with 100+ shows instead of 100 rows they'll now have 100*11(1,100) rows to scroll through on a small *MOBILE* screen.

**Pull request closed without merging**
