### PR TITLE
Fix Yggtorrent 

### PR DESCRIPTION
**Pull request by adaur**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)
They changed their url again... It's starting to be depressing actually.

### CODE REVIEW

**Comment by darknat** [comment]
Hmm, sorry i'm Newbie how i can download a new version of yggtorrent.py ?

**Comment by labrys** [comment]
@darknat you can either wait till this is merged to master or you can change branch.  To change branch go to `Gear Icon -> General -> Advanced tab`.  Scroll down to the `GitHub` section and select the branch from the `Branch version` dropdown.  Click `Checkout branch` and restart Medusa.

**Comment by darknat** [comment]
Thank you ! i will see that ! but i wanted update my py alone and now medusa doesn't launch :/. 
But is it an other problem, thank you !

**Comment by p0psicles** [comment]
@adaur what's the status of this? Last time I heard they changed the domain to ww1.yggtorrent.com. But that's not working anymore?

**Comment by adaur** [comment]
Apparently they switched back.

**Comment by Djedje93270** [comment]
I have tested this modification manualy in my yggtorent.py file, doesn't works, i'm in develop branch
and after the merge and update, doesn't works:

2017-12-16 16:09:41 WARNING  SEARCHQUEUE-MANUAL-289590 :: [Yggtorrent] :: [5e4c9fc] Unable to login to provider
2017-12-16 16:09:41 DEBUG    SEARCHQUEUE-MANUAL-289590 :: [Yggtorrent] :: [5e4c9fc] User-Agent: Medusa/0.1.21 (Linux; 3.10.102; fa657a0a-e272-11e7-b5c0-001132645fb4)
2017-12-16 16:09:41 DEBUG    SEARCHQUEUE-MANUAL-289590 :: [Yggtorrent] :: [5e4c9fc] GET URL: https://yggtorrent.com/ [Status: 200]
2017-12-16 16:09:41 DEBUG    SEARCHQUEUE-MANUAL-289590 :: [Yggtorrent] :: [5e4c9fc] With post data: id=**********&submit=&pass=**********
2017-12-16 16:09:41 DEBUG    SEARCHQUEUE-MANUAL-289590 :: [Yggtorrent] :: [5e4c9fc] User-Agent: Medusa/0.1.21 (Linux; 3.10.102; fa657a0a-e272-11e7-b5c0-001132645fb4)
2017-12-16 16:09:41 DEBUG    SEARCHQUEUE-MANUAL-289590 :: [Yggtorrent] :: [5e4c9fc] POST URL: https://yggtorrent.com/user/login [Status: 200]
2017-12-16 16:09:41 INFO     SEARCHQUEUE-MANUAL-289590 :: [Yggtorrent] :: [5e4c9fc] Performing episode search for Mr. Robot

**Comment by adaur** [comment]
Maybe they changed something else. I know the login check has also been changed on Medusa side recently @Labrys

**Comment by adaur** [comment]
@medariox

**Comment by Djedje93270** [comment]
It's weird because in the last few days, it was working sometimes, but now it's not working anymore

**Comment by medariox** [comment]
I'm on latest develop and it works fine here.

@Djedje93270 
It seems like you didn't enter your username and password.

**Comment by darknat** [comment]
@labrys 

> @darknat you can either wait till this is merged to master or you can change branch. To change >branch go to Gear Icon -> General -> Advanced tab. Scroll down to the GitHub section and select the >branch from the Branch version dropdown. Click Checkout branch and restart Medusa. This branch >name is fix/ygg. If you change branches, make sure you change branch back to Master after this gets >merged to continue to get updates.

I can't do that.. i can't find your  yggtorrent.py to replace my mine?

**Comment by adaur** [comment]
Why can't you?

**Comment by adaur** [comment]
So what? You're on dev now, it's enough since fix/ygg has been merged into dev. Stay there if you want the bleeding edge of Medusa.

**Comment by darknat** [comment]
Hmm, yes but i have always same problem :/

**Comment by labrys** [comment]
@darknat can you post a current debug log?

**Comment by darknat** [comment]
@labrys , you want that https://pastebin.com/EHnqenvZ ?

**Comment by labrys** [comment]
Ok couple of questions.  Can you check your config.ini to make sure you have the correct username and password configured.  Do you have any non-ascii characters in your username or password, for example accented characters like `á`.

**Comment by darknat** [comment]
Yes no problem With my username or password :/

But i have try to delete last lines in .py ( with my error , unable to...)
And now i can search and see torrent but i can't download.

**Pull request merged**
