### PR TITLE
Made cdn.pymedusa.com configurable in app.

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

@OmgImAlexis, here you go.,
Can you double check I got everything?

### CODE REVIEW

**Comment by duramato** [comment]
What is the benefit of this? I see this as a superfluous config that can allows users to break Medusa's behaviour (scene exceptions etc) by changing it to something not our "CDN".

**Comment by p0psicles** [comment]
Because without this change, users can't change source code? I did it because it was a request from OMG. As she'd like to have the domain in one location. As she was experimenting with other hostings.

**Comment by duramato** [comment]
But users **shouldn't** change it, we can't foresee possible issues if people try to use something not our "CDN". If it's for developing it can be changed in the source code.

**Comment by labrys** [comment]
Personally I think it *should * be a config var (not something set in the UI ofc) as then it separates logic from data.... the URL is just data, data should be easy to change, the code should contain logic only as much as possible.

**Comment by p0psicles** [comment]
well for most data yes, only this is so tightly bound to the application, that I don't really see a use for making this available as configuration option.

**Comment by labrys** [comment]
Well for example, if the CDN is down for any reason a user could fix it by pointing to the github.io repo which is the source.

**Comment by p0psicles** [comment]
I feel we shouldn't suggest this as an option to users, as 1. it will only confuse them, 2. users trying to change it but make a mistake will only increase the amount of issue reports, and 3. one of the points of using a CDN is it's higher availability.

**Comment by p0psicles** [comment]
Well I have more reasons, but i'd hope 3 is enough ;-)

**Comment by labrys** [comment]
Its not an option for the users.  Its a configuration file.  I also advocate splitting the configurations as well.  For example user, provider, and application configs.  As this would be an app config it wouldn't normally be touched by the user.

**Comment by labrys** [comment]
As a further example X11 config on linux.  The conf has settings that generally should not be changed by a user and its recommended that you use a utility to change them to avoid problems (the medusa UI in our case).  If you go against advice, it's on you.

**Comment by fernandog** [comment]
Its hidden setting. Only editing config.ini users will be able to change it.
Lets move on as there is other stuff that needed to be tested/coded.

**Comment by p0psicles** [comment]
Yeah your right fernandog, dropping the discussion.

**Pull request merged**
