### PR TITLE
[Hotfix] Use T411 new domain

### PR DESCRIPTION
**Pull request by fernandog**
again another domain change
@duramato

### CODE REVIEW

**Comment by IDerr** [comment]
Yes exactly :D

**Comment by lilp69** [comment]
Still not merge commit for new t411 address?

**Comment by IDerr** [comment]
@lilp69 Seems to work on develop for the moment thanks to redirections, I think

**Comment by p0psicles** [comment]
We're not going to hotfix this. If needed we look into alternative solution

**Comment by IDerr** [comment]
When the .ai domain will be down, you'll have to hotfix this.

**Pull request closed without merging**
