### PR TITLE
Update provider yggtorrent URL and authentification mechanism and add env var to override yggtorrent URL

### PR DESCRIPTION
**Pull request by StudioEtrange**
* Update torrent provider "yggtorrent" URL and authentification mechanism
because the authentification mechanism has changed.

* Add the possibility to override yggtorrent URL with an environement variable named MEDUSA_YGGTORRENT_OVERRIDE_URL. Because yggtorent change often

- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by StudioEtrange** [comment]
fixes #11720

**Comment by andrptrc** [comment]
Any news on that PR ?

**Comment by jaytonic** [comment]
Is there anybody able to validate this PR? YGG is my most used source.

**Comment by medariox** [comment]
Thank you!

**Comment by StudioEtrange** [comment]
@medariox  why did you remove the optionnal way to fix yggtorrent url with an environment variable ?
without it, we have to change the code source everytime the url change. So we have to redeploy medusa each time, repackage it and eventually rebuild docker image if we use it.
And the url change very very often

It is not useless without any way to change the url without changing the code ....

**Comment by medariox** [comment]
> @medariox  why did you remove the optionnal way to fix yggtorrent url with an environment variable ?
> 
> without it, we have to change the code source everytime the url change. So we have to redeploy medusa each time, repackage it and eventually rebuild docker image if we use it.
> 
> And the url change very very often
> 
> 
> 
> This provider is not useable without a way to change the url without changing the code ....

You can change the URL in the provider settings.

**Comment by andrptrc** [comment]
Hi thanks for the PR update, I still have 403 Forbidden errors, even after putting "https://ygg.re" inside custom url field and setting my ygg_ cookie. Any idea on what i'm missing ?

**Comment by StudioEtrange** [comment]
> Hi thanks for the PR update, I still have 403 Forbidden errors, even after putting "https://ygg.re" inside custom url field and setting my ygg_ cookie. Any idea on what i'm missing ?
> 
> ```
> The response returned a non-200 response while requesting url https://www.ygg.re/auth/process_login Error: HTTPError('403 Client Error: Forbidden for url: https://www.ygg.re/auth/process_login')
> ```

Why do you set the cookie ?
I do not set anything before using this provider

**Comment by andrptrc** [comment]
I tried to follow the documentation. If you don't use this settings how do you configure the provider for it to work?

**Comment by StudioEtrange** [comment]
> I tried to follow the documentation. If you don't use this settings how do you configure the provider for it to work?

I cannot manage to make it work again.

It seems a problem again with cloudflare...

this yggtorrent provider is brokern for now, i did not found any solution... :/

**Comment by andrptrc** [comment]
Oh okay... I found this repository: https://github.com/LimeDrive/ygg-rss-proxy
Perhaps trying to configure a custom provider using the proxy can work.
I will try when i have time and let you know

**Comment by alphayax** [comment]
Hello there ! Any update about the ygg provider ?

**Pull request merged**
