### PR TITLE
Lowercase 'e' in multi-episode split naming

### PR DESCRIPTION
**Pull request by nmaggioni**
I came across a few split episodes and noticed that the naming couldn't be made coherent with the rest of my scheme: the `E` for the second episode in a split was forcibly uppercase. This PR introduces an additional dropdown value to make it lowercase.

Before:
Before

After (additional option):
After

---

- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once.
- [X] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
You have to refresh the snapshots. jest --updateSnapshot.

**Comment by p0psicles** [comment]
Also fix import order .
tv/episode.py:27:1: I101 Imported names are in the wrong order. Should be ARCHIVED, DOWNLOADED, NAMING_DUPLICATE, NAMING_EXTEND, NAMING_LIMITED_EXTEND, NAMING_LIMITED_EXTEND_E_LOWER_PREFIXED, NAMING_LIMITED_EXTEND_E_UPPER_PREFIXED, NAMING_SEPARATED_REPEAT, Quality, SKIPPED, SNATCHED, SNATCHED_BEST, SNATCHED_PROPER, UNAIRED, UNSET, WANTED, statusStrings

**Comment by nmaggioni** [comment]
Sorry, I couldn't find much info on the testing setup - I should have looked directly at CI runs.

**Comment by p0psicles** [comment]
Can you add a small changelog line in CHANGELOG.md?

**Pull request merged**
