### PR TITLE
Run WindowsSelectorEventLoop event loop explicit on windows and py3.

### PR DESCRIPTION
**Pull request by p0psicles**
* Required from python3.8.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by sharkykh** [comment]
FYI this will not work for Python 3.5 and 3.6 as `WindowsSelectorEventLoopPolicy` is only available on 3.7.0 and newer:
https://docs.python.org/3.7/whatsnew/changelog.html#id98
> [bpo-33792](https://bugs.python.org/issue33792): Add `asyncio.WindowsSelectorEventLoopPolicy` and `asyncio.WindowsProactorEventLoopPolicy`.

More info from [Tornado](https://www.tornadoweb.org/en/stable/index.html#installation):
> On Windows, Tornado requires the `WindowsSelectorEventLoop`. This is
the default in Python 3.7 and older, but Python 3.8 defaults to an
event loop that is not compatible with Tornado. Applications that use
Tornado on Windows with Python 3.8 must call
`asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())`
at the beginning of their `main` file/function.

I suggest
```py
# We need to set the WindowsSelectorEventLoop event loop on python 3 (3.8 and higher) running on windows
if sys.platform == 'win32':
    try:
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    except AttributeError:  # Only available since Python 3.7.0
        pass
```

**Comment by medariox** [comment]
@sharkykh 
Good catch! Mind opening a PR?

**Comment by p0psicles** [comment]
From what is Read was that it was always available below 3.8. But from 3.8 needed to be set explicitly. 

Good to know.
Tnx

**Comment by sharkykh** [comment]
@medariox Sure
@p0psicles It was the default up until 3.8. Tornado says that since 3.8 the default policy on Windows is not compatible with Tornado.

**Pull request merged**
