### PR TITLE
Don't refresh xem data when loading home page even data is outdated

### PR DESCRIPTION
**Pull request by fernandog**
@p0psicles @duramato 

sorry about that @ripper1967

### CODE REVIEW

**Comment by p0psicles** [comment]
I think this is okay for now, until someone starts on scheduling the updates, and removing the persistent next_refresh data in db. Just perform a refresh on show_update. And add a button for manually refreshing it, would be enough, and remove allot of complexity.

**Comment by fernandog** [comment]
Imo thos should be done in show refresh only (3am)

**Comment by labrys** [comment]
@fernandog I agree.  With possibly an option to force it later.

**Comment by ripper1967** [comment]
@fernandog i agree an option to force it later would be ok.

**Pull request merged**
