### PR TITLE
fix missing vue pages

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Closes https://github.com/pymedusa/Medusa/issues/3888

### CODE REVIEW

**Comment by sharkykh** [comment]
Can you check the `/errorlogs/` route? Seems broken to me as well

**Comment by sharkykh** [comment]
same for `/addRecommended/`

**Comment by sharkykh** [comment]
Also found this is broken (at least those two lines):
https://github.com/pymedusa/Medusa/pull/3884/files#diff-c05bb2c59f6b274b8c5134313046b898R51

Error is:
```
SyntaxException: (SyntaxError) EOL while scanning string literal (<unknown>, line 1) (u'\'realpage + \'/\'}?traktList=${traktList}#tabs-1">Ma') in file 'C:/Medusa/themes/light/templates/addShows_trendingShows.mako' at line: 51 char: 75
```

**Comment by sharkykh** [comment]
I have a show with a double quotation mark in its name - `תאג"ד`, since the last PR it broke some stuff:

Shows list:
before

after


Show page:
before
chrome_2018-03-22_01-49-56
after
chrome_2018-03-22_01-50-17

**Comment by sharkykh** [comment]
Not sure if related to my last comment - recent shows links are broken for me:
I get the link - `https://localhost:8081/home/displayShow?indexername=indexer-to-name&seriesid=316913`.
This seems to be unintended?
https://github.com/pymedusa/Medusa/blob/1d62c9064c260d003cc825f069b980c85c5837ce/themes/light/templates/partials/header.mako#L36

**Comment by OmgImAlexis** [comment]
@sharkykh that should be everything fixed. Can you please review.

**Comment by sharkykh** [comment]
Still seeing an error in `addShows_recommended.mako` (lines 51-52) and the character escape issue in `partials/showheader.mako`.
Apart from that and the recent shows, LGTM.

**Comment by sharkykh** [comment]
By the way, it seems like the `indexer-to-name` stuff is injected using JS.
But it's late here, so I might be wrong.

**Comment by OmgImAlexis** [comment]
@sharkykh recent should be fine now.

@p0psicles I've removed your `data-indexer-to-name` function and moved the relevant code to the `app-link` so you can now just pass a `indexer-id` to `app-link` and it'll replace the placeholder with the correct value.

I also added placeholder as a prop so you can change the placeholder as it defaults to `indexer-to-name`.

**Pull request merged**
