### PR TITLE
app-link: Fix undefined url with empty anonRedirect

### LINKED ISSUE #3359: Empty "Anonymous redirect" results in broken links in add show
Branch: master                
Commit: b96b3ee10760ffa03a15a207841a1a2bc65798dd                 
Version: v0.1.19                 
Database: 44.8
Python Version: | 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
SSL Version: | OpenSSL 1.0.2j  26 Sep 2016
OS: | Windows-10-10.0.14393
Locale: | nl_NL.cp1252

When no link is used in Anonymous redirect this will result in a broken link in the add show page all other pages seem to work fine.
image

image
The links point to:
- undefinedhttp://thetvdb.com/?tab=series&id=321239&lid=7
- undefinedhttp://www.tvmaze.com/shows/16579
- undefinedhttps://www.themoviedb.org/tv/69478

### PR DESCRIPTION
**Pull request by sharkykh**
Tested, works for me.
Fixes #3359 

@OmgImAlexis If you have any more fixes queued up for `app-link` maybe we should combine them into one PR.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
The one problem I have with this is it could leak users if they somehow are missing the field? Maybe we need a disable option?

**Comment by sharkykh** [comment]
@OmgImAlexis If they're missing the field, they're probably missing the config, If they're missing the config, what good would a disable option do? :thinking:

**Comment by OmgImAlexis** [comment]
If they disable it using a checkbox we know they don't want to use a anon redirect otherwise they could be missing the field because they pressed backspace, etc.

**Comment by p0psicles** [comment]
This can be merged?

**Pull request merged**
