### PR TITLE
Fix history size comparison and add size to downloaded status

### PR DESCRIPTION
**Pull request by fernandog**
@medariox please test when you can

### CODE REVIEW

**Comment by medariox** [comment]
Have this running locally now and row highlight seems to work again.

Column is still ugly:
_Too small:_
image
_Missing border:_
image

I will leave this running tonight, so we can see if the missing size is also still an issue.

**Comment by fernandog** [comment]
@medariox ok. 

about the "ugly". it depends on the release name size. If is too long, it will need more space.

**Comment by medariox** [comment]
If you look at the whole table, you can see that "size" has completely unproportional borders:
image

And there is still the missing bottom border.

**Comment by fernandog** [comment]
@medariox i only added column. just like the others

maybe @Thraxis can help understand why

**Pull request merged**
