### PR TITLE
Fix TypeError when updates_api returns None. Fixes #2424

### LINKED ISSUE #2424: [APP SUBMITTED]: TypeError: 'NoneType' object is not iterable
### INFO
**Python Version**: `2.7.9 (default, Sep 17 2016, 20:26:04) [GCC 4.9.2]`
**Operating System**: `Linux-4.4.38-v7+-armv7l-with-debian-8.0`
**Locale**: `UTF-8`
**Branch**: [develop](../tree/develop)
**Database**: `44.5`
**Commit**: pymedusa/Medusa@a70a6df42ec915a51409a059df3a58f56c1b2bd7
**Link to Log**: https://gist.github.com/839dc72eb02a30a96952cd7150164207
### ERROR
<pre>
2017-03-17 02:01:22 ERROR    SHOWUPDATER :: [a70a6df] Problem running show_updater, Indexer TVDBv2 seems to be having issues while trying to get updates for show Hannibal. Cause: 'NoneType' object is not iterable.
Traceback (most recent call last):
  File "/home/pi/Medusa/<a href="../blob/a70a6df42ec915a51409a059df3a58f56c1b2bd7/medusa/show_updater.py#L86">medusa/show_updater.py</a>", line 86, in run
    update_max_weeks)
  File "/home/pi/Medusa/<a href="../blob/a70a6df42ec915a51409a059df3a58f56c1b2bd7/medusa/indexers/tvdbv2/tvdbv2_api.py#L565">medusa/indexers/tvdbv2/tvdbv2_api.py</a>", line 565, in get_last_updated_series
    last_update_ts = max(x.last_updated for x in updates)
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

### PR DESCRIPTION
**Pull request by medariox**
As discussed in https://github.com/pymedusa/Medusa/issues/2424

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@medariox if updates is None, should we count +1?

**Comment by medariox** [comment]
To my understanding, yes - I'm sure @p0psicles knows better.

**Comment by fernandog** [comment]
Checking the code what I understood is that we only update count when we get results from API

If we are getting a None is because response from API is None. So we shouldnt increment count

```python
    def updated_query_get(self, from_time, **kwargs):
        """
        Returns an array of series that have changed in a maximum of one week blocks since the provided `fromTime`.\n\n\nThe user may specify a `toTime` to grab results for less than a week. Any timespan larger than a week will be reduced down to one week automatically.
```

**Comment by fernandog** [comment]
@medariox notice that it returns the response:


```python
        response = self.api_client.call_api(resource_path, method,
                                            path_params,
                                            query_params,
                                            header_params,
                                            body=body_params,
                                            post_params=form_params,
                                            files=files,
                                            response_type='UpdateData',
                                            auth_settings=auth_settings,
                                            callback=params.get('callback'))
        return response
```

**Comment by medariox** [comment]
It doesn't really matter, as the while stops anyway - I would still count it, as it can causes an endless loop otherwise. I think we should raise something like ```ApiException```.

**Pull request merged**
