### PR TITLE
Update yggtorrent.py

### PR DESCRIPTION
**Pull request by Silvers12**
Update de la nouvelle URL

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by medariox — APPROVED** [review]

**Comment by medariox** [comment]
Please open against develop branch.

**Comment by baya44** [comment]
Hello!
There is a new adress for this provider (yggtorrent.li)
Can you update it?

**Comment by medariox** [comment]
@baya44 
They block us with Cloudflare v2 protection. There is no point in updating the URL, we already handle the redirects.

**Comment by baya44** [comment]
I know, but some times they shutdown their protection ^^

**Comment by medariox** [comment]
@baya44 
If/when that happens it will work with the URL we have set now, as it still redirects correctly.

**Pull request closed without merging**
