### PR TITLE
Adding some missing tv network logos

### PR DESCRIPTION
**Pull request by akosasante**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

I followed the instructions in the Medusa wiki page here regarding formatting and naming: https://github.com/pymedusa/Medusa/wiki/Network-logos#how-to-add-network-logos-for-medusa

One question, the example in there indicates using spaces in the logo filenames (eg: `sky atlantic`) but I notice a bunch of the logos in this folder are using snake-case; is there a preferred naming convention?

Networks added:
* alibi
* all 4 tv (channel4's on-demand service)
* amazon freevee
* amc premiere
* BET+
* britbox
* cmore tv
* cbc gem
* channel 13 (israel)
* crave
* dr ramasjang
* epix.com (**NOTE:** I wasn't sure if the naming convention would be able parse the `.com` here ? )
* france tv slash
* hbo go
* hot tv (also known as hot3)
* itvx
* m-net
* sky max
* stoo2 tv (iceland)
* sundance tv
* tencent video
* the roku channel
* yahoo! view (also known as yahoo! screen)
* yle

### CODE REVIEW

**Comment by akosasante** [comment]
Hmm, not sure why the gulp task is failing; it worked fine locally 🤔 The action doesn't seem to print much of useful error log. Not sure about API test either; that's not anything I touched.

**Comment by p0psicles** [comment]
For all the images where there are spaces in the names you'll need to replace those with a dash `-`. For example `amazon freevee.png`  should be `amazon-freevee.png`.

After that you'll need to run a:
`yarn install`
`gulp sync`
and `yarn dev`

**Comment by akosasante** [comment]
Sounds good @p0psicles thanks! Could the wiki page also be updated to clarify how to add new Network images (regarding spaces / any other invalid characters; and regarding generating the dark/light theme assets before committing) ? I don't think I have access to make edits to this page currently: https://github.com/pymedusa/Medusa/wiki/Network-logos#how-to-add-network-logos-for-medusa

**Comment by p0psicles** [comment]
I'll give you edit rights.
You still have added the icons with the space in them.

**Comment by p0psicles** [comment]
Tnx for the contribution!

**Pull request merged**
