### PR TITLE
Vueify log viewer (and use Backstretch)

### PR DESCRIPTION
**Pull request by sharkykh**
Supersedes #4104

**It's basically done!**
Looks like I just need to fix the tests.
_Edit:_ Also push [the fix for this bug](https://i.imgur.com/tP21MW2.jpg).

- I added log polling (updates the page every 1.5 seconds), with a button to pause the refreshing.
- Backstretch component was not being used, fixed it and hopefully got it going with a temporary API variable for a random show slug. It should ultimately be from the list of shows in the store, but they're really available right now.

### CODE REVIEW

**Comment by sharkykh** [comment]
Retry Deepcode

**Comment by sharkykh** [comment]
image
Need to fix that (when selecting `Thread` as filter)

**Comment by p0psicles** [comment]
nice PR!

**Comment by sharkykh** [comment]
Many thanks

**Pull request merged**
