### PR TITLE
Optimize docker build pipeline

### PR DESCRIPTION
**Pull request by reconman**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

I've replaced some manual actions with predefined Github actions and combined both workflow files.

I've tested the changes in the master and develop branches of my fork, although I modified it a bit so I'm pushing to the Github docker registry instead of Dockerhub.

### CODE REVIEW

**Comment by reconman** [comment]
Proof of it working:
proof

**Comment by p0psicles** [comment]
Does it also successfully build all architectures?

**Comment by reconman** [comment]
Yes, see https://github.com/reconman/Medusa/pkgs/container/medusa, tab OS / Arch.

I mostly copy-pasted what I had in another repo where I've been using a similar pipeline for half a year now.

**Comment by p0psicles** [comment]
Nice. I'll look more into it tomorrow.

**Comment by p0psicles** [comment]
@reconman it should also show the branch in docker containers now.
So nice work!

**Comment by reconman** [comment]
Nope, still broken since there are 2 variables being used as reported in https://github.com/pymedusa/Medusa/issues/9532

I'm working on a fix right now.

**Pull request merged**
