### PR TITLE
Perfect match for subtitles is too strict

### PR DESCRIPTION
**Pull request by Thilas**
Change perfect match in order to make it less strict as discussed in #5729.

### CODE REVIEW

**Comment by Thilas** [comment]
@medariox, could you review this PR?

**Comment by medariox** [comment]
Thanks for the PR!
The problem with this is that some providers like `LegendasTV` group the release groups together, like: img
I understand your reasoning behind this, but it will cause a lot of users that use `LegandasTV` to complain about subs not being downloaded. Maybe there is some other way to do this e.g. using the language instead of release group?

**Comment by Thilas** [comment]
I'm confused: I only changed the perfect match option to make it less strict. I mean that with the current perfect match, from what I understand, it already didn't download subtitles in such cases like the one you mention for `LegendasTV`. And I guess it also wouldn't with my change. So the only way for users is to use non-perfect match here, which I didn't change. Am I wrong?

**Comment by medariox** [comment]
Maybe it was there other way around, lowering the score makes it download wrong subtitles even with perfect match? Oh well, I would say we try it out and see how it turns out.

**Comment by medariox** [comment]
@Thilas
Can you update the changelog please? I would add this to improvements.

**Comment by Thilas** [comment]
@medariox, @p0psicles, here is the changelog.

**Pull request merged**
