### PR TITLE
Feature/indexers refactor

### PR DESCRIPTION
**Pull request by labrys**
Refactor indexers
merge after #3558

### CODE REVIEW

**Comment by p0psicles** [comment]
Nice PR. Change was needed. Merge from develop, fix conflicts and fix flake, then it's fine with me.

**Comment by labrys** [comment]
Open it in a new PR.  I don't want notifications for this.

**Comment by fernandog** [comment]
You can "unsubscribe". There is a button for it

**Comment by labrys** [comment]
Unsubscribe does not remove it from my open pull requests.

**Comment by p0psicles** [comment]
No problem, I'll open a new one

**Pull request closed without merging**
