### PR TITLE
Expected titles should be cached against show names and scene exception names

### PR DESCRIPTION
**Pull request by ratoaq2**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)
- [x] Adding proper key generator function that takes into account names and exception names for each tv show

### CODE REVIEW

**Comment by duramato** [comment]
Commit: c7cab9a4448ac5a9d550bb193d83a9325c9896a4`
```
2016-10-27 22:55:16 DEBUG    POSTPROCESSOR :: [c7cab9a] Processing folder 17 mgnovenij vesni(Shtirlits)
2016-10-27 22:55:19 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.01.of.12.(Rus).avi to a show in your database. Parser result: episode: [1, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:20 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.02.of.12.(Rus).avi to a show in your database. Parser result: episode: [2, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:22 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.03.of.12.(Rus).avi to a show in your database. Parser result: episode: [3, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:24 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.04.of.12.(Rus).avi to a show in your database. Parser result: episode: [4, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:26 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.05.of.12.(Rus).avi to a show in your database. Parser result: episode: [5, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:28 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.06.of.12.(Rus).avi to a show in your database. Parser result: episode: [6, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:30 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.07.of.12.(Rus).avi to a show in your database. Parser result: episode: [7, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:32 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.08.of.12.(Rus).avi to a show in your database. Parser result: episode: [8, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:34 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.09.of.12.(Rus).avi to a show in your database. Parser result: episode: [9, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:36 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.10.of.12.(Rus).avi to a show in your database. Parser result: episode: [10, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:38 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.11.of.12.(Rus).avi to a show in your database. Parser result: episode: [11, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:40 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17.Mgnovenij.vesni.12.of.12.(Rus).avi to a show in your database. Parser result: episode: [12, 17], title: Mgnovenij vesni, episode_count: 12, language: ru, container: avi, mimetype: video/x-msvideo, type: episode, absolute_episode: [], quality: Unknown, season: None
2016-10-27 22:55:42 DEBUG    POSTPROCESSOR :: [c7cab9a] Unable to match 17 mgnovenij vesni(Shtirlits) to a show in your database. Parser result: episode: [], absolute_episode: [17], title: mgnovenij vesni, release_group: Shtirlits, type: episode, quality: Unknown, season: None
```

**Comment by fernandog** [comment]
is it working? can be merged?

**Comment by ratoaq2** [comment]
Marking this as an enhancement and leaving the bug still open. This enhancement is needed anyway. Bug to be fixed in another opportunity.

**Comment by fernandog** [comment]
approved

**Pull request merged**
