### PR TITLE
Adding pyOpenSSL 16.2.0 as to fix pyOpenSSL 0.14-1 bug

### LINKED ISSUE #1385: Error: cafile must be None or a byte string - new issue
### Before submitting your issue:

Enable debug logging in Medusa settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: b6a8bc7cabd9c42a38ac7b993a841cc0cfc6d1cb
OS: Debian Linux (FeralHosting Seedbox)
What you did: Rebuilt Medusa from scratch.
What happened: Looks like more SSL related errors?
What you expected: For it to work, without timezone issues. Also, can't search providers with these issues.
Logs:
````
2016-10-30 01:56:41 INFO     CHECKVERSION :: [b6a8bc7] Unknown exception in url https://cdn.pymedusa.com/news/news.md. Error: cafile must be None or a byte string
2016-10-30 01:56:40 INFO     CHECKVERSION :: [b6a8bc7] Checking for updates using GIT
2016-10-30 01:56:40 WARNING  MAIN :: [b6a8bc7] Updating network timezones failed, this can happen from time to time. URL: https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt
2016-10-30 01:56:40 INFO     MAIN :: [b6a8bc7] Unknown exception in url https://cdn.pymedusa.com/sb_network_timezones/network_timezones.txt. Error: cafile must be None or a byte string
2016-10-30 01:56:39 INFO     TORNADO :: [b6a8bc7] Starting Medusa on http://0.0.0.0:30334/
```

### PR DESCRIPTION
**Pull request by ratoaq2**
# PR is based on the MASTER branch

This is a hotfix to master. Added pyOpenSSL 16.1.0 in order to fix infamous 0.14-1 bug.
It needs confirmation that it actually works. And it also needs to be tested on other systems.

This should fix #1385

@whipcracker Are you able to test this branch and report back if that fixed your issue?

### CODE REVIEW

**Comment by fernandog** [comment]
@ratoaq2 I cherry-picked and got this in config page: ` SSL Version:	OpenSSL 1.0.1t 3 May 2016` is that right?

**Comment by fernandog** [comment]
without this commit i also have: `SSL Version:	OpenSSL 1.0.1t 3 May 2016`

**Comment by whipcracker** [comment]
Sorry for the noob answer, but what exactly do you want me to do? Happy to help and all, though. 

You want me to try develop branch and do a git pull and see how I go? 

I'm on the east coast of Australia, so it's gone 11pm and first day back at work tomorrow after some weeks of annual leave, so I'll take a look tomorrow morning for you lot if that's ok :) 

Cheers lads!

**Comment by fernandog** [comment]
@whipcracker run inside Medusa folder:

git fetch origin & git cherry-pick 6817c1ffdf8e4dabb8c9c8e429f9836f932bfa9c

**Comment by whipcracker** [comment]
Sounds great, thanks for the reply, but I'm totally shagged, so I'll have a look at it tomorrow morning, sorry for the inconvenience :( It's 11:15pm here and our 4 month old baby wears us out lol... If I'm up later for whatever reason, I'll have a crack then. Cheers!

**Comment by fernandog** [comment]
@whipcracker np! i know what is like! no rush

**Comment by whipcracker** [comment]
Confirming I now have an issue where IPTorrents and TVChaosUK aren't finding episodes anymore, but TorrentDay working fine.

2016-10-31 02:08:00 INFO     SEARCHQUEUE-MANUAL-83127 :: [TvChaosUK] :: [6d8991b] Performing episode search for Strictly Come Dancing
2016-10-31 02:08:00 INFO     SEARCHQUEUE-MANUAL-83127 :: [TorrentDay] :: [6d8991b] Performing episode search for Strictly Come Dancing
2016-10-31 02:08:00 INFO     SEARCHQUEUE-MANUAL-83127 :: [IPTorrents] :: [6d8991b] Performing episode search for Strictly Come Dancing
2016-10-31 02:08:00 INFO     SEARCHQUEUE-MANUAL-83127 :: [6d8991b] Using manual search providers
2016-10-31 02:08:00 INFO     SEARCHQUEUE-MANUAL-83127 :: [6d8991b] Beginning manual search for: [Strictly Come Dancing - S14E11 - Week 5 Results]
2016-10-31 02:07:45 INFO     SEARCHQUEUE-MANUAL-83127 :: [TvChaosUK] :: [6d8991b] Performing episode search for Strictly Come Dancing
2016-10-31 02:07:45 INFO     SEARCHQUEUE-MANUAL-83127 :: [TorrentDay] :: [6d8991b] Performing episode search for Strictly Come Dancing
2016-10-31 02:07:45 INFO     SEARCHQUEUE-MANUAL-83127 :: [IPTorrents] :: [6d8991b] Performing episode search for Strictly Come Dancing
2016-10-31 02:07:45 INFO     SEARCHQUEUE-MANUAL-83127 :: [6d8991b] Using manual search providers
2016-10-31 02:07:45 INFO     SEARCHQUEUE-MANUAL-83127 :: [6d8991b] Beginning manual search for: [Strictly Come Dancing - S14E11 - Week 5 Results]

**Comment by fernandog** [comment]
@whipcracker ok but the cafile is gone right?

**Comment by whipcracker** [comment]
Yeah mate, she's gone. V16 seems to have done the trick. 

Any idea about searching IPT or TVChaosUK?

**Comment by fernandog** [comment]
No idea. Dont have this providers

**Comment by whipcracker** [comment]
Should I create another issue instead of discussing it here?

**Comment by fernandog** [comment]
Yes. Move comments to issue and delete from here please

**Comment by whipcracker** [comment]
Issue can be closed now and merged into Master if needed... unsure how it'll impact other OSes, though.

**Pull request merged**
