### PR TITLE
HotFix T411 url

### PR DESCRIPTION
**Pull request by labrys**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
@fernandog I need to know. Is this provider working or not with the new url? We should not merge in hotfixes if it's not working at all.

**Comment by fernandog** [comment]
API is down. No ETA.

don't need to hotfix as i said twice that both domains works.

**Comment by IDerr** [comment]
Both domains works, but the .li will be down in a near future.

**Comment by IDerr** [comment]
Why close this PR ? Labrys is right. .ai is the new domain for t411. The .li will be dropped soon.

**Comment by labrys** [comment]
@IDerr because `.ai` is already in dev which is being prepped for release, thus the hotfix won't be necessary for the master branch.

**Comment by IDerr** [comment]
ok sir, thanks

**Pull request closed without merging**
