### PR TITLE
Feature configure per show daily search airdate offset

### PR DESCRIPTION
**Pull request by p0psicles**
…ate offset.

* Implemented check in dailsearch for searching episodes early.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### TODO:
- [x] add api spec
- [x] update changelog
- [x] add field to tv_shows db
- [x] add field to series class
- [x] add logic to dailsearch, for searching earlier
- [x] add logic to dailysearch, for search later
- [x] add UI control to editShow
- [ ] ~~add UI control to providers~~
- [x] add UI indicator to displayShow/snatchSelection header
- [x] Test by users

implement feature #3679 

### Update:
I've scratched the feature to enable/disable the feature per provider. As for that I need to make structural changes throughout medusa's code. And i'm not going to do that now.

### CODE REVIEW

**Comment by rafi-d** [comment]
I've tested this with both per-search (negative offsets) and post-search (positive offsets), and everything seems to work OK!

Still, this offset needs to  be visible on the show page, as well as the manual search page - in the top/header - show-info part, at least in cases it is *not* 0.

Thanks!

Rafi

https://github.com/pymedusa/Medusa/issues/3679#issuecomment-446289920

**Comment by rafi-d** [comment]
...a small typo in series.py - 

# The offset in **ours**, for when we want to start searching episodes for this show. -1 is search 1 hour early. 1, 1 hour later.

**Comment by p0psicles** [comment]
> ... one small typo in series.py -
tnx, will correct

> Also, be aware that once the early offset-time arrives, the status for a specific episode (changed to "wanted" when the offset time arrives) is not/cannot be reverted back to "unaired" even if the user corrects this offset, or sets it to 0 again. No a big deal I believe...

Yes I'm aware. Also, if the backlog search is triggered. It will also search for these early episodes if they're already set to wanted by the daily search.

**Comment by rafi-d** [comment]
This feature (dealing with offsets/time-limits) reminds  of another desired feature - an autofiles size filter (min/max). Actually I have it working here locally great (tho, w/o changing anything in the DB yet). So, since you are changing the DB for this feature, it might be a good point in time to consider adding two more edit-boxes for this file-size feature if you are interested ... :)

**Comment by p0psicles** [comment]
> it might be a good point in time to consider adding two more edit-boxes for this file-size feature if you are interested ... :)

No i'm not interested. I already got like 6 other PR's on my backlog to finish. I did this one cause it's rather easy to implement.

**Comment by rafi-d** [comment]
Sure, no problem. Works for me... 
For this feature here, I think you still need to add some "external" visibility for users .

**Comment by medariox** [comment]
@rafi-d 
We are aware of it. Once the PR is done we will label it as **concluded**.

**Comment by rafi-d** [comment]
@medariox 
What I meant, was have the offset ( if set ) *visible* on the show's page among the other show's details, so not to make it more clear why the status shows  as "wanted"  earlier or late relative to the air-time...

**Comment by p0psicles** [comment]
Yes i updated the todo checklist of this pr.

**Comment by rafi-d** [comment]
Ok, Thanks. Actually these two are pretty much done IMHO... 👍 
v add logic to dailysearch, for search later
v Test by users

One more thing to consider - one might see a strange show list like the attached (after a show has been snatched early, sorted by 'Next Ep', where future date(s) show in the 'Prev Ep' column). So, maybe adding another possible column - for "offset" can be helpful here?

**Comment by rafi-d** [comment]
I have been testing this for the last couple of weeks, and results are very good, but there is this one symptom which I've noticed, and not sure if it is related or not:
After an episode has been downloaded, say, -24 hours ahead of time as designed, I  sometimes see an extra/second double download of the same episode for that same  show with -24 offset, with a "Proper" notation, and it seems to occur after the original airtime. It also does not delete the previous downloaded episode (by uTorrent). 
Is this something that can be expected? or maybe needs to be tweaked with regards to this new setting?

**Comment by p0psicles** [comment]
Sounds like a "proper" was released after. But that should replace the original?

**Comment by rafi-d** [comment]
Yes, I guess it was released later on. And yes, if you decided to download same release twice, it should have deleted the first one. Honestly, I have never seen this happen. 

Also, be aware that delete cleanly,  is not that easy, since you have to remove it from the client (WebAPI to  uTorrent) as well. So, in the worse case, when the client is still seeding it, you'd also need to stop it first.

**Comment by p0psicles** [comment]
Okay but that doesn't sound as anything related to this pr. More something with your post-processing setup.

**Comment by rafi-d** [comment]
>that doesn't sound as anything related to this pr

If so, let's forget  it for now over here.

BTW,  I do not have any post processing set, and didn't know that deleting of double download  episodes even requires post-processing. I thought if it  does an extra download, it should just clean/erase the previous one ....

I hope you release this feature soon, I am already one version behind...  :)

**Comment by p0psicles** [comment]
I'll merge develop into it.

**Comment by rafi-d** [comment]
maybe you can add minimal UI for it, so to make this easier to use/test?...

**Comment by rafi-d** [comment]
Got it. Looks good, thanks. I guess it is ready for release...

**Comment by p0psicles** [comment]
Yeah, just needs to get review

**Pull request merged**
