### PR TITLE
Update logging style

### PR DESCRIPTION
**Pull request by labrys**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by medariox** [comment]
Can we keep this in develop until release?

**Comment by labrys** [comment]
Sure

**Comment by medariox** [comment]
Replaced by https://github.com/pymedusa/Medusa/pull/2809 because of Travis issues.

**Comment by labrys** [comment]
@medariox FYI you can click on the travis that is failing and restart it to fix these kinds of things.

**Pull request closed without merging**
