### PR TITLE
Update adba to medusa-1.0.0

### PR DESCRIPTION
**Pull request by labrys**
Update adba to [adba-medusa-1.0.0](https://github.com/pymedusa/adba) for py3 compatibility.

### CODE REVIEW

**Comment by Thraxis** [comment]
I just took a quick look through...  Why was the downloading of the updated ScudLee XML files removed?

**Comment by labrys** [comment]
@p0psicles unintended.. i just removed the old folder and replaced with the updated lib folder.  I'll add it back but IMO if its not part of the original lib it shouldn't go in the libs folder.

**Comment by labrys** [comment]
Oops meant to tag that @Thraxis

**Comment by p0psicles** [comment]
Ideally no your right, we shouldn't place monkey patched libs in the lib folder. But if we remove adba, then there are at least another dozen which should be moved to where??

**Comment by fernandog** [comment]
i think we should use this PR and fix the https://github.com/pymedusa/Medusa/issues/1729#issuecomment-283417088 as @medariox said

**Comment by medariox** [comment]
@labrys 
What's the status here? Needs review/testing? What about the removed XML files?

**Comment by labrys** [comment]
@medariox Adding the removed XML to medusa and having them loaded i think was the last thing this was waiting on.  I think they should be added external to the lib personally.  Thoughts?

**Comment by p0psicles** [comment]
I think providing a caching location for the xml would be the cleanest solution.

**Comment by medariox** [comment]
@labrys 
Sorry for the late answer, I totally forgot about the mention.
The problem I see here is not much about the missing XML files per se, but rather about the fact that you removed the whole download/update logic of those files. We don't want to be manually updating those every time (they seem to get updates quite often). IMO, since we already forked this lib and changed it quite a bit (and the changes won't be added upstream), we should keep the update mechanism. Possibly not storing the XMLs in the lib folder, but rather in the cache folder like @p0psicles suggested.

**Pull request closed without merging**
