### PR TITLE
Use torrasave.top instead of vr3mrzpy4ugpt2wi.onion.cab

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
are you sure there is no captcha or JS blocking?
we disabled torcache in the past because of JS blocking

**Comment by medariox** [comment]
@fernandog 
Tested and working just fine.

**Comment by duramato** [comment]
Why the http link? No ssl version of the site? Same question goes for the existing ones too

**Comment by medariox** [comment]
@duramato 
torrasave.top has an invalid certificate. Not sure about itorrents. Anyway, in this case the use of TLS is useless as we aren't transmitting any sensitive information.

**Comment by duramato** [comment]
It's always better to use ssl :P

**Pull request merged**
