### PR TITLE
Updated logo in the help&info sprite.

### PR DESCRIPTION
**Pull request by neoatomic**
Could not help myself being the first one sending in a PR. :P

### CODE REVIEW

**Comment by fernandog** [comment]
Look who is still around!

**Comment by neoatomic** [comment]
@fernandog Was about to blade you for all the problems. :P

**Comment by fernandog** [comment]
LOL

**Comment by fernandog** [comment]
@neoatomic your branch is showing as `unknown repository` and we can't rebase because of a travis issue we fixed. Can you make another PR or may create it cherry-picking the commit?

**Pull request closed without merging**
