### PR TITLE
just a small fix to center items for episode selection in the new div.

### PR DESCRIPTION
**Pull request by wimpyrbx**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

image

### CODE REVIEW

**Comment by wimpyrbx** [comment]
fixes issue with space between snatchselection items and showheader. now looks like this:
image

**Comment by wimpyrbx** [comment]
looked like this before.
image

**Comment by medariox** [comment]
I think you reverted your first change?

**Comment by wimpyrbx** [comment]
it seems indeed that i did.. now to figure out how i can fix that!

**Comment by wimpyrbx** [comment]
@medariox i hope that fixed it. never reverted before, but it looks correct now.

**Pull request merged**
