### PR TITLE
Fixing language detection

### PR DESCRIPTION
**Pull request by ratoaq2**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

@NicoLeOca: This should fix the "do not postpone if any embedded sub matches a wanted language"
Shame on @fernandog. I asked him to test before merging the other PR.

### CODE REVIEW

**Comment by NicoLeOca** [comment]
@ratoaq2 
thanks for fixing it

I don't get what you mean here:  "postpone if any embedded sub matches a wanted language"

so you mean that language of embedded subs will be detected and that also if one matches the wanted language, it will be PP?
so then it would be "post process if any embedded sub matches a wanted language" and not postpone?

**Comment by ratoaq2** [comment]
Just edited

**Comment by fernandog** [comment]
@nicoleoca I doesnt read the subtitle data to detect language. It only reads the field "subtitle language" in the mkv

**Comment by ratoaq2** [comment]
Subliminal uses enzyme and tries to parse the language code and track name. A lot of times you don't have the language code, but the track name is English, therefore it defects as English. But several times it also has another track named English (SDH). This one is detected as unknown by subliminal and detected as English + hearing impaired by knowit

**Comment by NicoLeOca** [comment]
@ratoaq2 
I updated to last develop

but this file isn't PPed:
Knowit 0.1.2 found:
{
    "duration": "0:24:40",
    "overall_bit_rate": 5592324,
    "video": [
        {
            "number": 1,
            "language": "English",
            "duration": "0:24:39.980000",
            "size": 942939044,
            "width": 1920,
            "height": 1080,
            "scan_type": "Progressive",
            "aspect_ratio": 1.778,
            "pixel_aspect_ratio": 1.0,
            "resolution": "1080p",
            "frame_rate": 23.976,
            "bit_rate": 5097037,
            "bit_depth": 8,
            "codec": "h264",
            "profile": "High@L4",
            "media_type": "video/H264",
            "default": true
        }
    ],
    "audio": [
        {
            "number": 2,
            "name": "Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG",
            "language": "English",
            "duration": "0:24:40",
            "size": 71040000,
            "codec": "AC3",
            "channels_count": 6,
            "channels": "5.1",
            "bit_rate": 384000,
            "bit_rate_mode": "Constant",
            "sampling_rate": 48000,
            "compression": "Lossy",
            "default": true
        }
    ],
    "subtitle": [
        {
            "number": 3,
            "language": "English",
            "format": "SubRip",
            "encoding": "utf-8",
            "default": true
        }
    ]
}

logs of the PP:
2016-11-06 16:03:47 INFO     Thread-17 :: [cd82439] Not deleting folder /home/nicoleoca/Downloads/AutoDL/Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG found the following files: [u'Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv']
2016-11-06 16:03:47 DEBUG    Thread-17 :: [cd82439] No subtitles associated. Postponing the post-process of this file: Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv
2016-11-06 16:03:47 DEBUG    Thread-17 :: [cd82439] No associated files for /home/nicoleoca/Downloads/AutoDL/Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG/Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv were found during this pass
2016-11-06 16:03:47 DEBUG    Thread-17 :: [cd82439] Using cached parse result for '/home/nicoleoca/Downloads/AutoDL/Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG/Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv'
2016-11-06 16:03:47 DEBUG    Thread-17 :: [cd82439] Parsed 'Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv' into title: Atlanta, season: 1, episode: [4], screen_size: 1080p, format: WEB-DL, audio_codec: DolbyDigital, audio_channels: 5.1, video_codec: h264, release_group: RARBG, container: mkv, mimetype: video/x-matroska, type: episode, absolute_episode: [], quality: 1080p WEB-DL
2016-11-06 16:03:46 DEBUG    Thread-17 :: [cd82439] Processing folder /home/nicoleoca/Downloads/AutoDL/Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG

**Comment by NicoLeOca** [comment]
@ratoaq2 

I just spotted that:
2016-11-06 16:03:47 DEBUG Thread-17 :: [cd82439] Using cached parse result for '/home/nicoleoca/Downloads/AutoDL/Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG/Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv'

as I force a new manual PP with these settings below, it shouldn't use cached results from previous PP, isn't it?
image

**Comment by ratoaq2** [comment]
The cached message is not related to subtitles check.

I can't understand from the logs why it doesn't work.
Are the configuration ok?
- Subtitles enabled for that show
- Not ignoring embedded subs
- English language as "wanted language"

?

**Comment by NicoLeOca** [comment]
I double-checked and it's all good

so subs are checked every time you PP? it doesn't use any cache from a previous PP?
is that what you mean?

**Comment by fernandog** [comment]
@NicoLeOca its working here. I added "English" to my wanted languages and enabled the disabled the "ignore embedded subs"

The second log i added to debug

```
2016-11-06 18:34:35 INFO     Thread-15 :: [154a164] Found embedded subtitles: set([<Language [en]>])
2016-11-06 18:34:35 INFO     Thread-15 :: [154a164] Wanted languages: set([<Language [en]>, <Language [pt-BR]>]). Subtitles: set([<Language [en]>])
2016-11-06 18:34:35 INFO     Thread-15 :: [154a164] Found wanted embedded subtitles. Continuing the post-process of this file: American.Horror.Story.S06E08.1080p.WEB-DL.DD5.1.H264-ViSUM.mkv

```

ping @ratoaq2

**Comment by NicoLeOca** [comment]
@fernandog @ratoaq2 
I think I found the issue
the knowit results I displayed above were tested on my local windows

here is knowit on my distant ubuntu

Both on the same file : Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG.mkv

Knowit 0.1.2 found:
{
    "duration": "0:24:40",
    "video": [
        {
            "number": 1,
            "name": "Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG",
            "width": 1920,
            "height": 1080,
            "scan_type": "Progressive",
            "resolution": "1080p",
            "codec": "h264",
            "default": true
        }
    ],
    "audio": [
        {
            "number": 2,
            "name": "Atlanta.S01E04.1080p.WEB-DL.DD5.1.H264-RARBG",
            "codec": "AC3",
            "channels_count": 6,
            "channels": "5.1",
            "default": true
        }
    ],
    "subtitle": [
        {
            "number": 3,
            "default": true
        }
    ]
}


How come is it different?

**Comment by ratoaq2** [comment]
@Nicoleoca knowit has two providers:
- enzyme (mkv header extraction) and it's a pure python library 
- pymediainfo (support several containers and media types) and it  has a native dependency: https://mediaarea.net/en/MediaInfo

Knowit ships mediainfo for Windows (32 bits and 64 bits) and Mac. But not for Linux, since there are different binaries for each distribution and version. If you get Ubuntu, there should be a different binary for 32 and 64 bits, times the number of versions: 14.04, 14.10, 15.04, 15.10, 16.04, 16.10 = 12 different binaries

In Linux you could install mediainfo (`apt-get install mediainfo`)  and knowit will just works with it. But that's optional. Without MediaInfo knowit should still support mkv out of the box. 

Going back to your issue:
In your windows installation, knowit is using mediainfo to read video metadata and finding the subtitle track correctly. 
In your ubuntu installation, knowit is using enzyme (since mediainfo is not installed)  to read video metadata and the mkv header for that subtitle track doesn't contains the language code. 

I'm upgrading knowit version to always return 'unknown language` when language code is wrong or missing. And it also improves the language detection using the track name as a fallback (like subliminal does) 

That should fix your issue in Linux.

**Comment by ratoaq2** [comment]
Additionally, knowit has a version parameters that can show you its version and each dependency version:

```
knowit --version
```

**Comment by NicoLeOca** [comment]
@ratoaq2 
thanks for helping out
I'll have a look at it later today.

Also, in addition to a better handling of unknown language, could you add a message somewhere to let Linux users know that installing mediainfo would improve the "experience", please?
A better solution would be to have it installed by default, by you said it wasn't possible

**Comment by ratoaq2** [comment]
We added the information on our front page:

https://github.com/pymedusa/Medusa/blob/develop/readme.md

But it will only appear in the next release. 
If you have other ideas, let us know

**Comment by fernandog** [comment]
we can add it to news

**Comment by NicoLeOca** [comment]
@ratoaq2 @fernandog 
I agree with Fernandog, in a news annoncing Knowit
also in the wiki and maybe in the settings, next to subs or language

**Pull request merged**
