### PR TITLE
Use xthor api

### PR DESCRIPTION
**Pull request by xataz**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by labrys** [comment]
@xataz Thanks for the contribution.  I notice you are using SickRge's provider format though.  We have evolved our format here.

For example we split the parsing out of the search function, we use a logging style similar to python standard logging instead of the old sickrage logger, and a few other things.

If you would like to make to compare to one of our existing providers and make the changes, or if you prefer I can create a new PR based on your work and make the changes myself.

If you have any questions at all, please don't hesitate to ask.

**Comment by xataz** [comment]
Hello,

Thanks for your updates. I'm sorry, i'm not a developer, I simply adapted the sickrage code.

Sorry for my bad english ^^

**Comment by p0psicles** [comment]
@xataz you mind doing some tests on it? Running an episode and season search?

**Comment by xataz** [comment]
Hi, 

I try today, it works.
Manual and backlog search it's ok, for episode and season.

Thanks

**Pull request merged**
