### PR TITLE
small cosmetic fix

### PR DESCRIPTION
**Pull request by cheese1**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
You need to build the theme.
Yarn install
Yarn dev

**Comment by medariox** [comment]
https://github.com/pymedusa/Medusa/wiki/Themes

**Comment by cheese1** [comment]
sorry, was not aware that this would break the themes. will take some time as i need to install yarn,...

**Comment by cheese1** [comment]
will create a new one after fixing

**Pull request closed without merging**
