### PR TITLE
The sickbeard index api_key has a value of 0. This results on all '0' being censored.

### LINKED ISSUE #3128: Censoring the number 0
After updating to the latest develop commit, it has started to censor the number `0`
```
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking database structure...main.db2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Initial Schema database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] InitialSchema upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Version To Tv Episodes database upgrade2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddVersionToTvEpisodes upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Default Ep Status To Tv Shows database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddDefaultEpStatusToTvShows upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Alter Shows Field Types database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AlterTVShowsFieldTypes upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Minor Version database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddMinorVersion upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Test Increase Major Version database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] TestIncreaseMajorVersion upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Proper Tags database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddProperTags upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Manual Searched database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddManualSearched upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Info Hash database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddInfoHash upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Plot database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddPlot upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Resource Size database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddResourceSize upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Indexer Mapping database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddPKIndexerMapping upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Indexer Integer database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddIndexerInteger upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking database structure...cache.db
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Initial Schema database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] InitialSchema upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Scene Exceptions database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddSceneExceptions upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Scene Name Cache database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddSceneNameCache upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Network Timezones database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddNetworkTimezones upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Last Search database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddLastSearch upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Scene Exceptions Seasons database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddSceneExceptionsSeasons upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Scene Exceptions Custom database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddSceneExceptionsCustom upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Scene Exceptions Refresh database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddSceneExceptionsRefresh upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Convert Scene Exeptions To Indexer Scheme database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] ConvertSceneExeptionsToIndexerScheme upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Convert Scene Names To Indexer Scheme database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] ConvertSceneNamesToIndexerScheme upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Remove Indexer Update Schema database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] RemoveIndexerUpdateSchema upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Checking Add Indexer Scene Exceptions database upgrade
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] AddIndexerSceneExceptions upgrade not required
2**********17-**********9-21 13:**********2:49 DEBUG    MAIN :: [4**********a598c] Performing a vacuum on the CACHE database
```

https://gist.github.com/duramato/62d1a19d24459ba14f70038ecbb0ba95

### PR DESCRIPTION
**Pull request by p0psicles**
I've introduced a rule that a string needs to have 4 chars at minimum to be censored.

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Should fix #3128

### CODE REVIEW

**Comment by p0psicles** [comment]
@duramato this should fix your bug. Can you verify?
@pymedusa/developers any reasons why we would to censor strings shorter then 4 chars?

**Comment by labrys** [comment]
While I can confirm that this fixes the issue, I think that this fix is too permissive.  A user could potentially have a 3 letter password which would then be exposed.  Since an api key of 0 means no API key required, I think it would be better to just filter for that one specific value.

**Comment by labrys** [comment]
Personally I would go with something like the following:
```python
if privacy_level >= censor_level or (cfg_name, item_name) in iteritems(logger.censored_items):
    if item_name.endswith('custom_url'):
        # Custom URLs should not be censored
        pass
    elif item_name.endswith('api_key') and my_val == '0':
        # API key of '0' means its not required and should not be censored
        pass
    else:
        # Item qualifies for censoring
        logger.censored_items[cfg_name, item_name] = my_val
```

**Comment by p0psicles** [comment]
@labrys I also thought about that. But the reason i'd rather not limit it to the '0'. Is because it doesn't fix the issue when there is a '1' entered or some other single character.

Also you should ask yourself, which user holds any value in a password that's 3 characters long? Why should we censor that? At least that was my toughtprocess in this.

**Comment by labrys** [comment]
As of right now the only specific value that is an issue is 0 due to the API key which my code addresses specifically, since an API key of 0 is not valid since that is our sentinel value for no key required.  A 1 on the other hand (while extremely unlikely) is technically a valid.

Any additional checks if needed in the future for other values can be added as needed.  The censor list is only loaded when the configuration is changed/loaded so having an extended ruleset would not be a performance concern.

Lastly, a password is a password.  Just because a user doesn't choose a secure one doesn't mean that we shouldn't protect it nonetheless.

**Pull request merged**
