### PR TITLE
Fix changing process method in Manual PP

### LINKED ISSUE #10196: Manual Post-Processing unable to change "Process Method to be used".
**Describe the bug**
When I select an option other than the one set in my regular post-processing settings, it will revert to default as soon as I click **any** other button on the screen.

**To Reproduce**
1. Go to 'Shows and Click Manual Post-Processing'
2. Click on 'pull down menu of Process Method to be used'
3. Scroll down to 'any non-default method, in my case I chose Move'
4. Click any of the buttons below, or even process and the selection reverts to system default.  It will not allow me to actually use any alternate method.

**Expected behavior**
Select an alternate post processing method.  In my case change from Copy to Move, and process with my new selection.  
**Screenshots**

**Medusa (please complete the following information):**
 - OS: Linux-3.10.108-x86_64-with
 - Branch: master 
 - Commit: f3f501
 - Python version: 3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 - Database version: 44.18
 - Version: 0.5.22 
 - Docker Container: pymedusa/medusa:master
**Debug logs (at least 50 lines):**
General > Advanced Settings > Enable debug
<details>

```
None available since its more of a gui loss of focus issue
```

**Additional context**
Have tried on various installs using both docker and synology installation via benjv package.  Same problem occurs either way.

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Fix #10196

### CODE REVIEW

**Comment by consenti** [comment]
No change.  I still cannot change PP method.

**Comment by p0psicles** [comment]
Ow that's weird. I was pretty sure I fixed that

**Comment by p0psicles** [comment]
Nope. Working fine here. Set pp method to copy. In manual pp selecting move, works fine. You on latest master / develop. Did you refresh the page?

**Comment by consenti** [comment]
Still not working here.  I'm perplexed.

Medusa Info:	
     Branch: master
     Commit: f35a19da6bc4efcafff8facca6a4d5b9e3f3f501
     Version: 0.5.23
     Database: 44.19
Python Version:	3.7.6 (default, Dec 21 2019, 02:28:04) [GCC 8.3.0]
 SSL Version:	OpenSSL 1.1.1d 10 Sep 2019
 OS:	Linux-3.10.108-x86_64-with

I'm running docker-compose using image from docker.io/pymedusa/medusa:master

**Pull request merged**
