### PR TITLE
will replace placeholder images for missing artwork to match new logo.

### PR DESCRIPTION
**Pull request by wimpyrbx**
also fixes xbmc-notify png file.
removed medusa christmas logo png file.

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by medariox** [comment]
Thanks!

Did you also replace the notification image by chance?
noti

**Comment by labrys** [comment]
I changed it a while back so that the notification image uses the favicon, so yes its already changed.

**Comment by wimpyrbx** [comment]
@labrys forgot that one. done now.

**Comment by labrys** [comment]
@wimpyrbx That isnt the one its using it uses: `var iconUrl = 'images/ico/favicon-120.png';`
Its in `static/js/ajax-notifcations.js`

**Comment by labrys** [comment]
It was originally changed to use a favicon here: https://github.com/pymedusa/Medusa/pull/519

**Comment by wimpyrbx** [comment]
favicon-120.png was also changed in the other logo PR

**Pull request merged**
