### PR TITLE
Fixing issue of no matches showing when only one result available (hebits)

### PR DESCRIPTION
**Pull request by smoresmores**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

When only one result appeared in the search it was not parsing it.
Tiny fix.

### CODE REVIEW

**Comment by p0psicles** [comment]
We use mostly < 2 when the table header is also included in de results.

**Comment by smoresmores** [comment]
Yes, which in this case the header is not included. As I am using regex to find all the results that start with "line" and this doesn't include the header. That's why it didn't work when only one result was found, because the size of the list is one and it worked as there are no results at all.
Now this should work fine though.

**Comment by myakove** [comment]
Works for me with this fix.

**Comment by medariox** [comment]
@smoresmores 
Can you rebase the PR please?

**Comment by p0psicles** [comment]
Meaning can you merge develop into this branch pls.

**Comment by smoresmores** [comment]
Sorry for the delay.
Hope it's fine now.

**Pull request merged**
