### PR TITLE
Snooze instead of sleep

### PR DESCRIPTION
**Pull request by labrys**
Use non-blocking `tornado.gen.sleep` instead of `time.sleep`.

### CODE REVIEW

**Comment by p0psicles** [comment]
http://www.tornadoweb.org/en/stable/_modules/tornado/gen.html# sleep. I doubt this will be useful  like this. Reading docs it should be used in coroutines yielding a result.

But you probably have more experience using async then I do. 

```
Note that calling this function on its own does nothing; you must wait on the Future it returns (usually by yielding it).
```

**Comment by labrys** [comment]
Supposedly in threads its supposed to sleep the current thread.  This is just a test to see how it works.

**Comment by p0psicles** [comment]
I think the sleep command tells the event scheduler to wait an additional amount of time before it provides time to the coroutine again. That's why its tightly bound to coroutines.

**Comment by labrys** [comment]
Coroutines do nothing on their own.  A coroutine must be driven.  Without something driving the coroutine it just returns a coroutine object (or in this specific case a future).  Coroutines can drive other coroutines, otherwise you have to drive them yourself (e.g. with a loop).

**Comment by p0psicles** [comment]
Well with a coroutine I mean a driven coroutine.

**Pull request closed without merging**
