### PR TITLE
Fix parse result removing episodes if they are like absolute episodes

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

No idea why this was like this. Fixes https://github.com/pymedusa/Medusa/issues/7575
Also fixes https://github.com/pymedusa/Medusa/issues/7576

### CODE REVIEW

**Comment by p0psicles** [comment]
I don't know. This breaks some of the unit tests. So that's kind of a red flag

**Comment by medariox** [comment]
> Where these `if` `then` blocks purpose less before?

Yeah, they were just for logging 😕

**Comment by p0psicles** [comment]
That definitely wasn't the case at first

**Comment by medariox** [comment]
@p0psicles 
Should be all good now. The main issue was that we didn't account the fact that our guessit parses anime shows with season in the name correctly now (without the season). That needed a little change in the method. The tests also pass without any change.

**Comment by skarekrow** [comment]
Didn't see this in the 0.3.10 release notes, but this is included I believe?

**Comment by medariox** [comment]
Yes, it is.

**Pull request merged**
