### PR TITLE
Don't let add show when no default root folder

### PR DESCRIPTION
**Pull request by fernandog**
Also fix notification message

Fixes https://github.com/pymedusa/Medusa/issues/2214

### CODE REVIEW

**Comment by Thraxis** [comment]
Why are you blocking access to those sections.  The Add New Show and Add existing show pages both already require you to set a show path before you can submit to add the new show.

The add recommended pages have a section that could be used to set path, what is needed is the trigger to disable / enable the buttons on the recommended page when a defaut root dir is not available

**Comment by fernandog** [comment]
No default root folder set as issue says

**Comment by fernandog** [comment]
Anyway its an idea. Ofc can change

**Comment by Thraxis** [comment]
See https://github.com/pymedusa/Medusa/pull/2305

**Comment by fernandog** [comment]
@Thraxis closing this

**Pull request closed without merging**
