### PR TITLE
Feature/fix newznab cats

### PR DESCRIPTION
**Pull request by p0psicles**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@xo we should really fix this issues in API v2 tests.

Sometimes it works and sometimes it doesn't.
I restarted a lot of times and is still not passing

**Comment by fernandog** [comment]
error: POST /api/v2/series/tvdb301824/operation duration: 3ms
error: Error connecting to server under test!

**Comment by OmgImAlexis** [comment]
This is what I needed @ratoaq2 for but he's super busy. I have a feeling we may need to just increase the timeout for dredd before it starts testing.

**Comment by fernandog** [comment]
@xo What about this one?

info: Hooks handler stderr: /home/travis/build/pymedusa/Medusa/dredd/dredd_hook.py:2: RuntimeWarning: Parent module 'dredd_hook' not found while handling absolute import
  import ConfigParser

**Pull request merged**
