### PR TITLE
Feature/vueify display show rebased

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### checklist
- [x] include show header component
- [x] Display season theads
- [x] Display episodes
- [x] include subtitle flags
- [x] use localized date format for date/times
- [x] fix the status overview checkbox buttons
- [x] fix `change status to` button
- [x] fix `change quality to` button
- [x] implement 'select columns' feature
- [x] implement season summary row. for ex. `Season contains 6 episodes with total filesize: 9.06 GB`
- [x] fix dark / light template
- [x] implement download column
- [x] implement links to forced search, manual search
- [x] implement modal to ask for failed search, when clicking forced search button
- [x] implement subtitle search auto + manual 
- [x] implement 'jump to season' feature
- [x] fix with / without fanart background option
- [x] remove `show all seasons` option
~~- [ ] implement `fuzzy dates` option~~ only applies to snatchSelection
- [x] allow option to disable farnart
- [x] CSS bug ignored blue text
- [x] fix pagination div on smaller displays
- [x] add config options for enabling/disabling pagination. And page length.
- [x] for the snatch-selection release-name coloring. Take notice of the exclude ignored/required words.
- [x] fix the display specials toggle button.
- [x] fix builds

### I've created a set of smaller PR's to offload this one. Merged in this order:
- [x] Add custom vue-good-table component to package.json #6726
- [x] update package.json separate deps and dev-deps #6758
- [x] Add queuetime and starttime to the generic_queue.py #6717 
- [x] Introduce the apiv2 search route #6716
- [x] Replace FailedSearchQueueItem with BacklogSearchQueueItem #6718
- [x] Add subtitle search Vue SFC  #6727 

This will be the (reased) base PR/branch. For the coming weeks i'll start creating smaller PR's, and try to reduce this PR in size where possible.
continued from #6315 

Tnx. @sharkykh

### CODE REVIEW

**Comment by p0psicles** [comment]
@medariox I need to add jQuery + qtip2 to jest. Or we choose to use a Vue replacement?

**Comment by medariox** [comment]
Vue would be nice, but I don't know how much work it would be.

**Comment by p0psicles** [comment]
@medariox Not much work. I've added it.
Only a small issue with the color of the arrow. I reflicated the default styling of qtip.
image

**Comment by p0psicles** [comment]
@medariox i'm kinda getting into the final stage of this pr. How do we proceed with this?
It could use some more heavy testing.

**Comment by medariox** [comment]
A few things I've noticed so far:
1. Air date does not sort correctly: https://snapr.pw/i/caf7de2e19.png
2. Subtitle flags are not centered: https://snapr.pw/i/ec0e8fd6e0.png
3. Clicking on the subtitle flag brings up a page that doesn't exist.
4. Changing status/quality individually brings up a warning.

**Pull request merged**
