### PR TITLE
Change displayShow invalid Timeformat message

### PR DESCRIPTION
**Pull request by fernandog**
Related:

pasted image at 2016_11_04 13_51

### CODE REVIEW

**Comment by p0psicles** [comment]
is this still an issue? thought I resolved that?

**Comment by fernandog** [comment]
If airs = '' the convertion will still fail in mako

**Comment by ratoaq2** [comment]
So, it's only empty that needs to be handled, right? The new message is not the best one. Probably we should only leave the ui field empty

**Comment by fernandog** [comment]
But if format is wrong users should know and edit info in tvdb

**Comment by p0psicles** [comment]
no because in mako '' == false.
It will just not display anything.

So if airs is '' and network is '', it will show nothing.

**Comment by fernandog** [comment]
Beetle Bailey
Chuck Norris: Karate Kommandos
Fanthomas <- this is a norwegian web series so not really a network noted on thetvdb

**Pull request closed without merging**
