### PR TITLE
Fix feature postpone if no subs

### LINKED ISSUE #10436: Files get deleted in manual PP whereas PP should be postponed
When Manual PP, when:
- postpone if no subtitles is enabled in the setting
- Delete files and folders is turned on the manual PP settings
if there are no subtitles, the file gets deleted.

Capture d’écran 2022-03-27 à 08 47 13

Capture d’écran 2022-03-27 à 08 48 22

```
2022-03-27 08:02:21 DEBUG    POSTPROCESSOR :: [9b23c72] Starting new thread: POSTPROCESSOR
2022-03-27 08:02:21 INFO     POSTPROCESSOR :: [9b23c72] Processing path: /home/**********/Downloads/Completed/MedusaUS
2022-03-27 08:02:21 INFO     POSTPROCESSOR :: [9b23c72] Feature 'postpone post-processing if no subtitle available' is enabled.
2022-03-27 08:02:21 DEBUG    POSTPROCESSOR :: [9b23c72] No processable items found in folder: /home/**********/Downloads/Completed/MedusaUS
2022-03-27 08:02:21 DEBUG    POSTPROCESSOR :: [9b23c72] No resource_name passed, using path [/home/**********/Downloads/Completed/MedusaUS/Euphoria.US.S01.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-KiNGS[rartv]] to process as a source folder
2022-03-27 08:02:21 DEBUG    POSTPROCESSOR :: [9b23c72] Processing folder: /home/**********/Downloads/Completed/MedusaUS/Euphoria.US.S01.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-KiNGS[rartv]
2022-03-27 08:02:21 DEBUG    POSTPROCESSOR :: [9b23c72] Post-processing files: ['Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv']
2022-03-27 08:02:21 DEBUG    POSTPROCESSOR :: [9b23c72] Post-processing video files: ['Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv']
2022-03-27 08:02:21 DEBUG    POSTPROCESSOR :: [9b23c72] Using cache item for /home/**********/Downloads/Completed/MedusaUS/Euphoria.US.S01.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-KiNGS[rartv]/Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv
2022-03-27 08:02:22 DEBUG    POSTPROCESSOR :: [9b23c72] Video '/home/**********/Downloads/Completed/MedusaUS/Euphoria.US.S01.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-KiNGS[rartv]/Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv' scanned using mediainfo 'libmediainfo.so.0' has raw data:
<?xml version="1.0" encoding="utf-8"?>
<Mediainfo version="18.08.1">
  <File>
    <track type="General">
      <Count>331</Count>
      <Count_of_stream_of_this_kind>1</Count_of_stream_of_this_kind>
      <Kind_of_stream>General</Kind_of_stream>
      <Kind_of_stream>General</Kind_of_stream>
      <Stream_identifier>0</Stream_identifier>
      <Unique_ID>104503554635609542979467301725602968870</Unique_ID>
      <Unique_ID>104503554635609542979467301725602968870 (0x4E9EA70B56AC4BED5EA5BEDC00A9F526)</Unique_ID>
      <Count_of_video_streams>1</Count_of_video_streams>
      <Count_of_audio_streams>1</Count_of_audio_streams>
      <Video_Format_List>AVC</Video_Format_List>
      <Video_Format_WithHint_List>AVC</Video_Format_WithHint_List>
      <Codecs_Video>AVC</Codecs_Video>
      <Audio_Format_List>E-AC-3</Audio_Format_List>
      <Audio_Format_WithHint_List>E-AC-3</Audio_Format_WithHint_List>
      <Audio_codecs>E-AC-3</Audio_codecs>
      <Audio_Language_List>English</Audio_Language_List>
      <Complete_name>/home/**********/Downloads/Completed/MedusaUS/Euphoria.US.S01.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-KiNGS[rartv]/Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv</Complete_name>
      <Folder_name>/home/**********/Downloads/Completed/MedusaUS/Euphoria.US.S01.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-KiNGS[rartv]</Folder_name>
      <File_name>Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv</File_name>
      <File_name>Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS</File_name>
      <File_extension>mkv</File_extension>
      <Format>Matroska</Format>
      <Format>Matroska</Format>
      <Format_Url>https://matroska.org/downloads/windows.html</Format_Url>
      <Format_Extensions_usually_used>mkv mk3d mka mks</Format_Extensions_usually_used>
      <Commercial_name>Matroska</Commercial_name>
      <Format_version>Version 4</Format_version>
      <File_size>3479229086</File_size>
      <File_size>3.24 GiB</File_size>
      <File_size>3 GiB</File_size>
      <File_size>3.2 GiB</File_size>
      <File_size>3.24 GiB</File_size>
      <File_size>3.240 GiB</File_size>
      <Duration>3233254</Duration>
      <Duration>53 min 53 s</Duration>
      <Duration>53 min 53 s 254 ms</Duration>
      <Duration>53 min 53 s</Duration>
      <Duration>00:53:53.254</Duration>
      <Duration>00:53:54;00</Duration>
      <Duration>00:53:53.254 (00:53:54;00)</Duration>
      <Overall_bit_rate_mode>CBR</Overall_bit_rate_mode>
      <Overall_bit_rate_mode>Constant</Overall_bit_rate_mode>
      <Overall_bit_rate>8608613</Overall_bit_rate>
      <Overall_bit_rate>8 609 kb/s</Overall_bit_rate>
      <Frame_rate>23.976</Frame_rate>
      <Frame_rate>23.976 FPS</Frame_rate>
      <Frame_count>77520</Frame_count>
      <Stream_size>811098</Stream_size>
      <Stream_size>792 KiB (0%)</Stream_size>
      <Stream_size>792 KiB</Stream_size>
      <Stream_size>792 KiB</Stream_size>
      <Stream_size>792 KiB</Stream_size>
      <Stream_size>792.1 KiB</Stream_size>
      <Stream_size>792 KiB (0%)</Stream_size>
      <Proportion_of_this_stream>0.00023</Proportion_of_this_stream>
      <IsStreamable>Yes</IsStreamable>
      <Encoded_date>UTC 2019-06-17 10:52:33</Encoded_date>
      <File_last_modification_date>UTC 2022-03-26 22:09:42</File_last_modification_date>
      <File_last_modification_date__local_>2022-03-26 23:09:42</File_last_modification_date__local_>
      <Writing_application>mkvmerge v34.0.0 ('Sight and Seen') 64-bit</Writing_application>
      <Writing_application>mkvmerge v34.0.0 ('Sight and Seen') 64-bit</Writing_application>
      <Writing_library>libebml v1.3.7 + libmatroska v1.5.0</Writing_library>
      <Writing_library>libebml v1.3.7 + libmatroska v1.5.0</Writing_library>
    </track>
    <track type="Video">
      <Count>347</Count>
      <Count_of_stream_of_this_kind>1</Count_of_stream_of_this_kind>
      <Kind_of_stream>Video</Kind_of_stream>
      <Kind_of_stream>Video</Kind_of_stream>
      <Stream_identifier>0</Stream_identifier>
      <StreamOrder>0</StreamOrder>
      <ID>1</ID>
      <ID>1</ID>
      <Unique_ID>16213319671984929130</Unique_ID>
      <Format>AVC</Format>
      <Format>AVC</Format>
      <Format_Info>Advanced Video Codec</Format_Info>
      <Format_Url>http://developers.videolan.org/x264.html</Format_Url>
      <Commercial_name>AVC</Commercial_name>
      <Format_profile>High@L4</Format_profile>
      <Format_settings>CABAC / 4 Ref Frames</Format_settings>
      <Format_settings__CABAC>Yes</Format_settings__CABAC>
      <Format_settings__CABAC>Yes</Format_settings__CABAC>
      <Format_settings__ReFrames>4</Format_settings__ReFrames>
      <Format_settings__ReFrames>4 frames</Format_settings__ReFrames>
      <Internet_media_type>video/H264</Internet_media_type>
      <Codec_ID>V_MPEG4/ISO/AVC</Codec_ID>
      <Codec_ID_Url>http://ffdshow-tryout.sourceforge.net/</Codec_ID_Url>
      <Duration>3233230.000000</Duration>
      <Duration>53 min 53 s</Duration>
      <Duration>53 min 53 s 230 ms</Duration>
      <Duration>53 min 53 s</Duration>
      <Duration>00:53:53.230</Duration>
      <Duration>00:53:54;00</Duration>
      <Duration>00:53:53.230 (00:53:54;00)</Duration>
      <Bit_rate_mode>CBR</Bit_rate_mode>
      <Bit_rate_mode>Constant</Bit_rate_mode>
      <Bit_rate>7966666</Bit_rate>
      <Bit_rate>7 967 kb/s</Bit_rate>
      <Nominal_bit_rate>10000000</Nominal_bit_rate>
      <Nominal_bit_rate>10 000 kb/s</Nominal_bit_rate>
      <Width>1920</Width>
      <Width>1 920 pixels</Width>
      <Height>1080</Height>
      <Height>1 080 pixels</Height>
      <Stored_Height>1088</Stored_Height>
      <Sampled_Width>1920</Sampled_Width>
      <Sampled_Height>1080</Sampled_Height>
      <Pixel_aspect_ratio>1.000</Pixel_aspect_ratio>
      <Display_aspect_ratio>1.778</Display_aspect_ratio>
      <Display_aspect_ratio>16:9</Display_aspect_ratio>
      <Frame_rate_mode>CFR</Frame_rate_mode>
      <Frame_rate_mode>Constant</Frame_rate_mode>
      <Frame_rate>23.976</Frame_rate>
      <Frame_rate>23.976 (24000/1001) FPS</Frame_rate>
      <FrameRate_Num>24000</FrameRate_Num>
      <FrameRate_Den>1001</FrameRate_Den>
      <Frame_count>77520</Frame_count>
      <Color_space>YUV</Color_space>
      <Chroma_subsampling>4:2:0</Chroma_subsampling>
      <Chroma_subsampling>4:2:0</Chroma_subsampling>
      <Bit_depth>8</Bit_depth>
      <Bit_depth>8 bits</Bit_depth>
      <Scan_type>Progressive</Scan_type>
      <Scan_type>Progressive</Scan_type>
      <Bits__Pixel_Frame_>0.160</Bits__Pixel_Frame_>
      <Delay>0</Delay>
      <Delay>00:00:00.000</Delay>
      <Delay__origin>Container</Delay__origin>
      <Delay__origin>Container</Delay__origin>
      <Stream_size>3219758148</Stream_size>
      <Stream_size>3.00 GiB (93%)</Stream_size>
      <Stream_size>3 GiB</Stream_size>
      <Stream_size>3.0 GiB</Stream_size>
      <Stream_size>3.00 GiB</Stream_size>
      <Stream_size>2.999 GiB</Stream_size>
      <Stream_size>3.00 GiB (93%)</Stream_size>
      <Proportion_of_this_stream>0.92542</Proportion_of_this_stream>
      <Default>Yes</Default>
      <Default>Yes</Default>
      <Forced>No</Forced>
      <Forced>No</Forced>
      <Buffer_size>31250000</Buffer_size>
      <Color_range>Limited</Color_range>
      <colour_description_present>Yes</colour_description_present>
      <Color_primaries>BT.709</Color_primaries>
      <Transfer_characteristics>BT.709</Transfer_characteristics>
      <Matrix_coefficients>BT.709</Matrix_coefficients>
    </track>
    <track type="Audio">
      <Count>298</Count>
      <Count_of_stream_of_this_kind>1</Count_of_stream_of_this_kind>
      <Kind_of_stream>Audio</Kind_of_stream>
      <Kind_of_stream>Audio</Kind_of_stream>
      <Stream_identifier>0</Stream_identifier>
      <StreamOrder>1</StreamOrder>
      <ID>2</ID>
      <ID>2</ID>
      <Unique_ID>15875770715706031085</Unique_ID>
      <Format>E-AC-3</Format>
      <Format>E-AC-3</Format>
      <Format_Info>Enhanced AC-3</Format_Info>
      <Format_Url>https://en.wikipedia.org/wiki/Dolby_Digital_Plus</Format_Url>
      <Commercial_name>Dolby Digital Plus</Commercial_name>
      <Commercial_name>Dolby Digital Plus</Commercial_name>
      <Format_settings__Endianness>Big</Format_settings__Endianness>
      <Internet_media_type>audio/eac3</Internet_media_type>
      <Codec_ID>A_EAC3</Codec_ID>
      <Duration>3233248.000000</Duration>
      <Duration>53 min 53 s</Duration>
      <Duration>53 min 53 s 248 ms</Duration>
      <Duration>53 min 53 s</Duration>
      <Duration>00:53:53.248</Duration>
      <Duration>00:54:19:10</Duration>
      <Duration>00:53:53.248 (00:54:19:10)</Duration>
      <Bit_rate_mode>CBR</Bit_rate_mode>
      <Bit_rate_mode>Constant</Bit_rate_mode>
      <Bit_rate>640000</Bit_rate>
      <Bit_rate>640 kb/s</Bit_rate>
      <Channel_s_>6</Channel_s_>
      <Channel_s_>6 channels</Channel_s_>
      <Channel_positions>Front: L C R, Side: L R, LFE</Channel_positions>
      <Channel_positions>3/2/0.1</Channel_positions>
      <Channel_layout>L R C LFE Ls Rs</Channel_layout>
      <Samples_per_frame>1536</Samples_per_frame>
      <Sampling_rate>48000</Sampling_rate>
      <Sampling_rate>48.0 kHz</Sampling_rate>
      <Samples_count>155195904</Samples_count>
      <Frame_rate>31.250</Frame_rate>
      <Frame_rate>31.250 FPS (1536 SPF)</Frame_rate>
      <Frame_count>101039</Frame_count>
      <Compression_mode>Lossy</Compression_mode>
      <Compression_mode>Lossy</Compression_mode>
      <Delay>6</Delay>
      <Delay>6 ms</Delay>
      <Delay>6 ms</Delay>
      <Delay>6 ms</Delay>
      <Delay>00:00:00.006</Delay>
      <Delay__origin>Container</Delay__origin>
      <Delay__origin>Container</Delay__origin>
      <Delay_relative_to_video>6</Delay_relative_to_video>
      <Delay_relative_to_video>6 ms</Delay_relative_to_video>
      <Delay_relative_to_video>6 ms</Delay_relative_to_video>
      <Delay_relative_to_video>6 ms</Delay_relative_to_video>
      <Delay_relative_to_video>00:00:00.006</Delay_relative_to_video>
      <Stream_size>258659840</Stream_size>
      <Stream_size>247 MiB (7%)</Stream_size>
      <Stream_size>247 MiB</Stream_size>
      <Stream_size>247 MiB</Stream_size>
      <Stream_size>247 MiB</Stream_size>
      <Stream_size>246.7 MiB</Stream_size>
      <Stream_size>247 MiB (7%)</Stream_size>
      <Proportion_of_this_stream>0.07434</Proportion_of_this_stream>
      <Language>en</Language>
      <Language>English</Language>
      <Language>English</Language>
      <Language>en</Language>
      <Language>eng</Language>
      <Language>en</Language>
      <Service_kind>CM</Service_kind>
      <Service_kind>Complete Main</Service_kind>
      <Default>Yes</Default>
      <Default>Yes</Default>
      <Forced>No</Forced>
      <Forced>No</Forced>
      <bsid>16</bsid>
      <dialnorm>-31</dialnorm>
      <dialnorm>-31 dB</dialnorm>
      <compr>-0.28</compr>
      <compr>-0.28 dB</compr>
      <acmod>7</acmod>
      <lfeon>1</lfeon>
      <dialnorm_Average>-31</dialnorm_Average>
      <dialnorm_Average>-31 dB</dialnorm_Average>
      <dialnorm_Minimum>-31</dialnorm_Minimum>
      <dialnorm_Minimum>-31 dB</dialnorm_Minimum>
      <dialnorm_Maximum>-31</dialnorm_Maximum>
      <dialnorm_Maximum>-31 dB</dialnorm_Maximum>
      <dialnorm_Count>582</dialnorm_Count>
      <compr_Average>-4.35</compr_Average>
      <compr_Average>-4.35 dB</compr_Average>
      <compr_Minimum>-10.55</compr_Minimum>
      <compr_Minimum>-10.55 dB</compr_Minimum>
      <compr_Maximum>-0.56</compr_Maximum>
      <compr_Maximum>-0.56 dB</compr_Maximum>
      <compr_Count>217</compr_Count>
    </track>
  </File>
</Mediainfo>

2022-03-27 08:02:22 DEBUG    POSTPROCESSOR :: [9b23c72] Handling general track
2022-03-27 08:02:22 DEBUG    POSTPROCESSOR :: [9b23c72] Handling video track
2022-03-27 08:02:22 DEBUG    POSTPROCESSOR :: [9b23c72] Handling audio track
2022-03-27 08:02:22 DEBUG    POSTPROCESSOR :: [9b23c72] Skipping rule language since property is already present: <Language [en]>
2022-03-27 08:02:22 DEBUG    POSTPROCESSOR :: [9b23c72] No associated files were found for /home/**********/Downloads/Completed/MedusaUS/Euphoria.US.S01.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-KiNGS[rartv]/Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv
2022-03-27 08:02:22 DEBUG    POSTPROCESSOR :: [9b23c72] No subtitles associated. Postponing the post-processing of this file: Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv
2022-03-27 08:02:22 INFO     POSTPROCESSOR :: [9b23c72] Not deleting folder /home/**********/Downloads/Completed/MedusaUS/Euphoria.US.S01.REPACK.1080p.AMZN.WEBRip.DDP5.1.x264-KiNGS[rartv] found the following files: ['Euphoria.US.S01E01.Pilot.1080p.AMZN.WEB-DL.DDP5.1.H.264-KiNGS.mkv']
2022-03-27 08:02:22 DEBUG    POSTPROCESSOR :: [9b23c72] Ignoring folder: .stfolder
2022-03-27 08:02:22 INFO     POSTPROCESSOR :: [9b23c72] Post-processing completed.
2022-03-27 08:02:22 INFO     POSTPROCESSOR :: [9b23c72] I did encounter some unprocessable items: 
2022-03-27 08:02:22 WARNING  POSTPROCESSOR :: [9b23c72] Missed file: /home/**********/Downloads/Completed/MedusaUS/.stfolder: Hidden or ignored folder
```

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Fix #10436

### CODE REVIEW

**Comment by p0psicles** [comment]
[NicoLeOca](https://github.com/NicoLeOca) could you test this branch please

**Comment by p0psicles** [comment]
@NicoLeOca you still committed to test this out?

**Comment by NicoLeOca** [comment]
sure!

can you describe precisely what is the expected behaviour in various conditions please?
by conditions, I refer to the 3 possible ways for PP to get run.
1 manual
2 daily
3 automatic

**Comment by p0psicles** [comment]
So with Daily you mean the `Periodic postprocessing` and automatic the `Download Handling`.
So these to should postpone the processing right now.

But TBH I only did some refactoring in this PR. And I suspect it already worked in the code pre-this-PR.

**Comment by NicoLeOca** [comment]
Yes I do

as I use docker, it would need to be merged into develop for me to test though

**Comment by p0psicles** [comment]
okay @NicoLeOca merged. Please extensively test

**Comment by p0psicles** [comment]
@NicoLeOca hows testing going?

**Comment by NicoLeOca** [comment]
Hi @p0psicles 
Just testing now, as I was away last week

**Comment by NicoLeOca** [comment]
Hi @p0psicles 

So I have added many new TV shows to Medusa.
In most cases, the episodes contain subs "out of the box"; more now than ever before as most content are webrips from streaming services.
However, I progress.

AndI have issues with Periodic postprocessing.
if episodes don't have subs, they get deleted, just the same as with manual PP

PS: I don't know if this would occur with Download Handling as I didn't have episodes without subs downloaded that way

**Comment by NicoLeOca** [comment]
@p0psicles 
Hi! Do you have feedback for me? Should I carry on testing?

**Pull request merged**
