### PR TITLE
Add RSS Feed Client

### PR DESCRIPTION
**Pull request by sawyersteven**
- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Adds a RSS feed *client* for both nzb and torrents.

Why?

In broad strokes, its similar to a blackhole client in that Medusa will simply grab the result and promptly forget about it, requiring the client to alert Medusa when the download is complete and ready for processing.

The main benefit is that this allows for a download client on a different network to simply read the rss file (which can be exposed easily through any reverse proxy) instead of needing to mount the blackhole directory to download and/or delete torrent and nzb files.

It also allows an effortless one-to-many relationship between Medusa and a download client in case you want to send the feed to several different locations to download simultaneously. I can't think of a particular use case for that, but I'm sure it can help someone.

The frontend changes will need to be built before merging with master. My frontend skills are not great, though I did get this to build and run. Still, it seemed wise to me to let someone familiar with npm and yarn and everything else to do it properly.

### CODE REVIEW

**Comment by medariox** [comment]
Thanks for the PR, it looks great!
Can you fix the test please? https://github.com/pymedusa/Medusa/blob/31bbc700d56c7443e0ceffdda5252765ca53d960/tests/apiv2/test_config.py#L506
`section_data['rss'] = {}` needs to be added to the test.

**Comment by sawyersteven** [comment]
> Thanks for the PR, it looks great! Can you fix the test please?
> 
> https://github.com/pymedusa/Medusa/blob/31bbc700d56c7443e0ceffdda5252765ca53d960/tests/apiv2/test_config.py#L506
> 
> 
> `section_data['rss'] = {}` needs to be added to the test.

Done. You probably saw that I did manage to get the frontend built around my changed (I know almost nothing about npm or any of that workflow) and the massive amount of changes that produced. Is that going to be a problem? I can revert that commit if that would make merging easier.

**Comment by medariox** [comment]
@sawyersteven 
It looks like you built the themes for master, you should build for develop instead. To do that, in the themes-default/slim folder, `run yarn install --prod false --force && yarn dev` to build the themes for develop.

**Comment by medariox** [comment]
Your test seems to be failing with Python 3.7, see: https://github.com/pymedusa/Medusa/actions/runs/4217939243/jobs/7352586386#step:5:93

**Comment by sawyersteven** [comment]
Seems to be a problem with ElementTree putting xml attributes in a random order, which (of course) worked fine for me when I tested it. I just pushed a better test and the frontend build with the command posted above.

**Comment by medariox** [comment]
Still failing: https://github.com/pymedusa/Medusa/actions/runs/4249622034/jobs/7394514823

**Comment by sawyersteven** [comment]
Well that's irritating. A classic case of *it works on my machine*

I'll have to try and abuse it some and see what the problem is.

**Comment by medariox** [comment]
Will be available with the upcoming release. Thank you!

**Comment by sawyersteven** [comment]
Awesome, thank you!

**Pull request merged**
