### PR TITLE
Improve NameParserCache logic. Try to fix #2044, #2035

### LINKED ISSUE #2044: [APP SUBMITTED]: KeyError: u'D:\\- Series\\NCIS [2003]\\Season 07\\NCIS [2003] - S07E12 - Flesh and Blood.avi'
### INFO
**Python Version**: `2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]`
**Operating System**: `Windows-10-10.0.10586`
**Locale**: `cp1252`
**Branch**: [fix-isinstance](../tree/fix-isinstance)
**Database**: `44.4`
**Commit**: pymedusa/Medusa@ee778e94195098ec9d602703ba0dcbb0b3db8192
**Link to Log**: https://gist.github.com/2646047b6705f9dec943af60d8a30039
### ERROR
<pre>
2017-01-26 05:25:40 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [BinSearch] :: [ee778e9] Error while searching BinSearch, skipping: D:\- Series\NCIS [2003]\Season 07\NCIS [2003] - S07E12 - Flesh and Blood.avi
Traceback (most recent call last):
  File "H:\usr\local\medusa\medusa\search\core.py", line 418, in search_for_needed_episodes
    cur_found_results = cur_provider.search_rss(episodes)
  File "H:\usr\local\medusa\medusa\providers\generic_provider.py", line 425, in search_rss
    return self.cache.find_needed_episodes(episodes)
  File "H:\usr\local\medusa\medusa\tv_cache.py", line 463, in find_needed_episodes
    if not show_name_helpers.filterBadReleases(cur_result[b'name']):
  File "H:\usr\local\medusa\medusa\show_name_helpers.py", line 82, in filterBadReleases
    NameParser().parse(name)
  File "H:\usr\local\medusa\medusa\name_parser\parser.py", line 239, in parse
    name_parser_cache.add(name, result)
  File "H:\usr\local\medusa\medusa\name_parser\parser.py", line 430, in add
    del self._previous_parsed[self._previous_parsed.keys()[0]]
  File "C:\Python\latest\lib\collections.py", line 85, in __delitem__
    dict_delitem(self, key)
KeyError: u'D:\\- Series\\NCIS [2003]\\Season 07\\NCIS [2003] - S07E12 - Flesh and Blood.avi'
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
Im running this for a month. I prefer a time erase. Not quantity

Remove previous parsed when parsed >24 hours
https://github.com/fernandog/Medusa/commit/1c6cf734e6ad3e141388966abbfa7fb538f53b8c

maybe the setting should be linked to the trim cache setting

**Comment by medariox** [comment]
I doubt that is a good idea, but if you want to discuss it, it will need a new PR.

**Comment by fernandog** [comment]
i said two ideas:

1) Remove by time not but quantity of data

2) Link cache trim with remove by time

so why is not a good idea? With quantity you don't have a baseline to pick a value (like 1000)
with time you can.

**Comment by medariox** [comment]
There are likely many reason why time based cache should be avoided. For once it allows to the cache to grow to an extend that might be undesired and creates unnecessary overhead. The code you linked is just incredibly inefficient.

Anyway, this discussion has nothing to do with this PR. Open a new PR or whatever.

**Comment by p0psicles** [comment]
Often a dumb fast is fulfilling its task better then a smart 'slower'  one.  You have to take that into account.

**Comment by fernandog** [comment]
you said: "For once it allows the cache to grow to an extend that might be undesired"

undesired? how if I set to erase all cached when > x hours/days ?!

**Comment by medariox** [comment]
Because you can't know how many items will be added in that time frame, as different users have completely different needs, provider amounts, subtitles on/off, and so on.

**Comment by fernandog** [comment]
so 1000 is enough based on what? maybe too much? maybe need 10.000?

for @duramato maybe 1000 is not enough.
for a user with only one provider 1000 is overkill

**Pull request merged**
