### PR TITLE
RIP ek()

### PR DESCRIPTION
**Pull request by ratoaq2**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
git clone in windows, started with `python SickBeard.py`

```
python SickBeard.py
Traceback (most recent call last):
  File "SickBeard.py", line 9, in <module>
    from start import Application
  File "C:\SickRage\start.py", line 91, in <module>
    import medusa as app
  File "C:\SickRage\medusa\__init__.py", line 34, in <module>
    from . import (
  File "C:\SickRage\medusa\filesystem.py", line 55, in <module>
    replace_functions()
  File "C:\SickRage\medusa\filesystem.py", line 52, in replace_functions
    setattr(k, f, make_closure(getattr(k, f)))
AttributeError: 'module' object has no attribute 'chown'
```
so I patched code to
```python
        for k, v in affected_functions.items():
            for f in v:
                try:
                    setattr(k, f, make_closure(getattr(k, f)))
                except AttributeError:
                    pass
```

Medusa started.
I clicked to add a new show, as it was a new install i needed to `Pick the parent folder`, so when file browser appeared i got this:
```
2016-09-23 19:33:04 ERROR    Thread-26 :: [3599a64] Failed doing web ui callback: Traceback (most recent call last):
  File "C:\Users\Fernando\SickRage\medusa\server\web\core\base.py", line 269, in async_call
    result = function(**kwargs)
  File "C:\Users\Fernando\SickRage\medusa\server\web\core\file_browser.py", line 21, in index
    return json.dumps(list_folders(path, True, bool(int(includeFiles))))
  File "c:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "c:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 21: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Fernando\SickRage\medusa\server\web\core\base.py", line 269, in async_call
    result = function(**kwargs)
  File "C:\Users\Fernando\SickRage\medusa\server\web\core\file_browser.py", line 21, in index
    return json.dumps(list_folders(path, True, bool(int(includeFiles))))
  File "c:\Python27\lib\json\__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "c:\Python27\lib\json\encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\Python27\lib\json\encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe1 in position 21: invalid continuation byte
```

**Comment by fernandog** [comment]
Ready for windows testing?

**Comment by ratoaq2** [comment]
@pymedusa/developers @pymedusa/contributors 
Ready to be tested :-)

**Comment by fernandog** [comment]
testing this. but im on linux with utf-8 locale

**Pull request merged**
