### PR TITLE
Adding option to set savepath for qBittorrent

### PR DESCRIPTION
**Pull request by Gabisonfire**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by Gabisonfire** [comment]
First time I'm working with yarn and js, not sure I'm supposed to commit the js/css files as well

**Comment by p0psicles** [comment]
No. You should only make changes in themes-default. Then use yarn dev

**Comment by medariox** [comment]
You should also check if it is a folder with `os.path.isdir()`.

**Comment by sharkykh** [comment]
Just FYI...
I seems that support for this has only been added in qBT 3.2.0 ([`command/upload`](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-v3.2.0-v4.0.4)#upload-torrent-from-disk)) and qBT 3.3.1 ([`command/download`](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-v3.2.0-v4.0.4)#download-torrent-from-url)).

**Comment by Gabisonfire** [comment]
@p0psicles Thanks, will do. Should I close this request and do another one at this point?

@medariox That won't work since the path cannot be verified on the client host.

@sharkykh Thanks, I'll add a note like the other settings that are 3.2 +

**Comment by p0psicles** [comment]
If you can revert the changes in this pr. Also fine with me

**Comment by p0psicles** [comment]
I think you changed more then intended?

**Comment by Gabisonfire** [comment]
https://github.com/pymedusa/Medusa/pull/8304

**Pull request closed without merging**
