### PR TITLE
LTV: Fix KeyError in custom provider

### PR DESCRIPTION
**Pull request by fernandog**
I don't have any missed subtitles so only noticed it now

@ratoaq2 @duramato

```
2017-05-31 09:37:02 WARNING  FINDSUBTITLES :: [68a0049] Unexpected error in provider 'legendastv', discarding it
Traceback (most recent call last):
  File "/home/osmc/Medusa/lib/subliminal/core.py", line 171, in download_subtitle
    self[subtitle.provider_name].download_subtitle(subtitle)
  File "/home/osmc/Medusa/lib/subliminal/core.py", line 64, in __getitem__
    raise KeyError
KeyError
```

Proof:
image

### CODE REVIEW

**Comment by fernandog** [comment]
@ratoaq2 thanks for replying. The 'subliminal sync' PR is not in master.

Also I'm doing another commit into this PR

**Comment by fernandog** [comment]
@ratoaq2 
should we add something like this to explain users about the "legendastv2" ?

image

**Comment by medariox** [comment]
@fernandog 
I would remove the note about "Legendatv2". The users don't need to know about that.

**Comment by fernandog** [comment]
removed noted

**Pull request merged**
