### PR TITLE
Testing new log style

### PR DESCRIPTION
**Pull request by ratoaq2**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
Hi @ratoaq2 what's the status of this?

**Comment by ratoaq2** [comment]
I need to fix lint issues and pick a python module to use the new style as a reference

**Comment by ratoaq2** [comment]
subtitles.py is the reference on how to use log:

```
import logger_factory

log = logger_factory.get_logger(__name__)

log.debug('Skipping {show} {ep}', dict(show=show_name, ep=ep_num))
```

**Comment by ratoaq2** [comment]
Great, codacy didn't like it

**Comment by labrys** [comment]
@ratoaq2 FYI: dict literals `{ .. }`should be preferred over dict constructors `dict( ... )`

**Pull request closed without merging**
