### PR TITLE
Check version if /git-commit exists

### PR DESCRIPTION
**Pull request by a10kiloham**
For use in Docker scenarios - checks existence of newly created /git-commit file which has the hash for the Docker version's git pull. Not sure if this is v good but please do feel free to edit if not up to snuff.

### CODE REVIEW

**Comment by p0psicles** [comment]
You've made the check part of the GitUpdateManager. But that's not an issue.
The issue is when we don't have a .git folder, with the source. So we should have a way in the SourceUpdateManager, to get the commit.

**Comment by a10kiloham** [comment]
Taking .git out of the .dockerignore file leaves a .git directly but I don't know how to get the commit out of that.

**Comment by p0psicles** [comment]
Something like this could work. Not tested:
https://gist.github.com/p0psicles/87e648522470270b9374af5aad24cf93

**Comment by p0psicles** [comment]
Okay i understand. 
But Its not a problem that we dont have the git folder.

**Pull request closed without merging**
