### PR TITLE
Fix log history not using correct action for PROPERs

### PR DESCRIPTION
**Pull request by fernandog**
Old issue since Sickrage

Also fix all user history

This is the proof the query works
```sql
SELECT action, substr(action, 1, length(action) - 2) || '09' as new_action
FROM history
WHERE action LIKE "%02" and proper_tags is not ""
```

ping @labrys

### CODE REVIEW

**Comment by labrys** [comment]
We should deprecate the `Snatched Proper` status code `09` for 2 reasons.  First it has never been fully implemented and no current code relies on it.  Secondly we now store proper tags in DB so:
`Snatched + Has Proper Tags == Snatched Proper`

**Comment by fernandog** [comment]
@labrys we use in PP to check if episode status is PROPER and a lot of other places. I wouldn't touch that now as it may break stuff that would need a lot of testing to make sure it works.

**Comment by labrys** [comment]
@fernandog my point is we shouldn't be adding more methods that use `09` status when `SNATCHED` + `PROPER TAGS` is a more reliable check.

**Comment by fernandog** [comment]
in the new DB/quality model we can ditch it. I sew no point removing it now.
as for today, history is wrong. This PR only fixes it

**Pull request closed without merging**
