### PR TITLE
Fix _encode and _decode in subtitles.py, move encoding check after lo…

### PR DESCRIPTION
**Pull request by medariox**
…gger init

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Fixes https://github.com/pymedusa/Medusa/issues/5304#issuecomment-425873874
@duramato

### CODE REVIEW

**Comment by duramato** [comment]
Just tested it, seems to fix the issue. Altough I still got some BraceMessage errors, but I don't think they are related to this: https://gist.github.com/duramato/5a53834cc20915810fa0ced5e2ad47fc

**Comment by medariox** [comment]
@duramato 
It shouldn't be related, but it's also not possible to understand where that one is coming from. I've updated the logger and it should show the real exception now. Please update the branch and see what you get this time.

**Comment by duramato** [comment]
Just gave it a test, here's the result @medariox :https://gist.github.com/duramato/c013a39978dddf3c2a0f251d95bc4f5e

**Comment by medariox** [comment]
Please try again.

**Comment by duramato** [comment]
@medariox : https://gist.github.com/duramato/72ed4395598457ff0dfcc6120b965fcc

**Comment by medariox** [comment]
Should be good now. Thanks for all the testing @duramato

**Pull request merged**
