### PR TITLE
typos and clarifications

### PR DESCRIPTION
**Pull request by cheese1**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by medariox** [comment]
Thanks! I think I prefer post-processing with the hyphen. Opinions?

**Comment by p0psicles** [comment]
If you Google it, you'll also get more hits, links to ecyclopedia with the hypen. I also think we should keep the hyphen here.

**Comment by cheese1** [comment]
will rework and get back after my holydays.

**Comment by OmgImAlexis** [comment]
post-processing is what’s in my physical dictionary and it talk about computer post-processing. I’d say go with that.

**Comment by p0psicles** [comment]
@cheese1 if you could only revert those to Post-Processing / post-processing? The other changes are good!

**Comment by cheese1** [comment]
Agreed. Is it ok if I would do that at the weekend?

**Pull request closed without merging**
