### PR TITLE
Update guessit to 3.0.3

### PR DESCRIPTION
**Pull request by MrTimscampi**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Edit: ~~No idea if I should've made a new branch for this ?~~ It's cool, merging to develop fixes the mess :)

### CODE REVIEW

**Comment by medariox** [comment]
Thanks for the effort, but when upgrading guessit we also need to update the internal tests. These are quite painful to write and some advanced understanding of guessit is required. Have a look at this PR to see what I mean: https://github.com/pymedusa/Medusa/pull/5519/files

**Comment by p0psicles** [comment]
@MrTimscampi tnx for the help. I hope we'll see more PR's from you in future. Any help is welcome.

**Comment by MrTimscampi** [comment]
@medariox Figured as much, seeing the tests failing :p I did the commit from work during a break and you got to make a fix first. Will keep it in mind for the future :)

@p0psicles I'm actually looking for stuff to do around the source to get acquainted to it :) I'd like to separate Anime from Absolute Numbering (related to #5452 ) and look at supporting multiple categories (Anime/non-anime) for indexers (Seems like right now some are anime-only and others are everything, but passing Nyaa and Anidex to everything would produce a lot of false positives).  
I also notice there's a lot of Vue stuff blocked/on hold/waiting for merge and I'd love to work on that, but it's fairly difficult to see what needs to be done (I stumbled on a meta-issue for it which I can't seem to find anymore).

In any way, you might see more once I roam around the source for a bit and if work leaves me enough time for it :)

**Comment by p0psicles** [comment]
Give me an email. And ill add you to slack

**Comment by p0psicles** [comment]
Especially for our frontend were looking for people willing to help out. Where transitioning from everything mako rendered.. To our apiv2 + a new vue frondend. The frontend will eventually be a single page app. @OmgImAlexis is in the lead for that.

**Comment by p0psicles** [comment]
Also separating anime from absolute numbered can be a welcome addition.

But expect to touch on some dark anchient code there. Needless to say it can use some refactoring.

**Pull request closed without merging**
