### PR TITLE
Check scene exceptions using season number

### PR DESCRIPTION
**Pull request by fernandog**
Possible fix to https://github.com/pymedusa/Medusa/issues/1633

@duramato

### CODE REVIEW

**Comment by fernandog** [comment]
I also had those:

```
2016-11-21 11:21:41 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [a737de1] Scene exception lookup got indexer ID 95441, using that
2016-11-21 11:21:41 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [a737de1] Scene exception lookup got indexer ID 95441, using that
2016-11-21 11:21:37 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: [a737de1] Scene exception lookup got indexer ID 95441, using that
```

**Comment by fernandog** [comment]
@p0psicles can you review this please? i don't know what you did about scene exceptions with multiple indexers and i have some concerns. ping me when you have time

**Comment by fernandog** [comment]
Related to last commit:
image

**Comment by p0psicles** [comment]
I did allot of tests. And I came to this concolusion: passing the season number is wrong. As we shouldn't assume it's the indexer season number being passed. We are getting the scene name from a search result, and we want to map using the scene name to an indexer + (possible) indexer season number. So the functionality was okay like it was.

In fernandog's example using the America Horror Story.
If we would get a result for season 4, it could look like this: American Horror Story Freak Show - S1E13.
I know that for this show, they almost always also provide the correct indexer's season number (in this case 4). But bear with me just to make my point.

In the old sitution, you would get back: indexerid: 250487+ season: 4.
After this PR, you would not get back a result. As season 1, would have been passed in the sql, and it would only compare: 'American horror story murder house'.

**Pull request closed without merging**
