### PR TITLE
Fix unable to start Medusa due to configparser ImportError

### LINKED ISSUE #5137: Update to 0.2.9 makes medusa fail to start ext/adba no module named configparser
**Describe the bug**
I upgraded to 0.2.9 from 0.2.8 and Medusa would no longer start. The problem seems to be 
related to adba. It tries to load an external module configparser import ConfigParser but it fails
to find the module and exits.

**To Reproduce**
Start medusa after upgrading to 0.2.9

**Expected behavior**
Medusa should start as usual instead of failing and exiting.

**Medusa (please complete the following information):**
 - OS: archlinux 4.18.5
 - Branch: master
 - Commit:  db3d9d7

**Logs:**

```
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/medusa/scene_exceptions.py", line 13, in <module>
Sep 07 08:07:56 norm env[30534]:     import adba
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/ext/adba/__init__.py", line 27, in <module>
Sep 07 08:07:56 norm env[30534]:     from configparser import ConfigParser
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/ext/configparser.py", line 12, in <module>
Sep 07 08:07:56 norm env[30534]:     from backports.configparser import (
Sep 07 08:07:56 norm env[30534]: ImportError: No module named configparser
Sep 07 08:07:56 norm systemd[882]: medusa.service: Control process exited, code=exited status=1
Sep 07 08:07:56 norm systemd[882]: medusa.service: Failed with result 'exit-code'.
Sep 07 08:07:56 norm systemd[882]: Failed to start Medusa user service.


Sep 07 08:07:56 norm env[30534]: Traceback (most recent call last):
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/start.py", line 6, in <module>
Sep 07 08:07:56 norm env[30534]:     from medusa.__main__ import main
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/medusa/__main__.py", line 67, in <module>
Sep 07 08:07:56 norm env[30534]:     from medusa import (
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/medusa/name_cache.py", line 12, in <module>
Sep 07 08:07:56 norm env[30534]:     from medusa.scene_exceptions import (
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/medusa/scene_exceptions.py", line 13, in <module>
Sep 07 08:07:56 norm env[30534]:     import adba
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/ext/adba/__init__.py", line 27, in <module>
Sep 07 08:07:56 norm env[30534]:     from configparser import ConfigParser
Sep 07 08:07:56 norm env[30534]:   File "/opt/Medusa/ext/configparser.py", line 12, in <module>
Sep 07 08:07:56 norm env[30534]:     from backports.configparser import (
Sep 07 08:07:56 norm env[30534]: ImportError: No module named configparser
Sep 07 08:07:56 norm systemd[882]: medusa.service: Control process exited, code=exited status=1
Sep 07 08:07:56 norm systemd[882]: medusa.service: Failed with result 'exit-code'.

```
</details>

**Additional context**

I'm guessing the problem is related to this adba commit:

https://github.com/pymedusa/Medusa/pull/4822

### PR DESCRIPTION
**Pull request by sharkykh**
### Fixes #5137 
I had a hunch that the `.pth` file I got when installing the package locally was important.
I can try to explain the fix better later, if anyone is interested, but basically [`site.addsitedir`](https://docs.python.org/2/library/site.html#site.addsitedir) adds a path to `sys.path`, plus it handles these files if any are found on the path.
However it uses `appends` and not `insert`, that's why we need to rebuild `sys.path` like in the new code.

https://bugs.python.org/issue7744

### CODE REVIEW

**Comment by hobeone** [comment]
This doesn't seem to work if you have configparser installed with a system package:

```
Traceback (most recent call last):
  File "/opt/medusa/start.py", line 6, in <module>
    from medusa.__main__ import main
  File "/opt/medusa/medusa/__main__.py", line 67, in <module>
    from medusa import (
  File "/opt/medusa/medusa/name_cache.py", line 12, in <module>
    from medusa.scene_exceptions import (
  File "/opt/medusa/medusa/scene_exceptions.py", line 13, in <module>
    import adba
  File "/opt/medusa/ext/adba/__init__.py", line 27, in <module>
    from configparser import ConfigParser
  File "/opt/medusa/ext/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: cannot import name ConverterMapping
```

After running `apt-get remove python-configparser` medusa starts as normal.

This is on Debian testing.  I ran `git reset --hard origin/master` to make sure everything was up to date but removing the system package was the only thing that got it working.

Debian package info:
```
Package: python-configparser
Source: configparser
Version: 3.5.0b2-1
```

**Comment by sharkykh** [comment]
@hobeone 
Unfortunately I don't have a way of testing this, but can you try re-adding this file:
https://github.com/pymedusa/Medusa/raw/31171bc896108a52f80cfd90f3c70f0baf205db2/ext/backports/__init__.py
Save it to `/opt/medusa/ext/backports/__init__.py`
Reinstall the `python-configparser` system package and try to run medusa.

**Comment by sharkykh** [comment]
Also I must say,
that debian package seems to be out of date with the actual library version and that's probably the reason for the issue: Current library version is [3.5.0](https://pypi.org/project/configparser/#history) (it's out of beta) - 3.5.0b2 is from **2014**.
If you still want to use the system package over installing a user package with `pip`,
I suggest contacting the debian pkg maintainer(s) to bump the version.
https://packages.debian.org/sid/python-configparser

**Comment by hobeone** [comment]
Adding that __init__.py file doesn't seem to fix it.  I get the same error code when starting.

I think you're right about the package being too old.  When I get a second I'll see about filing a request to update it.

**Pull request merged**
