### PR TITLE
Not query xem for unsupported indexers

### PR DESCRIPTION
**Pull request by fernandog**
@p0psicles @labrys

### CODE REVIEW

**Comment by labrys** [comment]
This ignores the fact that other providers (tvmaze for example) may provide a tvdb id

**Comment by fernandog** [comment]
### Before:

image

### After:

image

**Comment by fernandog** [comment]
@p0psicles why do not merge? is the best solution imo. did you see the SS from pycharm?

**Comment by p0psicles** [comment]
Your solution was not wrong. It was just putting indexer configuration in code. Which i'm trying to prevent all over the medusa code. I did the same as you, but used the xem_origin, like it was supposed to.

If tvmaze and tmdb will be supported by xem in future, xem_origin, should be put back in the config.

**Comment by p0psicles** [comment]
@labrys the confusion here came from us asuming this was doing the xem lookup for a show_id. But this is just a plain xem refresh, per indexer.

**Pull request merged**
