### PR TITLE
displayShow Edits

### PR DESCRIPTION
**Pull request by Thraxis**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Implements Request #2023

### CODE REVIEW

**Comment by p0psicles** [comment]
Nice. Maybe we should remove the thin border around the table-cell div, and put it around the image. Try to enable all custom qualities, and some preferred words. You'll see.

**Comment by Thraxis** [comment]
One thing I noticed and that could be fixed pretty easily...  the background fanart on some shows the top of the image gets cut off, could easily drop it down 50 pixels to drop it below the top bar to stop that.  some cropping will still occur due to the stretch.

All it needs is to change:

`$('.backstretch').css('opacity', MEDUSA.config.fanartBackgroundOpacity).fadeIn(500);`

to
` $('.backstretch').css('top','50px');
$('.backstretch').css('opacity', MEDUSA.config.fanartBackgroundOpacity).fadeIn(500);
`

in static/js/home/display-show.js

**Comment by fernandog** [comment]
image

**Comment by p0psicles** [comment]
Yeah got a point there @fernandog. Im also not sure if that's the best possible solution. @Thraxis what do you think?

**Comment by Thraxis** [comment]
I think I know where I need to edit to fix that issue... I'll have to wait til I get home after work to test it.

**Comment by fernandog** [comment]
@Thraxis is fixed. thanks!

**Comment by duramato** [comment]
image

**Comment by p0psicles** [comment]
So now the poster is alligned to the middle (by design). Do we want to change that? Maybe again allign to top?

**Comment by fernandog** [comment]
liked aligned top

**Comment by labrys** [comment]
I would say align to the midpoint of the background bar

**Comment by Thraxis** [comment]
There was discussion about changing the summary box to display show information.

image

**Comment by p0psicles** [comment]
Great improvement, but I think we should go with wimps design for now. Thing with these design changes is, they are always subject to personal preference. And sure we can improve, but then we should give him the creative freedom to do so.

**Pull request merged**
