### PR TITLE
show showheader on testRename.

### PR DESCRIPTION
**Pull request by wimpyrbx**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

image

### CODE REVIEW

**Comment by wimpyrbx** [comment]
Will need some help here @Thraxis in regards to the mako errors due to missing initializations.

**Comment by wimpyrbx** [comment]
note; in the screenshot.. the "there is a newer available..." notice.. nevermind that. it's a screenshot only. the PR was done with latest develop.

**Comment by fernandog** [comment]
personally i like the way its today

**Comment by fernandog** [comment]
@Thraxis are you going to continue this? - as you added "in progress"

**Comment by OmgImAlexis** [comment]
Closing this as it's likely going to have to be redone in vue.

**Pull request closed without merging**
