### PR TITLE
Rename subtitle provider from TheWiz > Wizdom

### PR DESCRIPTION
**Pull request by fernandog**
URL also changed
code from @ofir123

### CODE REVIEW

**Comment by fernandog** [comment]
@duramato did you tested? working ok?

**Comment by duramato** [comment]
Not yet

**Comment by fernandog** [comment]
@ratoaq2 please?

**Comment by fernandog** [comment]
@ratoaq2 develop provider is broken as that URL is 404 now. Need to merge to this release

**Comment by p0psicles** [comment]
I says i dismissed a review. But thats because I resolved conflicts. And merged rebase it.

**Comment by p0psicles** [comment]
@fernandog can you double check I resolved the conflicts the right way?

**Comment by fernandog** [comment]
@p0psicles thanks

**Pull request merged**
