### PR TITLE
update all js/css libs

### PR DESCRIPTION
**Pull request by OmgImAlexis**
This updates to jQuery 3.0.0 as well as fixes all the issues between migrating from 2.x.x to 3.x.x.
I've linted the Gruntfile finally.
Removed all unneeded js libs.
Updated a few libs that had security issues, etc.
`vender.min.js` now only loads for non devs where as the vender.js loads of `DEVELOPER = 1`.

### CODE REVIEW

**Comment by fernandog** [comment]
@OmgImAlexis why develop uses a diff one?

**Comment by fernandog** [comment]
Testing this and so far so good

**Comment by OmgImAlexis** [comment]
@fernandog difference what?

**Comment by fernandog** [comment]
@OmgImAlexis 

this: `<script type="text/javascript" src="js/vender${('.min', '')[app.DEVELOPER]}.js?${sbPID}"></script>`

**Comment by OmgImAlexis** [comment]
@fernandog that's so then developers can track down where in the file the errors are coming from instead of just having all of the script on a single line like the minified version does. For people like me and @p0psicles this will help a lot.

**Comment by fernandog** [comment]
approved

**Comment by fernandog** [comment]
@p0psicles if you want to review else merge it

**Pull request merged**
