### PR TITLE
add vue route

### PR DESCRIPTION
**Pull request by OmgImAlexis**
@labrys this adds the route we talked about on Slack.

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
I'll be moving the vue repo into this route so it can be tested along side the main UI.

**Comment by OmgImAlexis** [comment]
@p0psicles it's just the name for now @labrys said to just keep it with vue until we think of something else to use. I was going to use `/new` but didn't want the weird tornado regex issue of it overriding newShow, etc.

**Comment by fernandog** [comment]
are we going to merge this?

**Comment by labrys** [comment]
It's not labeled as having been concluded yet.  When its concluded and reviewed we can merge it.

**Comment by OmgImAlexis** [comment]
Closing this as I think it may be easier to add a file to handle this like @labrys and I talked about.

**Pull request closed without merging**
