### PR TITLE
Add option to split home page in tabs

### PR DESCRIPTION
**Pull request by h3llrais3r**
Add option to split home page in tabs.
If not enabled, home page is same as before.

Implementation of feature https://github.com/pymedusa/Medusa/issues/3306

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

**Screenshots**

Setting:

image

Simple layout:

image

Banner layout:

image

Small poster layout:

image

Poster layout:

image

### CODE REVIEW

**Comment by p0psicles** [comment]
LGTM

**Comment by medariox** [comment]
Should we indent Python-Style for mako or not? Let's decide once and for all.

**Comment by p0psicles** [comment]
I say yes.

**Comment by IDmedia** [comment]
On all screenshots "Series" show up before "Anime". How may I change the order of the tabs?

**Comment by p0psicles** [comment]
Go back to the non-tab poster layout. And drag the ellipsis from series down.

**Comment by p0psicles** [comment]
Then the order is also changed for the tab layout

**Pull request merged**
