### PR TITLE
Added an additional check for updating a show through the showUpdater…

### PR DESCRIPTION
**Pull request by p0psicles**
…, for shows that have episodes with missing season or episode number.

Fixes https://github.com/pymedusa/Medusa/issues/2310

Apparently this can happen for at least tvdb, when users do not properly add show information.

* Made the warning a little bit more informative. Through providing the user with some advice, on how to resolve the warning.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@p0psicles i don't think warning is the way to go. Those ep don't even appear in the tvdb website, so there is nothing user can do about

i would just ignore them

**Comment by p0psicles** [comment]
Yes it's related to that. But I do think we should provide the user with some info if they really want to resolve it for the show. Because it's still a fact that it's an issue with tvdb show info.

**Comment by fernandog** [comment]
@p0psicles my point it: they doesn't appear in http://thetvdb.com/?tab=seasonall&id=290853&lid=7

so how user will report it?

**Comment by p0psicles** [comment]
I don't know. That's their problem, if they want to resolve it. Maybe contact someone on the forums? Send them a mail. I honestly don't care. We just inform the user that this is not something we can fix for them. But that's it's data corruption on tvdb's end.

**Comment by fernandog** [comment]
i still couldn't reproduce the issue with other shows.

**Comment by p0psicles** [comment]
Thats great right?  Would be troublesome if you could reproduce this with multiple shows. We just warn for these edge cases.

**Comment by p0psicles** [comment]
We don't want this Pr?

**Comment by fernandog** [comment]
@p0psicles sure we want. otherwise we will get traceback and show won't update

why are you asking ?

**Pull request merged**
