### PR TITLE
Fix prowlarr typo

### PR DESCRIPTION
**Pull request by twolaw**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Write `prowlarr` instead of misspelled `prowler`

reviewed in https://github.com/pymedusa/Medusa/pull/9653

### CODE REVIEW

**Comment by p0psicles** [comment]
You'll need to build the theme

**Comment by twolaw** [comment]
`yarn install` returns error.
On windows:
`error @typescript-eslint/experimental-utils@5.3.1: The engine "node" is incompatible with this module. Expected version "^12.22.0 || ^14.17.0 || >=16.0.0". Got "14.16.1"`
On linux:
`error sass-loader@12.3.0: The engine "node" is incompatible with this module. Expected version ">= 12.13.0". Got "8.10.0"`

Maybe I need to update something, still investigating this new territory for me.

**Comment by p0psicles** [comment]
You'll need to latest version of nodejs

**Comment by twolaw** [comment]
Thanks, I think it's all good now

**Pull request merged**
