### PR TITLE
Improve notifiers by passing a dict and allow to send more information

### PR DESCRIPTION
**Pull request by fernandog**
Implements: https://github.com/pymedusa/Medusa/issues/3061

### CODE REVIEW

**Comment by fernandog** [comment]
@OmgImAlexis with last commit this is fully implemented:

https://github.com/pymedusa/Medusa/issues/168

**Comment by fernandog** [comment]
screenshot_20170825-120506

**Comment by fernandog** [comment]
quick looking other notifiers seems their are not following any pattern to the message. 

Like, for NMA, the title is "common.NOTIFY_SNATCH" and the message its the (don't laugh) message.
For other notifiers the common.NOTIFY_SNATCH is in the body/message

So I won't touch them for now as I don't how to add this new info without knowning how they would appear in the notifier 

ping @p0psicles

**Comment by fernandog** [comment]
Maybe pass as *args so we can keep current behavior and we can study each notifier at time

**Comment by NicoLeOca** [comment]
HI @fernandog 
I use Pushover on IOS and I would be happy to test your improvement

**Comment by fernandog** [comment]
I haven't touch that yet. Still waiting some discussion about possible pattern to notifiers text/msg

**Comment by fernandog** [comment]
If no one want this, i will close it. as I said I would like some inputs about making default messages for all notifiers

**Comment by NicoLeOca** [comment]
@fernandog 
Could you please tell us what we can talk about?
What possibilites do we have? which fields are available?

**Comment by duramato** [comment]
The format should be like this:

image

If there is a "title" field like in that image, that's where the "Started Download", "Download Finished", etc. should go and in the body what you have in your example. Outherwise if the notifier just has a "body" it should be: "Started Download: Show - 1x01 -blah -1080p WEB-DL" for example

**Comment by NicoLeOca** [comment]
@fernandog 
would you mind having a look at pushover notifier please?
I am really interested in this improvement

**Comment by OmgImAlexis** [comment]
@fernandog what's the go with this?

**Comment by p0psicles** [comment]
I think we should close this and create a Notification class. Gives more flexibility

**Pull request closed without merging**
