### PR TITLE
Adding support for the new DownlaodStation API

### PR DESCRIPTION
**Pull request by BenjV**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
Can you release it on the develop branch?

**Comment by BenjV** [comment]
done

**Comment by p0psicles** [comment]
Sorry. I meant rebase it on develop. Stupid autocorrect. It should only show your commit

**Comment by BenjV** [comment]
I am not allowed to do that

**Pull request closed without merging**
