### PR TITLE
Fix for first scene search

### PR DESCRIPTION
**Pull request by h3llrais3r**
@p0psicles  Possible fix for https://github.com/pymedusa/Medusa/issues/1978#issuecomment-273605769

- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
Hi @h3llrais3r , has your issue been resolved now? And was that using your fix or mine?

**Comment by h3llrais3r** [comment]
@p0psicles, the problem was solved with my fix. 
However, the work you did seems very promising, but I didn't have the time yet to test it.

**Comment by p0psicles** [comment]
I think that's more of a feature. Like it will also parse and accept batches. Like ```[BKT] Naruto Shippuden 321-348 (Grande guerra mondiale dei ninja, Sasuke ed Itachi)[Regolare]```. Searching for 325, would also accept this as a result.

**Comment by p0psicles** [comment]
I just tested your fix. That does seem to fix it. I'm going to keep this branch, for when the refactor has been finished.

**Comment by h3llrais3r** [comment]
@p0psicles: updated previous comment with reference to the code.
In fact I don't think my fix caused the problem. It was probably the case before because we are checking if the episode number appears in the list of parsed episode numbers. Because the batch is also found for a normal episode search, and the episode number is in it, it snatches it.

**Comment by p0psicles** [comment]
That's one the issues i'm trying to fix. The logic is currently for sick* way all over the place. So they all have search logic in determining if something should be a result, or if not then should be cached.

I'm removing the logic for "if cached". So then we can simplify to only evaluate if should be a valid result.

**Comment by p0psicles** [comment]
I've fixed it in a similar way. I'm making sure i'm translating scene_season back to indexers season, and am comparing those. Tested that with all of the scene seasons of jojo's 2012. Still doing some more tests with other shows.

**Comment by h3llrais3r** [comment]
Nice work. Will check your PR with your changes.

**Pull request closed without merging**
