### PR TITLE
Fix saving of the config - postprocess frequency.

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
@medariox you know whats going on with the flake test?

**Comment by medariox** [comment]
@p0psicles 
The new version of pycodestyle has some new rules, including `W605 invalid escape sequence` and `W504 line break after binary operator`. I've fixed W605 and excluded W504 for now.

**Comment by p0psicles** [comment]
Youve excluded 605

**Comment by p0psicles** [comment]
@sharkykh it says i need to build development.
But I did, yarn dev. And there's nothing left to build?

```
Done in 1.43s.
Please build the themes (mode: development) 
--------------------------------------------
 M themes/dark/assets/js/vendors.js
 M themes/light/assets/js/vendors.js
```

**Comment by medariox** [comment]
@p0psicles Make sure to run `yarn install` before `yarn dev`.

**Pull request merged**
