### PR TITLE
UI scaling improvements

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)
- [x] #1965 
- [x] Weird bug when you have added a new show, it redirects, an it's only showing one poster which is misplaced. (wasn't that weird. I fixed it already in another PR. Had to rebase it.)

### CODE REVIEW

**Comment by p0psicles** [comment]
@fernandog Regarding the relative published date. That should also work for newznab right? As I'm not getting results there now for the published column. Only the update column is showing it.
image

**Comment by p0psicles** [comment]
@duramato pls let me know what you think of the last commit. It has some changes which should solve the issues you had with a different poster height and show-info box height.

It should also "fix" the issue with the schedule alignment. But that could also be fixed with #1859 .

**Comment by duramato** [comment]
What i don't like that much is now the manual search page:
Now:
image
Before:
image
I have enough on screen real estate , there is no apperant reason for the release name to be chopped imo

**Comment by fernandog** [comment]
@p0psicles rebased and removed my commit

**Comment by medariox** [comment]
Is this still WIP or ready to be tested/reviewed?

**Comment by p0psicles** [comment]
fixes #1952

**Comment by p0psicles** [comment]
Implemented #1965

**Comment by medariox** [comment]
Still having this issue:
image

Release names are very bold (Chrome 55):
image2

**Comment by fernandog** [comment]
@p0psicles can't we have a "widescreen" table instead of 4:3? =)

image

**Comment by p0psicles** [comment]
1. is a rebase issue.
2. is by design, as tooltips are in bold. Like the tooltips on the episode number in display show.

**Pull request merged**
