### PR TITLE
Added support for Pushover notification priority configuration.

### PR DESCRIPTION
**Pull request by andofrjando**
Pushover supports five levels of notification priority, from very low to emergency. This is detailed https://pushover.net/api#priority and support for this is the main reason for this PR.

Also fixed a bug where failed notifications were not properly detected, and clarified which menu option will use the default sound.

The failed notifications bug was caused by the fact that 4XX HTTP response codes don't raise an exception, which is how they were trying to be detected previously. This just checks the response code rather than try and catch an exception that is never raised.

- [X] PR is based on the DEVELOP branch
- [X] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [X] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
Please rebase your pr on this pr/branch.
https://github.com/pymedusa/Medusa/pull/4913
As that pr will be merged before this one.

**Comment by p0psicles** [comment]
You can also wait on that other pr to have been merged of course

**Comment by andofrjando** [comment]
No worries. Done.  I think (I just skipped the conflicts that exist in `feature/fully-vueify-notifications` during the rebase).

**Comment by andofrjando** [comment]
A few things have gone wrong and I need to tidy some stuff up. In the interest of keeping things simple, I'm going to close this PR and open a new one in to `feature/fully-vueify-notifications` once the tidy up is complete.

**Pull request closed without merging**
