### PR TITLE
Added select for submenu navigation on mobile devices < 900px

### PR DESCRIPTION
**Pull request by p0psicles**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Always make sure the PR has a clear description of why,how, and what your trying to fix. The same goes for improvements or new features. Also if you refering to an issue, make sure a summary is available in the PR.
- [ ] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
I've marked this as a bug, cause the submenu's are almost non-navigatable on mobile devices. Al tough I doubt that this implementation is the right one.

**Comment by fernandog** [comment]
@p0psicles can you check viewlogs page too? On mobile objects overlaps

**Comment by p0psicles** [comment]
@fernandog I know that there are allot of things to improve to UI. I'm in no way interested in fixing them all. The submenu is really buggin me, so I just want to focus on that

**Comment by fernandog** [comment]
@p0psicles are you still going to continue on this?

**Comment by fernandog** [comment]
@p0psicles i think the buttons are better now that you are working in the tabs PR

**Pull request closed without merging**
