### PR TITLE
Don't log error when can't connnect to NMA

### PR DESCRIPTION
**Pull request by fernandog**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
What's wrong with it being a warning?

**Comment by fernandog** [comment]
Consistent with others notifiers

**Comment by p0psicles** [comment]
Well info is the same as putting it away. A warning will show the user it is not being notified. Then that can be a hint to the user to check what else he missed, and maybe checking the history. It could also be an indication that something is wrong with authentication?

**Comment by fernandog** [comment]
codacy stucked

**Pull request merged**
