### PR TITLE
Add VRV and RTÉjr icons

### PR DESCRIPTION
**Pull request by duramato**
Fix https://github.com/pymedusa/Medusa/issues/3231

### CODE REVIEW

**Comment by PinaColonic** [comment]
FYI the new VRV icon works but RTEJR does not, it still shows question mark icon with latest build.

**Comment by PinaColonic** [comment]
@fernandog  I got your msg "PinaColonic which image medusa is looking for? See image source please"

I'm not 100% sure how to give you what you asked for, hopefully this does the trick:

RTÉjr

Copy image address shows:  http://localhost:8081/api/v2/series/tvdb299994/asset/network?api_key=c8e0c39e02cbf2b29f863a84201ec38e which is a question mark image instead of the new RTEjr one.    The new VRV one however does work.

**Comment by fernandog** [comment]
Rename image to:
static/images/network/rtejr.png

I removed the accent

**Comment by PinaColonic** [comment]
@fernandog that did the trick!  thank you very much.

**Pull request merged**
