### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by purevertigo**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
Maybe you need to merge the latest commits of develop into your branch

**Comment by medariox** [comment]
I think he needs GH actions enabled in his fork as well.

**Comment by medariox** [comment]
Replaced by https://github.com/pymedusa/Medusa/pull/8821

**Comment by purevertigo** [comment]
thanks @medariox @p0psicles for fixing. I have GH actions enabled so I'm really not sure what is happening.

**Pull request closed without merging**
