### PR TITLE
13-10

### PR DESCRIPTION
**Pull request by purevertigo**
Updated Network Logos

### CODE REVIEW

**Comment by p0psicles** [comment]
These changes have already been merged?

**Comment by purevertigo** [comment]
Weird @p0psicles it tacked onto the other ones from the other day. Should I create a new commit again?

**Comment by p0psicles** [comment]
You probably didn't update your develop branch. When we merge a pr, we squash the commits of the pr.

Best to pull changes from medusa:develop into your develop. And push back to your fork.

**Comment by purevertigo** [comment]
Closed for incorrect push.

**Pull request closed without merging**
