### PR TITLE
fix pill overlap on backlogOverview

### LINKED ISSUE #2187: Quality pills too cramped with the "Wanted/Quality" pill
It even goes as far as beeing hidden by the [low] `Quality` pill
captura de ecra de 2017-02-16 23 22 17
captura de ecra de 2017-02-16 23 22 29

### PR DESCRIPTION
**Pull request by Thraxis**
+ Fixes #2187

image

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
I didnt liked. 

Why not align with quality column?
We could use the "show more" if > x pills

**Comment by Thraxis** [comment]
Well for one thing I forgot to fix the column headers.  the "Quality" column is the "Download Status" column,  The "Status" column is the "Episode name" column.

**Comment by Thraxis** [comment]
But yes I was thinking of using a "Custom" pill with a click to expand to show all the others

**Comment by fernandog** [comment]
@Thraxis what about like this?

use `row` and set a max column width so it never overlaps the button?

image

**Comment by Thraxis** [comment]
Think this might work out for looking a bit cleaner.

image

**Comment by fernandog** [comment]
Agree. Its better

**Pull request merged**
