### PR TITLE
Warn about possible subtitle match

### PR DESCRIPTION
**Pull request by fernandog**
Fix for https://github.com/pymedusa/Medusa/issues/2950

@ratoaq2 @duramato

### CODE REVIEW

**Comment by ratoaq2** [comment]
Well, I dislike this feature. 
You have missing subtitles page, manual sub search and here you're just reruning guessit for every sub search

**Comment by fernandog** [comment]
A real example:

WARNING  FINDSUBTITLES :: [7a152d4] Consider doing a manual subtitle search for: TURN.Washingtons.Spies.S04E04.Nightmare.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv

Notice:
DDP5 vs DD5
WEBRIP vs WEB-DL

Subtitle:
"Turn.S04E04.Nightmare.1080p.AMZN.WEBRip.DD5.1.x264-ViSUM"

**Comment by fernandog** [comment]
@ratoaq2 Im not using guessit. Im using the property `subtitle.get_matches(video)`

**Comment by medariox** [comment]
Isn't this exactly what missed subtitles management is for? Check it after X days and use manual search.

**Comment by fernandog** [comment]
Each episode has it own "3 days" without subs as each one has it own airdate/download date

**Comment by fernandog** [comment]
Also even if after 3 days it may not have subs. This doesn't  search. It only warns about existing subs it already found

**Comment by medariox** [comment]
The point is: if you don't have the subs after X days (looking at the missed subs page), you will know you should try to search with manual subs search, there is no need for such a warning. Additionally, a warning is something that went wrong with the system, it is not suitable for this kind of information. A much better approach would be to integrate some kind of visual notification to the missed subtitles page.

**Comment by fernandog** [comment]
On hold because get_matches is not cached. Need to think about it

**Comment by fernandog** [comment]
@medariox like this? =)

image

**Pull request closed without merging**
