### PR TITLE
Remove dark background for add existing show

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

_Before:_
img

_After:_
img2

### CODE REVIEW

**Comment by p0psicles** [comment]
Could we not just make the text white? Wouldn't that look better?

**Comment by medariox** [comment]
Sure thing! I personally like the contrast, but as long as it isn't black on black (like now), I'm fine with it,

**Comment by p0psicles** [comment]
I was thinking about a white divs border and white text. Maybe make it bold.

**Comment by medariox** [comment]
LGTM, thanks! (I can't approve this myself)

**Pull request merged**
