### PR TITLE
Fixes TB's FL torrent's having the tagging part of the name

### PR DESCRIPTION
**Pull request by duramato**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

Fixes: ```The.Wire.S01.1080p.BluRay.x264-SCENE[F L]```, which should be ```The.Wire.S01.1080p.BluRay.x264-SCENE``` upon parsing.

image

### CODE REVIEW

**Comment by duramato** [comment]
Why was this closed?

**Comment by fernandog** [comment]
you cant commit to master!

**Comment by duramato** [comment]
If you would have said that, i would have known. 
By just closing I can't read your mind. To me you could even have miss clicked the close button..

**Pull request closed without merging**
