### PR TITLE
Trakt: Create episode object because we need the actual status (from db)

### PR DESCRIPTION
**Pull request by fernandog**
Create episode object because we need the actual status (from db)
Otherwise we will read default blank episode status (UNKNOWN)

This can happen if show never got updated
So self.episodes would be empty and the episode object in trakt would be None

### CODE REVIEW

**Comment by p0psicles** [comment]
@fernandog you implemented this here: https://github.com/pymedusa/Medusa/commit/a6af9b96f10e053cfb6045c1d390db6413af37d4

What was the reason you changed this in that commit?

**Comment by fernandog** [comment]
@p0psicles the no_create=True is only used in trakt and in another place. After debugging med issue i found out that no_create param doesn't load (my idea was to avoid re-load, that's why i used it) the episode from database but if show we never updated, the ep obj will never be created. I'm my tests the show was always updated so I didn't found this issue

**Comment by p0psicles** [comment]
Does the param have any use then? Shouldn't we also remove it?

**Comment by fernandog** [comment]
@p0psicles i already asked @ratoaq2 if we can deprecated/remove it

**Comment by p0psicles** [comment]
@fernandog please don't use bugfix/ for branches your merging into develop. /bugfix and /hotfix are kind of reserved for other purposes.

**Pull request merged**
