### PR TITLE
Fix imdb info

### PR DESCRIPTION
**Pull request by duramato**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
Imdb_info is already populated at that point?

**Comment by duramato** [comment]
`imdb_info` always exists as an empty dictionary, and as the countries are added before this changed code https://github.com/pymedusa/Medusa/blob/fix/imdb-info/medusa/tv/series.py#L1566-L1567 before this change ìmdb_info` would get overwritten by this

**Comment by medariox** [comment]
The empty string probably needs to stay for the DB (didn't check).

**Comment by medariox** [comment]
Did you make sure that the DB is going to be fine without countries and country_codes set? None isn't the same as an empty string, let's avoid to create inconstancies in the DB.

**Comment by p0psicles** [comment]
I'll make sure.

**Comment by p0psicles** [comment]
I checked. But, those keys are not available if there are no country codes right?
If there not available, there not written to the db. In that case for sqlite there is not much of a difference between not writing to the field, or writing an empty string.

I could use this as a workaround to be sure:
```
self.imdb_info['countries'] = self.imdb_info.get('countries', '')
self.imdb_info['country_codes'] = self.imdb_info.get('country_codes', '')
```

**Pull request merged**
