### PR TITLE
Feature/fix dvd order

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Fix for #3783

### CODE REVIEW

**Comment by p0psicles** [comment]
@Rouzax can you test this branch?

**Comment by Rouzax** [comment]
@p0psicles There is no `tvdb_dvd_order_ep_ignore` in my config.ini after moving to the Dev branch.
Do I just add it under `[General]` section?

**Comment by Rouzax** [comment]
When I change to DVD order in the show it will still generate the warnings:
```
2018-02-20 09:48:17 WARNING  SHOWQUEUE-UPDATE :: [0531a9f] No DVD order available for episode (season: 5, episode: 9.0). Falling back to non-DVD order. Please consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 09:48:17 WARNING  SHOWQUEUE-UPDATE :: [0531a9f] No DVD order available for episode (season: 9, episode: 2.0). Falling back to non-DVD order. Please consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 09:48:17 WARNING  SHOWQUEUE-UPDATE :: [0531a9f] No DVD order available for episode (season: 9, episode: 1.0). Falling back to non-DVD order. Please consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 09:48:17 WARNING  SHOWQUEUE-UPDATE :: [0531a9f] No DVD order available for episode (season: 4, episode: 4.0). Falling back to non-DVD order. Please consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 09:48:17 WARNING  SHOWQUEUE-UPDATE :: [0531a9f] No DVD order available for episode (season: 5, episode: 5.0). Falling back to non-DVD order. Please consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 09:48:17 WARNING  SHOWQUEUE-UPDATE :: [0531a9f] No DVD order available for episode (season: 5, episode: 4.0). Falling back to non-DVD order. Please consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 09:48:17 WARNING  SHOWQUEUE-UPDATE :: [0531a9f] No DVD order available for episode (season: 5, episode: 1.0). Falling back to non-DVD order. Please consider disabling DVD order for the show: Buurman en Buurman(80767)
```

**Comment by p0psicles** [comment]
@Rouzax. If you go to settings, and just save it once, it's added.
Can you also pull the last commit? I've improved the logging a little. Should make more sense now.

**Comment by Rouzax** [comment]
@p0psicles Just did it again, I was able to set the option with the explanation you gave.
Still have 10 Warnings remaining while it were 80 something before, these remaining might be the ones that are not on the DVDs.
```
2018-02-20 16:40:50 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 1, episode: 89). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:50 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 1, episode: 90). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:50 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 1, episode: 91). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:50 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 1, episode: 88). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:49 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 1, episode: 50). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:49 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 0, episode: 1). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:49 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 0, episode: 3). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:49 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 0, episode: 2). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:49 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 1, episode: 4). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
2018-02-20 16:40:49 WARNING  SHOWQUEUE-UPDATE :: [22df759] No DVD order available for episode (season: 1, episode: 87). Skipping this episode. If you want to have this episode visible, please change it on the TheTvdb site, or consider disabling DVD order for the show: Buurman en Buurman(80767)
```

**Pull request merged**
