### PR TITLE
Changed usage of trakt images. Using tvdb apiv2 for the posters.

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

* Made a change to have to default poster (when no poster available from tvdb) works. It's not downloading a default poster, but using the default poster located in the static content.

### CODE REVIEW

**Comment by p0psicles** [comment]
@pymedusa/developers are there any other locations, where we download/use trakt images?

**Comment by p0psicles** [comment]
For this build to succeed we need to merge and rebase on: #1321

**Comment by fernandog** [comment]
@p0psicles concluded then?

**Comment by fernandog** [comment]
Approved

**Pull request merged**
