### PR TITLE
Remove checks that prevent adding show without any episodes.

### PR DESCRIPTION
**Pull request by p0psicles**
For example status 'upcoming'

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read the [contribution guide](https://github.com/pymedusa/Medusa/blob/master/.github/CONTRIBUTING.md)

Was able to add show `star trek picard` with some minor adjustments to the code.
Really wondering if there are any other reasons why we don't support this?

Just running some tests to see if implementing this is desirable/possible: #6730

tested indexers
* tvdb: star trek picard
* tvmaze: star trek picard
* tmdb: the witcher (2020)

### CODE REVIEW

**Comment by p0psicles** [comment]
@medariox what do you think?

**Comment by medariox** [comment]
I think we can try it. Not in this release, but the next. But all indexers need to be supported, not just theTVDB.

**Comment by p0psicles** [comment]
@medariox shall we clean up the lint errors and merge?

**Comment by medariox** [comment]
Sure. What about tvmaze?

**Comment by medariox** [comment]
We should also consider https://github.com/pymedusa/Medusa/issues/6832 for this PR.

**Comment by p0psicles** [comment]
Ow yeah I'll it to this pr

**Pull request merged**
